### ISSUE TITLE
Feature req: set FreeNAS comments field (org.freenas:description) to PVC name

### ISSUE THREAD

**Issue by growse** [democratic-csi/democratic-csi#10]
I can see from the source there's a few TODOs around setting zfs properties on volumes (https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-ssh/index.js#L349) and wanted to suggest another one. The previous freenas-iscsi-provisioner set the FreeNAS comments field on each managed share to the PVC name that was used to request it. This is quite useful as it allows at a glance in the FreeNAS UI to see a bit more detail about which k8s claim own a given volume (which is just called `pvc-{uuid}`). 

I wonder how easy it would be for `controller-zfs-ssh` to get the PVC name and then add that property to the created dataset under `org.freenas:description`?

*edit: I wonder if the description on the iSCSI Extent could also be set similarly?

**Comment by travisghansen** [comment]
csi has no notion of pvc name or namespaces at all. I’m trying to remain `co` (container orchestrator) agnostic with the project and left it out (also partly because I simply didn’t have access to the data).

I did however discover recently that there is a flag you can set on one of the components which will send that info into the create volume call making it hypothetically viable.

**Comment by travisghansen** [comment]
OK, I just implemented this...you'll need to use the latest chart and make sure you pull in the latest images for the project as well.

```
zfs:
  # can be used to set arbitrary values on the dataset/zvol
  # can use handlebars templates with the parameters from the storage class/CO
  #datasetProperties:
  #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

  ...
  datasetParentName: tank/k8s/a/vols
  ...
```

Try it out and let me know how it goes.

**Comment by growse** [comment]
Looks like the volume is being created and the property is being set:

```
newtank/k8s/pvc-40251839-b5bc-4582-9994-2d54690511f4  org.freenas:description                           default/mbsync-iscsi-claim                        local
```

But it seems like there's a missing quote bug somewhere meaning the PVC never comes out of pending:

````
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver verbose: FreeNAS ISCSI TARGET_TO_EXTENT: {"id":60,"iscsi_extent":57,"iscsi_lunid":0,"iscsi_target":54}
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver verbose: ZfsProcessManager command: /sbin/zfs set democratic-csi:freenas_iscsi_targettoextent_id="60" newtank/k8s/pvc-40251839-b5bc-4582-9994-2d54690511f4
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver info: FreeNAS iqn: iqn.2005-10.org.freenas.ctl:csi-pvc-40251839-b5bc-4582-9994-2d54690511f4
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver verbose: ZfsProcessManager command: /sbin/zfs set democratic-csi:csi_share_volume_context="{\"node_attach_driver\":\"iscsi\",\"portal\":\"192.168.2.2:3260\",\"portals\":\"\",\"interface\":\"\",\"iqn\":\"iqn.2005-10.org.freenas.ctl:csi-pvc-40251839-b5bc-4582-9994-2d54690511f4\",\"lun\":0}" newtank/k8s/pvc-40251839-b5bc-4582-9994-2d54690511f4
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver error: handler error - driver: FreeNASDriver method: CreateVolume error: Error: Unmatched '"'.
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver
zfs-iscsi-democratic-csi-controller-74875b7cf4-6nn7n csi-driver { code: 13, message: `Error: Unmatched '"'.\n` }
````

However, running `zfs get` on the relevent zfs vol:

```
newtank/k8s/pvc-40251839-b5bc-4582-9994-2d54690511f4  democratic-csi:csi_share_volume_context           {"node_attach_driver":"iscsi","portal":"192.168.2.2:3260","portals":"","interface":"","iqn":"iqn.2005-10.org.freenas.ctl:csi-pvc-40251839-b5bc-4582-9994-2d54690511f4","lun":0}  local
```

Config is:

```
        zfs:
            datasetParentName: newtank/k8s
            detachedSnapshotsDatasetParentName: newtank/k8s/snaps
            datasetProperties:
                org.freenas:description: |
                    {{ parameters.[csi.storage.k8s.io/pvc/namespace]}}/{{parameters.[csi.storage.k8s.io/pvc/name]}}
                # "" (inherit), lz4, gzip-9, etc
                # "" (inherit), on, off, verify
            zvolCompression: null
            zvolDedup: null
            zvolEnableReservation: false
            # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
            zvolBlocksize: null
````
