### ISSUE TITLE
Pure api based truenas driver (ssh dependency removed)

### ISSUE THREAD

**Issue by travisghansen** [democratic-csi/democratic-csi#101]
I’m working on a purely api based driver for truenas (currently requires latest/greatest scale). Any takers to do some early testing?

SCALE 21.08 epic: https://jira.ixsystems.com/browse/NAS-110637
SCALE 21.10 epic: https://jira.ixsystems.com/browse/NAS-111870

**Comment by infra-monkey** [comment]
Hey,
I could spin up an instance of truenas easily for that but i can't setup a new k8s cluster for testing.
Is it possible to deploy another democratic-csi in another namespace without interfering with the existing one? I think so but not sure...

**Comment by travisghansen** [comment]
Yeah you don’t even need to use another namespace. Just a new helm release name and unique storage class names etc

**Comment by travisghansen** [comment]
In order to test this out use the existing helm chart with values to mimic nearly exactly the existing freenas drivers with a few changes:

```
controller:
  driver:
    image: democraticcsi/democratic-csi:next
    imagePullPolicy: Always
    logLevel: debug

node:
  driver:
    image: democraticcsi/democratic-csi:next
    imagePullPolicy: Always
    logLevel: debug
```

Remove the `sshConnection` block entirely.

Ensure `datasetPermissionsUser` and `datasetPermissionsGroup` are numeric instead of alpha, ie:

```
  #datasetPermissionsGroup: root
  #datasetPermissionsGroup: wheel
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0
```
