### ISSUE TITLE
freenas-api-nfs seems to require minimum pvc of 1GiB?

### ISSUE THREAD

**Issue by ahgraber** [democratic-csi/democratic-csi#114]
When using the new `freenas-api-nfs` driver  trying to create a PVC of size 128Mi, I get an error that the minimum size is 1GiB. This did not seem to occur using the older driver with SSH.

pvc.yaml
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-homer
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "csi-truenas-nfs"
  resources:
    requests:
      storage: 128Mi
```

Excerpt from `kubectl describe pvc`:

```
Warning  ProvisioningFailed    104s (x8 over 3m50s)  org.democratic-csi.truenas-nfs_k-work-03_31cd949d-72c8-43f3-aac0-cb7da97eb4a5  failed to provision volume with StorageClass "csi-truenas-nfs": rpc error: code = Internal desc = Error: {"pool_dataset_update.refquota":[{"message":"Should be greater or equal than 1073741824 or Should be 0","errno":22}]}
```
