### ISSUE TITLE
Update description of share in truenas to use PVC name instead of PV name?

### ISSUE THREAD

**Issue by ahgraber** [democratic-csi/democratic-csi#115]
I'm wondering if its possible to add a more informative description of the dataset (specifically, the NFS share) to Truenas.  Currently, when a PV is allocated, the information in Truenas is:

| path | `/mnt/ssdpool/csi/nfs/v/pvc-c9aab11e-a7e2-42b1-ab0f-2ec325135c8b` 
| --- | --- |
| description |`democratic-csi (org.democratic-csi.truenas-nfs): ssdpool/csi/nfs/v/pvc-c9aab11e-a7e2-42b1-ab0f-2ec325135c8b` |

I'd like the NFS share `description` to be the `pvc` name instead of the `pv` name.  I have set this in the config using the `org.freenas:description` entry, which annotates the zfs pool metadata, and I'd like to replicate for the NFS metadata.  Do you know the key for this entry (or how to find it)?  

Here's most of my secret/configmap for reference, if it helps:

```
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    meta.helm.sh/release-name: nfs-democratic-csi
    meta.helm.sh/release-namespace: democratic-csi
  name: secret-democratic-csi-driver-config-nfs
  namespace: democratic-csi
stringData:
  driver-config-file.yaml: |-
    driver: freenas-api-nfs
    ## generate guid `uuidgen` per helm release
    httpConnection:
      protocol: http
      host: "${TRUENAS_IP}"
      port: 80
      apiKey: "${TRUENAS_APIKEY}"
      allowInsecure: true
    zfs:
      cli:
        ## allow non-root user to sudo
        sudoEnabled: true

      # can be used to set arbitrary values on the dataset/zvol
      # use handlebars templates with the parameters from the storage class/CO
      datasetProperties:
        "org.freenas:description": "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # standard volume naming overhead is 46 chars; datasetParentName should therefore be 17 chars or less
      datasetParentName: ssdpool/csi/nfs/v
```
