### ISSUE TITLE
Consistently getting first time sudo message

### ISSUE THREAD

**Issue by Jacksondr5** [democratic-csi/democratic-csi#120]
I'm having some difficulty setting up here.  I'm trying to set up freenas-nfs targeting a TrueNAS Core instance.  I've tried using the root account and a non-root account, with passwords and SSH keys.  I'm consistently getting the first time sudo message and an error about a terminal being required:
```
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
```
I tried sshing into the nas with the non-root account and running sudo but the message came back after a bit.  I've also tried setting my non-root user with the following settings via the `cli` command:
```
password_disabled: true
sudo: true
sudo_nopasswd: true
```

I'm not sure where to go from here and would appreciate any help!  Please let me know what additional information is needed.

On the bright side, this project worked surprisingly well on my Raspberry Pi cluster.  I was expecting to have to swap out images for ARM64 friendly ones, but everything just worked.

**Comment by travisghansen** [comment]
Welcome! Send over your full yaml/config and that will help. Make sure to cleanse sensitive details first.

**Comment by Jacksondr5** [comment]
```yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

storageClasses:
- name: j5-nas-sc
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=3
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

driver:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 10.0.10.20
      port: 80
      username: nas-writer
      apiKey: '**********'
      allowInsecure: true
    sshConnection:
      host: 10.0.10.20
      port: 22
      username: nas-writer
      # use either password or key
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        *******
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      cli:
        sudoEnabled: true
      datasetParentName: nas/k8s/vols
      detachedSnapshotsDatasetParentName: nas/k8s/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: nas-writer
      datasetPermissionsGroup: nas-writer
    nfs:
      shareHost: 10.0.10.20
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root  #note: I have also tried putting nas-writer here 
      shareMaprootGroup: wheel #note: I have also tried putting nas-writer here
      shareMapallUser: ""
      shareMapallGroup: ""
```
