### ISSUE TITLE
Freenas-iscsi csi-controller CrashLoopBackOff on OpenShift

### ISSUE THREAD

**Issue by Boltovnya** [democratic-csi/democratic-csi#131]
### Issue
When deploying the helm chart, the controller pod loses all containers except the csi-driver container with CrashLoopBackOff. Error: `Probe Error: TypeError: Cannot read property 'replace' of undefined`.

Node pod runs fine with all containers

#### external-provisioner

```
I1105 20:11:13.154140       1 feature_gate.go:243] feature gates: &{map[]}
I1105 20:11:13.154306       1 csi-provisioner.go:132] Version: v2.1.0
I1105 20:11:13.154348       1 csi-provisioner.go:155] Building kube configs for running in cluster...
I1105 20:11:13.177974       1 connection.go:153] Connecting to unix:///csi-data/csi.sock
I1105 20:11:13.178821       1 common.go:111] Probing CSI driver for readiness
I1105 20:11:13.178854       1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
I1105 20:11:13.178872       1 connection.go:183] GRPC request: {}
I1105 20:11:13.191263       1 connection.go:185] GRPC response: {}
I1105 20:11:13.191369       1 connection.go:186] GRPC error: rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of undefined
E1105 20:11:13.191419       1 csi-provisioner.go:193] CSI driver probe failed: rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of undefined
```

#### external-resizer
```
I1105 20:11:13.597955       1 main.go:83] Version : v1.1.0
I1105 20:11:13.607344       1 connection.go:153] Connecting to unix:///csi-data/csi.sock
I1105 20:11:13.608176       1 common.go:111] Probing CSI driver for readiness
I1105 20:11:13.608205       1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
I1105 20:11:13.608216       1 connection.go:183] GRPC request: {}
I1105 20:11:13.617865       1 connection.go:185] GRPC response: {}
I1105 20:11:13.617959       1 connection.go:186] GRPC error: rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of undefined
F1105 20:11:13.618037       1 main.go:121] failed probing CSI driver: CSI driver probe failed: rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of undefined
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc00000e001, 0xc000224000, 0xb8, 0x1da)
	/workspace/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2451940, 0xc000000003, 0x0, 0x0, 0xc00049bd50, 0x23a2d9b, 0x7, 0x79, 0x40e000)
	/workspace/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0x2451940, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc000490550, 0x1, 0x1)
	/workspace/vendor/k8s.io/klog/v2/klog.go:732 +0x16f
k8s.io/klog/v2.(*loggingT).print(...)
	/workspace/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/klog/v2.Fatal(...)
	/workspace/vendor/k8s.io/klog/v2/klog.go:1482
main.main()
	/workspace/cmd/csi-resizer/main.go:121 +0x114a

goroutine 7 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x2451940)
	/workspace/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
created by k8s.io/klog/v2.init.0
	/workspace/vendor/k8s.io/klog/v2/klog.go:417 +0xdf

goroutine 16 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0004f3f00)
	/workspace/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:69 +0xc8
created by google.golang.org/grpc.newCCBalancerWrapper
	/workspace/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:60 +0x172

goroutine 49 [chan receive]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000140000)
	/workspace/vendor/google.golang.org/grpc/clientconn.go:1213 +0x709
created by google.golang.org/grpc.(*addrConn).connect
	/workspace/vendor/google.golang.org/grpc/clientconn.go:843 +0x12a

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0x7fda6ac73f18, 0x72, 0x1a35180)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0000bc318, 0x72, 0xc000284000, 0x8000, 0x8000)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000bc300, 0xc000284000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc0000bc300, 0xc000284000, 0x8000, 0x8000, 0x8f25be, 0x400000801, 0x8)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000b6208, 0xc000284000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/net/net.go:182 +0x8e
bufio.(*Reader).Read(0xc000201680, 0xc00003cff8, 0x9, 0x9, 0xc00028409d, 0x4, 0x18)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x1a30de0, 0xc000201680, 0xc00003cff8, 0x9, 0x9, 0x9, 0xc0000d8e28, 0x40e098, 0x20)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/io/io.go:314 +0x87
io.ReadFull(...)
	/go/pkg/csiprow.XXXXehmkDC/go-1.15/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc00003cff8, 0x9, 0x9, 0x1a30de0, 0xc000201680, 0x0, 0xc000000000, 0x164f640, 0xc0005a0090)
	/workspace/vendor/golang.org/x/net/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc00003cfc0, 0xc0005a0080, 0xc0005a0080, 0x0, 0x0)
	/workspace/vendor/golang.org/x/net/http2/frame.go:492 +0xa5
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc000498380)
	/workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1317 +0x179
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:330 +0xfb1

goroutine 51 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0000c9450, 0x1, 0x0, 0x0, 0x0, 0x0)
	/workspace/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:395 +0x125
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc000201860, 0x0, 0x0)
	/workspace/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:515 +0x1d3
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc000498380)
	/workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:376 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/workspace/vendor/google.golang.org/grpc/internal/transport/http2_client.go:374 +0x1185
```

#### external-snapshotter
```
I1105 20:11:14.129588       1 main.go:87] Version: v3.0.3
I1105 20:11:14.133968       1 connection.go:153] Connecting to unix:///csi-data/csi.sock
I1105 20:11:14.142336       1 main.go:136] CSI driver name: "org.democratic-csi.iscsi"
W1105 20:11:14.147365       1 metrics.go:333] metrics endpoint will not be started because `metrics-address` was not specified.
I1105 20:11:14.147385       1 common.go:111] Probing CSI driver for readiness
E1105 20:11:14.150272       1 main.go:142] error waiting for CSI driver to be ready: CSI driver probe failed: rpc error: code = Internal desc = TypeError: Cannot read property 'replace' of undefined
```

#### csi-driver
```
{"level":"info","message":"initializing csi driver: freenas-iscsi","service":"democratic-csi"}
{"level":"debug","message":"setting default identity service caps","service":"democratic-csi"}
{"level":"debug","message":"setting default identity volume_expansion caps","service":"democratic-csi"}
{"level":"debug","message":"setting default controller caps","service":"democratic-csi"}
{"level":"debug","message":"setting default node caps","service":"democratic-csi"}
{"level":"info","message":"starting csi server - name: org.democratic-csi.iscsi, version: 1.4.2, driver: freenas-iscsi, mode: controller, csi version: 1.2.0, address: , socket: unix:///csi-data/csi.sock","service":"democratic-csi"}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-go/1.34.0\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: TypeError: Cannot read property 'replace' of undefined","service":"democratic-csi"}
{
  code: 13,
  message: "TypeError: Cannot read property 'replace' of undefined"
}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-go/1.34.0\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: TypeError: Cannot read property 'replace' of undefined","service":"democratic-csi"}
{
  code: 13,
  message: "TypeError: Cannot read property 'replace' of undefined"
}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: GetPluginInfo call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-go/1.29.0\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"info","message":"new response - driver: FreeNASSshDriver method: GetPluginInfo response: {\"name\":\"org.democratic-csi.iscsi\",\"vendor_version\":\"1.4.2\"}","service":"democratic-csi"}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-go/1.29.0\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: TypeError: Cannot read property 'replace' of undefined","service":"democratic-csi"}
{
  code: 13,
  message: "TypeError: Cannot read property 'replace' of undefined"
}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: TypeError: Cannot read property 'replace' of undefined","service":"democratic-csi"}
{
  code: 13,
  message: "TypeError: Cannot read property 'replace' of undefined"
}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: TypeError: Cannot read property 'replace' of undefined","service":"democratic-csi"}
{
  code: 13,
  message: "TypeError: Cannot read property 'replace' of undefined"
}
```

### Config
```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"

controller:
  driver:
    logLevel: debug
  rbac:
    openshift:
      privileged: true

node:
  rbac:
    openshift:
      privileged: true
  driver:
    localtimeHostPath: false
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists

# add note here about volume expansion requirements
storageClasses:
  - name: freenas-iscsi-csi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: ext4

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"

    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      #      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
      #      # if doing CHAP
      #      node-db.node.session.auth.authmethod: CHAP
      #      node-db.node.session.auth.username: foo
      #      node-db.node.session.auth.password: bar
      #
      #      # if doing mutual CHAP
      #      node-db.node.session.auth.username_in: baz
      #      node-db.node.session.auth.password_in: bar
      node-publish-secret:
      controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      host: <HOST>
      port: 80
      apiKey: $API_KEY
      allowInsecure: true
      apiVersion: 2
    sshConnection:
      host: <HOST>
      port: 22
      username: $USER
      password: $PASSWORD
    zfs:
      cli:
        paths:
          zfs: /usr/local/sbin/zfs
          zpool: /usr/local/sbin/zpool
          sudo: /usr/local/bin/sudo
          chroot: /usr/sbin/chroot
      datasetParentName: master-knower/csi/iscsi/v
      datasetSnapshotsDatasetParentName: master-knower/csi/iscsi/s
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlockSize:
    iscsi:
      targetPortal: "$IP:3260"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-cluster"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extendDisablePhysicalBlocksize: true
      extendBlockSize: 4096
      extentRpm: "7200"
      extentAvailThreshold: 0

    #...
```

### Environment:
Red Hat OpenShift Container Platform 4.9.0 (SNO)
