### ISSUE TITLE
zfs-local (non ephemereal) a possibility (possibly a feature request)

### ISSUE THREAD

**Issue by DanieleVistalli** [democratic-csi/democratic-csi#148]
Hi, I would like to investigate if democratic could support ZOL datasets exposted to pods in filesystem mode.

My use case is that I want to provision node-bound PVs (as my application supports application based replication) and I would like to have the actual ZFS dataset mounted to the POD (my need is for RWO volumes, but being node-local RWX should just be possible for free).

Being plain ZFS dataset I would like to be able to use dataset snapshots directly. I don't need (and don't want) to put another filesystem on top of PVs provisioned this way.

Is this something that can be considered ?

**Comment by travisghansen** [comment]
It’s been a while since I looked into it but last I recall it was not possible with pure/standard csi/k8s semantics and required something like crds to fill in the gaps.

There is a project that does exactly that however: https://github.com/openebs/zfs-localpv

Is there something with that project which doesn’t meet your needs?

**Comment by DanieleVistalli** [comment]
Thank you for the prompt response. I know OpenEBS solution but my intention would be that of picking a single product to cover it all. That's just it. Btw I will perform a side by side test of Democratic and zfs-localpv to see if I can have what I need mixing the two.

Tanks for the great job. I'm anyway going to use Democratic for it's current use cases.

I will try to learn more about CSI semantics to figure out if there's some new way to achieve what I asked for (I'm not good enought for developing but if we find a way we might be able to hire somebody to implement and go for a PR to add it)

**Comment by travisghansen** [comment]
It has been discussed with the k8s team (and there may even be some PRs floating around). The predominant issue is enforcing that k8s invokes ‘controller’ operations on the node the pod is scheduled to. In the last year or so some additional features have been added which make it closer to feasible: https://github.com/kubernetes-csi/external-provisioner#distributed-provisioning

I’ll need to revisit but if the k8s pieces have all come together then the answer to the original request is a resounding yes (and it would be quite easy to implement).

**Comment by DanieleVistalli** [comment]
Thanks for the additional feedback. I now understand the challenge you described above (locality of execution). While everybody wants RWX storage that's anywhere I'm asking for "strictly local" things.

Should I keep this open or just close it ?

**Comment by travisghansen** [comment]
Understood entirely. The bits may all be there at this point I’m not entirely sure. It’s been a while since I visited the matter honestly.

Let’s leave it open and see what the current state is. I’ll ask around on csi slack and see what the current state of the ecosystem is.

Unrelated but what storage system do you use for ‘remote’ volume use-cases?

**Comment by DanieleVistalli** [comment]
For "remote" use case we use FreeNas / Truenas and we are pretty happy with it, this is the reason I came looking into democratic-csi and we will definitely move to it.

For one of our application stacks NFS is not good enogh and iSCSI proved to not be good enough also. 

This stack is actually a database and can perform application level replication (so we are happy with RWO  and let the app-stack sync amongs it's nodes and underlying PVs).

In this case having local (direct attach) ZFS datasets is perfect as we have normal unix filesystem calls (no NFS locking issues). Also the dataset that each pod address is made of millions of files (our largest env so far is addressing 15 Tb of data from a single pod). This same workload proved to fail / perform poorly over NFS to a remote FreeNAS.

We currently run this locally to ZOL datasets, we provision those in a semi-automated way (but not k8s integrated) and we use local path PVs pointing straight to the ZOL dataset mount point. So from a performance and usability point of view this is perfect for what we do. From an automation ( k8s ) point of view this is like a #fail.

Being able to provision local datasets in a k8s driven way would allow us to move from manual storage provisioning to a storage-class driven design.

**Comment by travisghansen** [comment]
Yeah! I love it! Understood on all the above.

I’ll poke around at the current state of things and see where it’s at. It may have moved further than I’m aware of.

**Comment by travisghansen** [comment]
For reference this is the blog post about the work that has been done: https://kubernetes.io/blog/2021/04/14/local-storage-features-go-beta/

**Comment by travisghansen** [comment]
OK, I'm still not entirely sure about the k8s tooling, but the driver itself has been reworked/updated to support local volumes. I'll get everything committed in the next day or 2 and then start testing actual deployment in k8s.

The great thing is it heavily leverages all the work already done for the other zfs drivers so the code paths are well-tested and unified across the board. Some minor changes were made to the node/mounting/etc side of the equation to support local zfs volumes but that was minor.

Of note (this can be changed), in order to make it work seamlessly with the rest of the node tooling I've decided to force `zfs set mountpoint=legacy <dataset>` on the datasets. This means a couple things:

- the data will not be available at 'standard' zfs mount paths like you would typically see
- `mount -t zfs ...` works as you would expect
- when the volume is not in use by k8s, it would not be mounted (unless someone did some manual mounting outside of this driver)

If you have strong feelings about the above please shout out :)

**Comment by DanieleVistalli** [comment]
First of all, thank you for your quick and detailed work.

With regard to mounting as "legacy" I have no strong feelings right now. Ideally NOBODY should mess around with managed datasets so I cannot say I don't like it (and I'm not knowledgeable enogh on ZFS to figure out other issues).

I also see this should not prevent any work in the future to support ZFS snapshots (and that is what I really care about).

Having the volume not mounted is even better.

Going crazy down the path of security we could imagine we use zfs allow/disallow to only let the driver user operate on the dataset used as the parent/root for the provisioning (maybe I'm being carried away too much).

I love that when no pod is using the dataset it is just not mounted.

So my feedback is .. go for it. What you described above makes complete sense to me.

**Comment by travisghansen** [comment]
Sounds good. csi conformance test suite is passing for both zvol- and dataset-based drivers locally, so I suspect a commit soon enough.

**Comment by DanieleVistalli** [comment]
Oh, just an extra question.

Do you see/expect issues using democratic-csi on an OpenSuse (LEAP, Kernel 5.3) + ZFS 2.1 host ?

**Comment by travisghansen** [comment]
No I wouldn't expect issues there. You definitely will need to use the host utils (zfs binary etc will not be install in the container so when invoked it will `chroot` to the host). However, you're welcome to spin up a test machine and run the csi suite to ensure everything looks good.

**Comment by DanieleVistalli** [comment]
It's on our list. Will test on Suse this week.

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/actions/runs/1780197433 first try!

**Comment by travisghansen** [comment]
OK, now tested end-to-end in a shiny new cluster where the nodes support zfs. I'll commit a new chart version to support the changes along with sample `values.yaml` files and then you should be good to do some testing in a cluster.

The k8s bits still don't support resizing (not sure if/when this will land) and snapshotting (snapshotting appears to be done, but not in a release yet).

**Comment by DanieleVistalli** [comment]
Great, we will test asap with the new chart on our test cluster and the promote to others !!! Thanks a lot

**Comment by travisghansen** [comment]
OK, chart details here: https://github.com/democratic-csi/charts/commit/265f46d3546db67bd2ba06381dd9c7f8a9e41b55

The example `values.yaml` will not work 100% right now because I haven't merged to master so you would have to override the images for the csi driver to use the `next` tag. Something like this added to the sample `values.yaml` files..

```
node:
  driver:
    image: democraticcsi/democratic-csi:next
    imagePullPolicy: Always
    logLevel: debug
```

Also for the sample config files you need to use the `next` branch here as well: https://github.com/democratic-csi/democratic-csi/tree/next/examples

Here's a full sample (with noise) that I used for testing locally:

```
# driver only works with 1.16+
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.zfs-local-dataset"
  storageCapacity: true

storageClasses:
- name: zfs-local-dataset
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  # distributed support is not yet ready
  allowVolumeExpansion: false
  parameters:
    fsType: zfs

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: nfs-client
#  secrets:
#    snapshotter-secret:


controller:
  enabled: true
  strategy: node
  
  externalProvisioner:
    extraArgs:
    - --leader-election=false
    - --node-deployment=true
    - --node-deployment-immediate-binding=false
    - --feature-gates=Topology=true
    - --strict-topology=true
    - --enable-capacity=true
    - --capacity-ownerref-level=1

  # distributed support is not yet ready
  externalResizer:
    enabled: false
  # distributed support is not yet ready
  externalSnapshotter:
    enabled: false
    extraArgs:
    - --node-deployment
    # snapshot controller option
    #- --enable-distributed-snapshotting=true

  driver:
    #image: democraticcsi/democratic-csi:latest
    image: democraticcsi/democratic-csi:next
    #image: democraticcsi/democratic-csi:v1.4.4
    imagePullPolicy: Always
    logLevel: debug

node:
  driver:
    #image: democraticcsi/democratic-csi:latest
    image: democraticcsi/democratic-csi:next
    #image: democraticcsi/democratic-csi:v1.4.4
    imagePullPolicy: Always
    logLevel: debug

driver:
  config:
    #driver: 
    # rest of per-driver config data/syntax
    driver: zfs-local-dataset

    zfs:
      datasetParentName: tank/k8s/local/dataset/v
      detachedSnapshotsDatasetParentName: tank/k8s/local/dataset/s

      datasetEnableQuotas: true
      datasetEnableReservation: false
```

**Comment by Venthe** [comment]
That's actually an amazing job, and it's precisely what I need when I need; so thank you!

My only question is - is it possible to even add `ReadWriteMany` capability? As of now, my PVC's with this requirement are not being provisioned. Unfortunately, gerrit helm chart is really adamant about having them RWX... :)

**Comment by travisghansen** [comment]
Thanks! That’s counter-intuitive for sure but I don’t think it would be difficult to allow managing that via the driver config…it probably doesn’t make much sense as a default however.

**Comment by DanieleVistalli** [comment]
I would have asked for the Sam (RWX on local volumes) I have the exact same need that's reported. I am having my test cluster updates to 1.21 so this week I finally test your work and report back. Thank you !!!

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/commit/4dd57c13bd72a593e3d02afd11b3848c28ee61f1

Wait for the build to finish here: https://github.com/democratic-csi/democratic-csi/actions/runs/1816103561 then update your containers to the current `next` image

In the driver config block simply set the `csi` block as below (it will work with zvol or dataset driver):

```
driver: zfs-local-dataset

csi:
  access_modes:
  - UNKNOWN
  - SINGLE_NODE_WRITER
  - SINGLE_NODE_SINGLE_WRITER
  - SINGLE_NODE_MULTI_WRITER
  - SINGLE_NODE_READER_ONLY
  - MULTI_NODE_READER_ONLY
  - MULTI_NODE_SINGLE_WRITER
  - MULTI_NODE_MULTI_WRITER

zfs:
  datasetParentName: ...
  ...
```
