### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by pantelis** [democratic-csi/democratic-csi#152]
Thank you for this excellent work and apologies if this is trivial or not the right way of asking for help. I followed all to the letter: 

https://www.lisenet.com/2021/moving-to-truenas-and-democratic-csi-for-kubernetes-persistent-storage/

except that for my TrueNAS Scale (latest release candidate), located in the same subnet as the k8s cluster,  I have switched to using the nfs-api that is based on another issue discussion in this repo. 

```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs-api"

storageClasses:
- name: truenas-nfs-csi-api
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

controller:
  driver:
    image: democraticcsi/democratic-csi:next
    imagePullPolicy: Always
    logLevel: debug

node:
  driver:
    image: democraticcsi/democratic-csi:next
    imagePullPolicy: Always
    logLevel: debug

driver:
  config:
    driver: freenas-api-nfs
    instance_id:
    httpConnection:
      protocol: "http"
      host: "192.168.1.177"
      port: "80"
      apiKey: "api key from github"
      allowInsecure: true
      apiVersion: 2
    zfs:
      datasetParentName: "marathon/datalake/k8s/vols"
      detachedSnapshotsDatasetParentName: "marathon/datalake/k8s/snaps"
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: "192.168.1.177"
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: "root"
      shareMaprootGroup: "root"
      shareMapallUser: ""
      shareMapallGroup: ""
```
I am on rancher RKE1 and when I launch the claim I get connection refused error as shown in the screenshot below: 

![Screenshot from 2022-02-20 16-38-22](https://user-images.githubusercontent.com/508740/154865548-07f206d5-f871-417f-9ab4-d84d710119c6.png)

Any idea what I am doing wrong or is this a known issue? 

Thank you

**Comment by travisghansen** [comment]
Welcome! Thanks for sharing the link. I had no idea that was out there so I'll add it the list of community how-tos.

Some thoughts:

- `next` is no longer required for the `-api` drivers. I would recommend `latest` or whatever the most recent tagged version is depending on your needs
- `apiKey` is not api key from github but for the nas itself (TrueNAS ui -> profile icon -> api keys)
- I highly recommend against nfsv4 unless you really have some specific need for it

I doubt any of the above will address `ECONNREFUSED` however. That error is pretty low-level and indicates something wrong at a fundamental level between the k8s nodes and the storage system. Is the storage system running on port 80 or using https/443? Maybe send a screenshot of the browser URL logged into the TrueNAS UI.

**Comment by pantelis** [comment]
Thank you !. I misspoke when I referred to  a Github apiKey - it was the TrueNAS Scale api key that I was using. your last paragraph revealed the issue: I had enabled traefik using https://truecharts.org/manual/Community%20Examples/truenas-web-gui-via-traefik/ and therefore the only change that I had to do was to change the port from 80 to 81. 
```
driver:
  config:
    driver: freenas-api-nfs
    instance_id:
    httpConnection:
      protocol: "http"
      host: "192.168.1.177"
      port: "81"
```

![image](https://user-images.githubusercontent.com/508740/154997665-91471961-6c19-48d7-9cf2-5e3570a4869d.png)

Thank you for helping resolve this. Now the PVCs are bound as shown above.
