### ISSUE TITLE
freenas-nfs: Error: {"create_ancestors":[{"message":"Field was not expected","errno":22}]}'

### ISSUE THREAD

**Issue by reefland** [democratic-csi/democratic-csi#159]
Processing a test NFS storage claim against TrueNAS CORE 12.0-U8:
```
{"level":"info","message":"new request - driver: FreeNASApiDriver method: CreateVolume call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-go/1.40.0\"]},\"flags\":0},\"request\":{\"volume_capabilities\":[{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[\"noatime\",\"nfsvers=4\"],\"fs_type\":\"nfs\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}],\"parameters\":{\"csi.storage.k8s.io/pv/name\":\"pvc-42688a22-3a62-4494-8488-ad6eeaeb4bc0\",\"fsType\":\"nfs\",\"csi.storage.k8s.io/pvc/name\":\"test-claim-nfs\",\"csi.storage.k8s.io/pvc/namespace\":\"democratic-csi\"},\"secrets\":\"redacted\",\"name\":\"pvc-42688a22-3a62-4494-8488-ad6eeaeb4bc0\",\"capacity_range\":{\"required_bytes\":\"1073741824\",\"limit_bytes\":\"0\"},\"volume_content_source\":null,\"accessibility_requirements\":null}}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASApiDriver method: CreateVolume error: Error: {\"create_ancestors\":[{\"message\":\"Field was not expected\",\"errno\":22}]}","service":"democratic-csi"}
{
  code: 13,
  message: 'Error: {"create_ancestors":[{"message":"Field was not expected","errno":22}]}'
}
```
Some digging shows this is from the TrueNAS Core 12 API not supporting this.  I was assuming the non-root `sudo` account would be used since this is not SCALE.

```
root@truenas[~]# cat /usr/local/etc/sudoers | grep k8s
k8s ALL=(ALL) NOPASSWD: ALL
```

Parts from `freenas-nfs.yaml` file:
```
    httpConnection:
      protocol: https
      host: truenas.[REDACTED]
      port: 443
      apiKey: [REDACTED]
      allowInsecure: False
      #apiVersion: 2
    sshConnection:
      host: truenas.[REDACTED]
      port: 22
      username: k8s

      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
          [REDACTED]
        -----END OPENSSH PRIVATE KEY-----

    zfs:
      cli:
        sudoEnabled: True
      # Set a comment on the zvol to identify what it belongs to
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      datasetParentName: main/k8s/nfs/v
      detachedSnapshotsDatasetParentName: main/k8s/nfs/s
      datasetEnableQuotas: True
      datasetEnableReservation: False
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
      #datasetPermissionsAcls:
      #- "-m everyone@:full_set:allow"
      #- "-m u:kube:full_set:allow"

    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: truenas.[REDACTED]
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: root
      shareMapallUser: ""
      shareMapallGroup: ""
```
