### ISSUE TITLE
Can i manually create a PV?

### ISSUE THREAD

**Issue by theautomation** [democratic-csi/democratic-csi#192]
Hi, i have successfully up and running this CSI driver. Thanks for your fantastic work! 
I was wondering if it is possible to create a PersistentVolume manually  instead of via a PerssistentVolumeClaim. When i apply the following config no Zvol where created in TrueNas. 

So question is can i create a PV manually? if yes, how should the config look like? 

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  annotations:
    pv.kubernetes.io/provisioned-by: org.democratic-csi.iscsi
  finalizers:
    - kubernetes.io/pv-protection
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: freenas-iscsi-csi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: org.democratic-csi.iscsi
    volumeHandle: test
    fsType: xfs
    volumeAttributes:
      interface: ""
      node_attach_driver: iscsi
      portal: storage-server.lan:3260
      portals: ""
      provisioner_driver: freenas-iscsi
    controllerExpandSecretRef:
      name: controller-expand-secret-freenas-iscsi-csi-zfs-iscsi-democratic
      namespace: democratic-csi
    controllerPublishSecretRef:
      name: controller-publish-secret-freenas-iscsi-csi-zfs-iscsi-democrati
      namespace: democratic-csi
    nodePublishSecretRef:
      name: node-publish-secret-freenas-iscsi-csi-zfs-iscsi-democratic-csi
      namespace: democratic-csi
    nodeStageSecretRef:
      name: node-stage-secret-freenas-iscsi-csi-zfs-iscsi-democratic-csi
      namespace: democratic-csi
```
the PV is create
$ kubectl get pv test
```
NAME   CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM   STORAGECLASS        REASON   AGE
test   1Gi        RWO            Retain           Available           freenas-iscsi-csi            7m43s

```
