### ISSUE TITLE
Provisioning fails with error field not expected when provisioning with truenas

### ISSUE THREAD

**Issue by funkel1989** [democratic-csi/democratic-csi#198]
I'm getting the below error when setting up democratic-csi to provision over nfs on my truenas core server.

```text
failed to provision volume with StorageClass "csi-truenas-nfs": rpc error: code = Internal desc = Error: {"create_ancestors":
[{"message":"Field was not expected","errno":22}]} Error: {"create_ancestors":[{"message":"Field was not expected","errno":22}]} at 
Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:392:11) at runMicrotasks (<anonymous>) at 
processTicksAndRejections (node:internal/process/task_queues:96:5) at async FreeNASApiDriver.CreateVolume 
(/home/csi/app/src/driver/freenas/api.js:2623:7) at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:177:18)

```

here is my helm release: https://github.com/funkel1989/k3s-gitops/blob/main/cluster/core/democratic-csi/nfs/helm-release.yaml
my test claim used to provision to see if this works: https://github.com/funkel1989/k3s-gitops/blob/main/cluster/core/democratic-csi/test-nfs-1.yaml

truenas version: TrueNAS-12.0-U7

if someone could point me to exactly what the error means so I can resolve it that would be the most helpful thing here for me.

Thanks all. sorry ahead of time if this is not the right place for this.

EDIT: Relized I forgot to post my driver.

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    annotations:
        meta.helm.sh/release-name: nfs-democratic-csi
        meta.helm.sh/release-namespace: democratic-csi
    name: secret-democratic-csi-driver-config-nfs
    namespace: democratic-csi
stringData:
    driver-config-file.yaml: |
        driver: freenas-api-nfs 
        instance_id: B8712266-C1B5-4DCD-9DFD-C6646C0AD3A4 
        sshConnection:   
            host: 192.168.0.22   
            port: 22   
            username: root   
            privateKey: |     
            -----BEGIN OPENSSH PRIVATE KEY-----     
            
            -----END OPENSSH PRIVATE KEY----- 
        zfs:   
            cli:     
                sudoEnabled: true   
                datasetProperties: "org.freenas:description": "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"   
                datasetParentName: /mnt/data/k8s/nfs/v   
                detachedSnapshotsDatasetParentName: /mnt/data/k8s/nfs/s   
                datasetEnableQuotas: true   
                datasetEnableReservation: false   
                datasetPermissionsMode: "0777"   
                datasetPermissionsUser: root    
                datasetPermissionsGroup: wheel 
        nfs:   
            shareCommentTemplate: "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"   
            shareHost: 192.168.0.22   
            shareAlldirs: false   
            shareAllowedHosts: []   
            shareAllowedNetworks: []   
            shareMaprootUser: root   
            shareMaprootGroup: "wheel"   
            shareMapallUser: ""   
            shareMapallGroup: """

```

**Comment by travisghansen** [comment]
Welcome! You must use the ssh variant of the driver with core, the pure api driver works with scale only.

**Comment by funkel1989** [comment]
so your suggested changes ended up getting me further. Thanks for all the help btw!

Here is my new config (I no longer do everything in a secret, was had to manage):
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: democratic-csi
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://democratic-csi.github.io/charts/
      chart: democratic-csi
      version: 0.12.0
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.truenas-nfs"
      installCRD: false

    driver:
      config:
        driver: freenas-nfs
        instance_id: B8712266-C1B5-4DCD-9DFD-C6646C0AD3A4
        httpConnection:
          protocol: http
          port: 80
          apiKey: "${SECRET_TRUENAS_APIKEY}"
          allowInsecure: true
          apiVersion: 2
        sshConnection:
          host: 192.168.0.22
          port: 22
          username: democrat
          password: "${SECRET_TRUENAS_PASSWORD}"
          # privateKey: ${SECRET_TRUENAS_PRIVATEKEY}
        zfs:
          cli:
            sudoEnabled: true
          datasetProperties:
            "org.freenas:description": "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          datasetParentName: data/k8s/nfs/v
          detachedSnapshotsDatasetParentName: data/k8s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 1001
          datasetPermissionsGroup: 1001
        nfs:
          shareCommentTemplate: "flux-{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          shareHost: 192.168.0.22
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: democrat
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""

    controller:
      enabled: true
      hostNetwork: true # set false if fails
      hostIPC: true # set false if fails
      strategy: deployment
      externalAttacher:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 24M
          limits:
            cpu: 11m
            memory: 24M
      externalProvisioner:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 24M
          limits:
            cpu: 11m
            memory: 24M
      externalResizer:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 37M
          limits:
            cpu: 11m
            memory: 37M
      external Snapshotter:
        enabled: true
        resources:
          requests:
            cpu: 11m
            memory: 24M
          limits:
            cpu: 11m
            memory: 24M
      externalHealthMonitorController:
        enabled: false
      livenessProbe:
        enabled: true
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
        logLevel: debug
        # ### for the controller, manually mount from the remote NFS server on start,
        # ### so it can dynamically create PVC (the "crude" part)
        # ### ref: https://gist.github.com/admun/4372899f20421a947b7544e5fc9f9117
        # lifecycle:
        #   postStart:
        #     exec:
        #       command: ["/bin/sh", "-c", "mkdir -p /mnt/nfs; mount ${SECRET_TRUENAS_IP}:/mnt/ssdpool/csi/nfs/v /mnt/nfs"]
        #   preStop:
        #     exec:
        #       command: ["/bin/sh","-c","umount /mnt/nfs"]
        resources:
          requests:
            cpu: 35m
            memory: 127M
          limits:
            cpu: 35m
            memory: 127M
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true

      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          # effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists

    node:
      enabled: true
      rbac:
        enabled: true
      hostNetwork: true
      hostIPC: true
      kubeletHostPath: /var/lib/kubelet
      livenessProbe:
        enabled: true
      mount:
        # should fsck be executed before mounting the fs
        checkFilesystem:
          xfs:
            enabled: true
          ext4:
            enabled: true

      cleanup:
        resources:
          requests:
            cpu: 11m
            memory: 14M
          limits:
            cpu: 11m
            memory: 14M
      driver:
        image: docker.io/democraticcsi/democratic-csi:latest
        logLevel: debug
        resources:
          requests:
            cpu: 35m
            memory: 127M
          limits:
            cpu: 35m
            memory: 127M
      driverRegistrar:
        resources:
          requests:
            cpu: 11m
            memory: 14M
          limits:
            cpu: 11m
            memory: 14M

      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          # effect: NoSchedule

    storageClasses:
      - name: csi-truenas-nfs
        defaultClass: false
        reclaimPolicy: Delete # Delete, Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - nfsvers=4
          - sec=sys

    # volumeSnapshotClasses:
    #   - name: csi-truenas-nfs
    #     deletionPolicy: Delete # Delete, Retain

    csiProxy:
      resources:
        requests:
          cpu: 11m
          memory: 14M
        limits:
          cpu: 11m
          memory: 14M

```

Here is my new error from the logs:
```
I0530 17:17:26.124075 1 controller.go:860] Started provisioner controller org.democratic-csi.truenas-nfs_k3s-m3_a766e581-3bd7-48d3-8b6d-94e68c4886b8!
--
Mon, May 30 2022 1:17:26 pm | I0530 17:17:26.124179 1 controller.go:1337] provision "democratic-csi/test-nfs-1" class "csi-truenas-nfs": started
Mon, May 30 2022 1:17:26 pm | W0530 17:17:26.124279 1 controller.go:579] "fstype" is deprecated and will be removed in a future release, please use "csi.storage.k8s.io/fstype" instead
Mon, May 30 2022 1:17:26 pm | I0530 17:17:26.124550 1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"democratic-csi", Name:"test-nfs-1", UID:"f1e07d74-a98e-42ae-8703-8b93993df7b1", APIVersion:"v1", ResourceVersion:"1220694", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "democratic-csi/test-nfs-1"
Mon, May 30 2022 1:17:26 pm | I0530 17:17:26.124663 1 connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
Mon, May 30 2022 1:17:26 pm | I0530 17:17:26.124729 1 connection.go:184] GRPC request: {"capacity_range":{"required_bytes":524288000},"name":"pvc-f1e07d74-a98e-42ae-8703-8b93993df7b1","parameters":{"csi.storage.k8s.io/pv/name":"pvc-f1e07d74-a98e-42ae-8703-8b93993df7b1","csi.storage.k8s.io/pvc/name":"test-nfs-1","csi.storage.k8s.io/pvc/namespace":"democratic-csi","fsType":"nfs"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4","sec=sys"]}},"access_mode":{"mode":7}}]}
Mon, May 30 2022 1:17:29 pm | I0530 17:17:29.146921 1 connection.go:186] GRPC response: {}
Mon, May 30 2022 1:17:29 pm | I0530 17:17:29.146983 1 connection.go:187] GRPC error: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
Mon, May 30 2022 1:17:29 pm | I0530 17:17:29.147000 1 controller.go:764] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Background: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
```
