### ISSUE TITLE
Restore from existing ZVOL

### ISSUE THREAD

**Issue by gregod-com** [democratic-csi/democratic-csi#20]
Hey @travisghansen,

I've been playing around with the snapshot functionality and all seems good so far. Nice Job! 
Is there already a solution implemented to restore/create a PVC/PV from an existing zvol on freenas in case of a disaster?
The use case would be something like this: 
1) Cluster is setup with democratic-csi via iscsi on freenas
1) Multiple deployments use volumes mounted as iscsi drives
1) Snapshots are regularly created and occasionally restored to
1) Disaster
1) Volumes need to be restored/created from existing zvols on freenas but k8s has no relation between zvols and PVs/PVCs

Or would you just suggest to mount the zvols on the freenas side and recover manually?

There are several other use cases like being able to provision a zvol manually and then use it as PVC in k8s, but the restore after disaster seems to be the most important one.

Any thoughts on this?
Cheers

**Comment by gregod-com** [comment]
ah I got it to work by creating 
1) a VolumeSnapshotContent with source.snapshotHandle: `pvc-id@snapshot-id`
1) a VolumeSnapshot referencing the VolumeSnapshotContent
1) a PVC from the VolumeSnapshot

noice
this can be closed

**Comment by travisghansen** [comment]
Sorry late getting back. A really busy time of year for me.

Maybe I misunderstood the original request. Are you trying to recover from a k8s cluster disaster? ie: import a volume into k8s that existed at some point but has been forgotten?

**Comment by gregod-com** [comment]
no worries, your replies are still fast :)

yes, exactly: i would like to import a volume (or just a snapshot of that volume) into a new cluster for whatever reason.
The reasons might be one or more of the following: 
* the cluster is corrupt and cannot be restored (just rebuild by applying all configs one-by-one)
* a new cluster is set up and the storage should be migrated
* other workflows that focus on restoring from `pre-bound` (I think that is the correct term) data

Anyways, it seems to work as expected and your implementation handles all I need. I just thing I might want to hack together a few scripts to speed up and automate the process of restoring from pre-bound volumes.

**Comment by travisghansen** [comment]
Yeah, I think it's possible to do all of it but it's a generally manual process. Basically you'd be manually creating PVs and PVCs. A simple script could probably do this *especially* because I've implemented the `ListVolumes` and `ListSnapshots` controller services...basically it's work that could be done but isn't yet.

Make note, the csi driver really has no direct notion of PVC so binding the hypothetical PVs getting created to a PVC could be tricky. In general the best approach for the use case is be damn sure you have your etcd from clusters backed up to as many places as needed (s3, offsite, etc) as often as you can :)

**Comment by gregod-com** [comment]
I get your point.
I’m not planing to use the functionality often 😂 but more as a last resort.
I just wanted to make sure that the scenario where the data is still here but I can’t access it is solvable.
I’ll let you know if I find an elegant solution, but probably it’s going to be just a “ok... it works” hack.
Cheers

**Comment by travisghansen** [comment]
Yeah, let's leave this open though as I've seen other platforms (ie: trident from NetApp) that provide tooling to do this kind of thing. At a minimum we can get it documented how to do it manually even if automated tools don't exist.

**Comment by gregod-com** [comment]
hmm ok, looks like the solution I described above with the PVC created from an existing Snapshot does not work after all. 
It `looks` like everything is working but the PV is empty when mounting it.

This is strange, since the creation of a PVC from another PVC works just as expected and this should also do some zfs-cloning-magic behind the scenes, right?

**Comment by Stormymusings** [comment]
To expand on this, would it be possible for the CSI to scan datasets in the configured location, identify datasets that don't have a corresponding PV in the cluster, and then create PVs from them based on the default (or a specified) StorageClass?

For example on the TrueNAS Core side of things I have an all-flash unit that's mapped to the CSI to provide storage for my cluster. This TrueNAS unit takes hourly and daily snapshots and replicates them to a secondary (all HDD) TrueNAS server.

In the event that my primary storage server goes down it would be awesome if I could point the CSI to my backup NAS, scan configured location where my replicated datasets live, create PVs from them, and then map (manually or with a script) those PVs to PVCs in my cluster.

It's an entirely different beast, but the way this description for Velero works makes me wonder if something like this could be built here as well:
> Velero treats object storage as the source of truth. It continuously checks to see that the correct backup resources are always present. If there is a properly formatted backup file in the storage bucket, but no corresponding backup resource in the Kubernetes API, Velero synchronizes the information from object storage to Kubernetes.
> 
> This allows restore functionality to work in a cluster migration scenario, where the original backup objects do not exist in the new cluster.

I spoke to a few other people about this kind of setup and they suggested I ignore using ZFS send/receive backups on the TrueNAS side and just stick 100% to using velero or some other backup software. I'll likely end up going this way, however since the tooling already exists in TrueNAS and it works _so well_, it might be worth exploring first. It's a lot faster to recover a multi-TB PV by pointing the cluster to a redundant copy of the PV (backup NAS) than it is to import/download multiple TBs over the wire into a newly-created PV.

Alternatively, if it's not TrueNAS that goes down but rather my k8s cluster, I could simply build a new cluster, install the CSI, scan TrueNAS for datasets/zvols and automatically have PVs created from them without needing to manually map each one.

Idk, maybe I'm way overthinking this and should leave data backup/migration to tools built specifically for that (like velero).

**Comment by travisghansen** [comment]
@gregod-com I must have missed your last comment...pvc from snapshot isn't working for you?

**Comment by travisghansen** [comment]
@Stormymusings yes, all very good stuff! There are a couple of things to note here:

- currently, all the connection details (minus secrets) actually get stored as zfs props, of note here is this includes the portals/iscsi targets/etc (those values as stored in the config are not actually used by the attach process)
- due to the above, you would likely run into issues migrating to a backup server as presumably the server is running with a different IP
- I've considered altering how this behaves, but it was an explicitly chosen design decision for various other reasons to the trade-offs need to be thought through for sure
- I'm currently exploring the import idea. I believe in the long-run this is actually how kubernetes may behave inherently if/when they begin using the `ListVolumes` functionality of csi drivers (which is implemented here)
- velero is great, but as you mentioned sometimes it's nice to have alternatives that integrate nicely with existing workflows

I don't think you're overthinking it, I love the input and am happy to discuss further! Sometimes my brain gets pretty twisted with all the options available and I had many similar design decisions to wade through just to get the project to where it is.

**Comment by gregod-com** [comment]
> @gregod-com I must have missed your last comment...pvc from snapshot isn't working for you?

No worries. It has been some time since I tried, but yes a new PVC from a snapshot is empty on my setup. I’ll try to verify today and post my results here.

**Comment by travisghansen** [comment]
Ok please do. Send over the cleansed config file as well of you don’t mind (the full helm values)? I need to check several of the settings you have so I can properly test..

**Comment by travisghansen** [comment]
I did some testing and was able to successfully use snapshots within a cluster. The only 'weirdness' I saw with data was when the fs hadn't been 'synced' when the snapshot was taken so data wasn't yet written to TrueNAS...otherwise it appeared sane.

**Comment by gregod-com** [comment]
Hey @travisghansen... boi the “today” i wrote above turned into “several weeks”. Upsi.
So yesterday and today I did a lot of testing and found you are correct about PVCs can be created also from Snapshots if those where made by the same helm deployment. So all good on that side. As for the creation of a PVC from a Snapshot that was done on another cluster I had no success. The PVC is actually getting mounted but it is empty. I’ll send my config down below.

**Comment by gregod-com** [comment]
So this is Cluster A for HDD Access

```
csiDriver:
  # should be globally unique for a given cluster
  name: "com.gregod-csi.iscsi"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-iscsi-csi-com-gregod
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
      
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    detachedVolumesFromSnapshots: "true"
    
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    detachedVolumesFromVolumes: "true"

  mountOptions: []
  secrets:
    provisioner-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: root
      node-db.node.session.auth.password: "*****"
    controller-publish-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: root
      node-db.node.session.auth.password: "*****"
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: root
      node-db.node.session.auth.password: "*****"
      # if doing mutual CHAP
      # node-db.node.session.auth.username_in: baz
      # node-db.node.session.auth.password_in: bar
    node-publish-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: root
      node-db.node.session.auth.password: "*****"
    controller-expand-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: root
      node-db.node.session.auth.password: "*****"

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses:
  - name: gregod-losangeles-k3ssnap-hdd
    secrets:
      snapshotter-secret:
        node-db.node.session.auth.authmethod: CHAP
        node-db.node.session.auth.username: root
        node-db.node.session.auth.password: "*****"
    parameters:
      # if true, snapshots will be created with zfs send/receive
      detachedSnapshots: "true"

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: some local ip
      port: 443
      username: root
      password: "*****"
      allowInsecure: true
    sshConnection:
      host: some local ip
      port: 22
      username: root
      # use either password or key
      # password: ""
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        "*****"
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less

      datasetParentName: LosAngeles/k3s
      detachedSnapshotsDatasetParentName: LosAngeles/k3ssnap

      datasetProperties:
         "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

      # "" (inherit), lz4, gzip-9, etc
      zvolCompression: (inherit)
      # "" (inherit), on, off, verify
      zvolDedup: (inherit)
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize: 16K
    iscsi:
      targetPortal: "some local ip:3262"
      targetPortals: []
      # leave empty to omit usage of -I with iscsiadm
      interface:
      namePrefix: csi-
      nameSuffix: "-clustera"
      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 2
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: CHAP
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup: 2
          

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
```

There is also another helm deployment on the same cluster for SSD Access that is basically identically configured

On a second K8sCluster (running inside the same physical machine) I used the exact same config as above in order to simulate the migration of storage. => This cluster CAN create delete and snapshot PVCs as expected but when trying to create a PVC from the Snapshots (which are now written to the same location on TrueNAS as by the fist cluster) I do get a PVC from a Snapshot of a PVC from the first cluster but it is empty. (as you suggested it would due to the lack/ of metadata existing on k8s side)

So yeah, I really like @Stormymusings explanation of the problem and would love to see such a `discover-disks-on-backend-and-sync-metadata-to-k8s-solution`.

**Comment by gregod-com** [comment]
Ok, so today I tested some more and I looked at your code and everything seems to be in place. I must miss something. So here are my steps:
ClusterA: (v1.18.9+k3s1)
1) has a PVC at TrueNAS `LosAngeles/k3s/pvc-2681c084-5b56-4ea5-b344-c551c5c3af12` (~250MB)
1) I just created a snapshot from pvc 
    ```yaml
    apiVersion: snapshot.storage.k8s.io/v1beta1
    kind: VolumeSnapshot
    metadata:
      name: grafana-snapshot-2020-02-21-14-05
      namespace: loki
    spec:
      volumeSnapshotClassName: gregod-losangeles-k3ssnap-hdd
      source:
        persistentVolumeClaimName: grafana
    ```
1) this created a k8s snapshot including a k8s snapshotcontent like this:
    `NAME                                READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS                   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
grafana-snapshot-2020-02-21-14-05   true         grafana                             0             gregod-losangeles-k3ssnap-hdd   snapcontent-956cfa1a-897f-4f29-9631-4bbf3e80c0dd   3m32s          3m26s`
    `NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                 VOLUMESNAPSHOTCLASS             VOLUMESNAPSHOT                      AGE
snapcontent-956cfa1a-897f-4f29-9631-4bbf3e80c0dd   true         0             Delete           com.gregod-csi.iscsi   gregod-losangeles-k3ssnap-hdd   grafana-snapshot-2020-02-21-14-05   4m30s`
1) a volume on TrueNAS is also created at `LosAngeles/k3ssnap/pvc-2681c084-5b56-4ea5-b344-c551c5c3af12/snapshot-956cfa1a-897f-4f29-9631-4bbf3e80c0dd` (with pvc-2681c084-5b56-4ea5-b344-c551c5c3af12 being of type FILESYSTEM and snapshot-956cfa1a-897f-4f29-9631-4bbf3e80c0dd of type VOLUME
    => perfect
1) I can create a new PVC from this snapshot easily by applying this yaml:
    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: from-grafana-snapshot
      namespace: loki
    spec:
      storageClassName: freenas-iscsi-csi-com-gregod
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      dataSource:
        apiGroup: snapshot.storage.k8s.io
        kind: VolumeSnapshot
        name: grafana-snapshot-2020-02-21-14-05

    ```  
1) pvc can be mounted and holds all data 
    ```bash
    root@tester-7559b7fc4b-nn2zg:/# du -sh /fresh/
    246M    /fresh/
    ```

So far so good!

Moving to ClusterB (v1.18.10+rke2r1)
1) create new PVC works as expected (creates volume at `LosAngeles/k3s/pvc-....` and is mountable)
1) create snapshot of this PVC works as expected
    1) creates volume at `LosAngeles/k3ssnap/pvc-..../snapshot-.....`
    1) creates k8s volumesnapshot object
    1) creates k8s volumesnapshotcontent object
1) create PVC from new Snapshot works as expected
    1) creates volume at `LosAngeles/k3s/pvc-....`
    1) pvc can be mounted
    1) data is present
=> perfect

Since all that works like butter and the `datasetParentName` and `detachedSnapshotsDatasetParentName` are set to the same location on both deployments I would assume it should be possible to create a `volumesnapshot` and `volumesnapshotcontent` object manually to get a snapshot from ClusterA to CLusterB. This is what I tried so far:

All is applied to ClusterB:
```yaml
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapcontent-956cfa1a-897f-4f29-9631-4bbf3e80c0dd
spec:
  deletionPolicy: Delete
  driver: com.gregod-csi.iscsi
  source:
    snapshotHandle: snapshot-956cfa1a-897f-4f29-9631-4bbf3e80c0dd
  volumeSnapshotClassName: gregod-losangeles-k3ssnap-hdd
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snap-from-clustera-1
    namespace: default
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snap-from-clustera-1
spec:
  volumeSnapshotClassName: gregod-losangeles-k3ssnap-hdd
  source:
    volumeSnapshotContentName: snapcontent-956cfa1a-897f-4f29-9631-4bbf3e80c0dd
```
=> this renders the k8s volumesnapshot object READYTOUSE=false and throws the error
`error occurred failed to list snapshot for content snapcontent-956cfa1a-897f-4f29-9631-4bbf3e80c0dd: "rpc error: code = Internal desc = Cannot read property 'entries' of undefined"` at external-snapshotter
=> As a result I tried to add the pvc-name to the snapshotHandle like this:
```yaml
...
  source:
    snapshotHandle: pvc-2681c084-5b56-4ea5-b344-c551c5c3af12@snapshot-956cfa1a-897f-4f29-9631-4bbf3e80c0dd
...
```

When applying this combination the snapshotter says
`error occurred failed to list snapshot for content snapcontent-956cfa1a-897f-4f29-9631-4bbf3e80c0dd: "rpc error: code = NotFound desc = snapshot_id pvc-2681c084-5b56-4ea5-b344-c551c5c3af12@snapshot-956cfa1a-897f-4f29-9631-4bbf3e80c0dd does not exist"`
which sound to me like he is trying to search for a ZFS Snapshot and not the send/receive snapshot I use.

So that's as far as I got by now. I think I will try to go back to the ZFS `inline` snapshots and try to restore from there...

It really seems to me like there is just a small misconfiguration on my side.
