### ISSUE TITLE
Helm Upgrade is failing

### ISSUE THREAD

**Issue by spointecker** [democratic-csi/democratic-csi#209]
Hi there,

our democratic-csi is in crash loop so we had/need to make a helm upgrade to redeploy it.

```
democratic-csi              zfs-iscsi-ssd-democratic-csi-controller-798dfc5b95-4qwzd   3/4     CrashLoopBackOff   465        129d
democratic-csi              zfs-iscsi-ssd-democratic-csi-node-8cm8n                    0/3     Evicted            0          91s
democratic-csi              zfs-iscsi-ssd-democratic-csi-node-b45jr                    2/3     CrashLoopBackOff   377        287d
democratic-csi              zfs-iscsi-ssd-democratic-csi-node-mqkbt                    2/3     CrashLoopBackOff   389        357d
```

Unfortunately it is not working with our current yaml configuration, which is pretty old so my suggestion is that the config isn't valid anymore, but maybe you have a better guess with this error message:

`helm upgrade --values values.yaml --namespace democratic-csi zfs-iscsi-ssd democratic-csi/democratic-csi`

`Error: UPGRADE FAILED: cannot patch "zfs-iscsi-ssd-democratic-csi-node" with kind DaemonSet: DaemonSet.apps "zfs-iscsi-ssd-democratic-csi-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"node-linux", "app.kubernetes.io/csi-role":"node", "app.kubernetes.io/instance":"zfs-iscsi-ssd", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "zfs-iscsi-ssd-democratic-csi-controller" with kind Deployment: Deployment.apps "zfs-iscsi-ssd-democratic-csi-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"controller-linux", "app.kubernetes.io/csi-role":"controller", "app.kubernetes.io/instance":"zfs-iscsi-ssd", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`

values.yaml:

```
csiDriver:
  # should be globally unique for a given cluster
  name: dev.org-csi-ssd.iscsi

driver:
  existingConfigSecret: "manual-democratic-csi-driver-config"
  config:
    driver: freenas-iscsi

node:
  kubeletHostPath: /opt/rke/var/lib/kubelet

storageClasses:
- name: iscsi-ssd
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    detachedVolumesFromSnapshots: "true"
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    detachedVolumesFromVolumes: "true"

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-expand-secret:
    controller-publish-secret:
    node-publish-secret:
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: k8suser
      node-db.node.session.auth.password: $OURPASSWORD$

- name: freenas-iscsi-csi-dev-org-ssd
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-expand-secret:
    controller-publish-secret:
    node-publish-secret:
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: k8suser
      node-db.node.session.auth.password: $OURPASSWORD$

volumeSnapshotClasses:
  - name: dev-org-ssd-iscsi-snapshot
    parameters:
      detachedSnapshots: "false"
    secrets:
      snapshotter-secret:

  - name: detached-snapshot
    parameters:
      detachedSnapshots: "true"
    secrets:
      snapshotter-secret:

  - name: zfs-snapshot
    parameters:
      detachedSnapshots: "false"
    secrets:
      snapshotter-secret:

```

Current installation:
`kubectl describe deployment/zfs-iscsi-ssd-democratic-csi-controller -n democratic-csi`

```
Name:                   zfs-iscsi-ssd-democratic-csi-controller
Namespace:              democratic-csi
CreationTimestamp:      Thu, 01 Oct 2020 13:30:39 +0000
Labels:                 app.kubernetes.io/csi-role=controller
                        app.kubernetes.io/instance=zfs-iscsi-ssd
                        app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=democratic-csi
                        helm.sh/chart=democratic-csi-0.7.0
Annotations:            deployment.kubernetes.io/revision: 13
                        meta.helm.sh/release-name: zfs-iscsi-ssd
                        meta.helm.sh/release-namespace: democratic-csi
Selector:               app.kubernetes.io/instance=zfs-iscsi-ssd,app.kubernetes.io/name=democratic-csi
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/csi-role=controller
                    app.kubernetes.io/instance=zfs-iscsi-ssd
                    app.kubernetes.io/name=democratic-csi
  Annotations:      fluentbit.io/exclude: true
  Service Account:  zfs-iscsi-ssd-democratic-csi-controller-sa
  Containers:
   external-provisioner:
    Image:      k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=democratic-csi
      --timeout=90s
      --worker-threads=10
      --extra-create-metadata
      --csi-address=/csi-data/csi.sock
    Environment:  <none>
    Mounts:
      /csi-data from socket-dir (rw)
   external-resizer:
    Image:      k8s.gcr.io/sig-storage/csi-resizer:v1.1.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=democratic-csi
      --timeout=90s
      --workers=10
      --csi-address=/csi-data/csi.sock
    Environment:  <none>
    Mounts:
      /csi-data from socket-dir (rw)
   external-snapshotter:
    Image:      k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3
    Port:       <none>
    Host Port:  <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=democratic-csi
      --timeout=90s
      --worker-threads=10
      --csi-address=/csi-data/csi.sock
    Environment:  <none>
    Mounts:
      /csi-data from socket-dir (rw)
   csi-driver:
    Image:      democraticcsi/democratic-csi:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      --csi-version=1.2.0
      --csi-name=dev.org-csi-ssd.iscsi
      --driver-config-file=/config/driver-config-file.yaml
      --log-level=info
      --csi-mode=controller
      --server-socket=/csi-data/csi.sock
    Liveness:     exec [bin/liveness-probe --csi-version=1.2.0 --csi-address=/csi-data/csi.sock] delay=10s timeout=3s period=60s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /config from config (rw)
      /csi-data from socket-dir (rw)
  Volumes:
   socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  manual-democratic-csi-driver-config
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      False   MinimumReplicasUnavailable
OldReplicaSets:  <none>
NewReplicaSet:   zfs-iscsi-ssd-democratic-csi-controller-798dfc5b95 (1/1 replicas created)
Events:          <none>
```
