### ISSUE TITLE
How to create multiple storageClasses for diffirent nfs-servers

### ISSUE THREAD

**Issue by BattlefieldTsk** [democratic-csi/democratic-csi#221]
Hello!
Tell me please. How to create multiple storageClasses and driver for diffirent nfs-servers?

**Comment by BattlefieldTsk** [comment]
System is Linux nfs-server. Driver is nfs-client.
My values.yaml file:
```yaml
---
csiDriver:
  name: "org.democratic-csi.nfs-client"
storageClasses:
- name: democratic-nfs-client
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
volumeSnapshotClasses: []
driver:
  config:
    driver: nfs-client
    instance_id:
    nfs:
      shareHost: "192.168.132.12"
      shareBasePath: "/opt/nfs-share"
      controllerBasePath: "/nfs-storage"
      dirPermissionsMode: "0700"
      dirPermissionsUser: 65534
      dirPermissionsGroup: 65534
controller:
  enabled: true
  externalResizer:
    enabled: false
  strategy: deployment
  hostNetwork: true
  hostIPC: true
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p /nfs-storage; mount 192.168.132.12:/opt/nfs-share /nfs-storage"]
      preStop:
        exec:
          command: ["/bin/sh","-c","umount /nfs-storage"]
node:
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
```
To install democratic-csi, command is used:
```sh
helm upgrade --install \
    democratic-nfs-client democratic-csi/democratic-csi \
    --create-namespace --namespace democratic-csi \
    --version 0.11.2 \
    --values values.yaml
```
Planned deployment pattern:
![Screenshot_20220728_094323](https://user-images.githubusercontent.com/8220353/181408866-36ffc9a2-b5ef-4a2d-bc36-c348e8d35141.png)

I can add multiple storageClasses at once, but I don't understand how to add a driver and controller for them.
```yaml
---
csiDriver:
  name: "org.democratic-csi.nfs-client"
storageClasses:
- name: democratic-nfs-client
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
- name: nfs-client-40.21
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
- name: nfs-client-21.40
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
.  .  .
```

**Comment by travisghansen** [comment]
I see, thanks for the helpful graphic and details!

OK, so for your scenario you actually want 3 separate deployments (releases) with helm, each with 1 storage class.

- be sure `csiDriver.name` is unique
- be sure the `storageClasses[0].name` names are unique
- be sure only 1 of the storage classes is flagged as default

The above 3 points are scoped within a single cluster. For example, if you add a 2nd cluster the `csiDriver.name` values from cluster 1 have no relevance to cluster 2.

As a tip if you ever think that multiple *clusters* will feed into those same storage servers I would 'namespace' your paths on the server directory structure as well (ie: replace `shareBasePath: "/opt/nfs-share"` with `shareBasePath: "/opt/<cluster id here>/nfs-share"` along with respective updates to the pre/post mount/unmount commands).

**Comment by travisghansen** [comment]
Of course `shareBasePath: "/opt/nfs-share/<cluster id here>"` would work as well...whatever makes most sense in your scenario...you get the idea :D

**Comment by BattlefieldTsk** [comment]
Thanks for quick and detailed answer!

Solution for my question is:

File `values-132-12.yaml`:
```yaml
---
csiDriver:
  name: "org.democratic-csi.nfs-client"
storageClasses:
- name: democratic-nfs-client
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
volumeSnapshotClasses: []
driver:
  config:
    driver: nfs-client
    instance_id:
    nfs:
      shareHost: "192.168.132.12"
      shareBasePath: "/opt/nfs-share"
      controllerBasePath: "/nfs-storage"
      dirPermissionsMode: "0700"
      dirPermissionsUser: 65534
      dirPermissionsGroup: 65534
controller:
  enabled: true
  externalResizer:
    enabled: false
  strategy: deployment
  hostNetwork: true
  hostIPC: true
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p /nfs-storage; mount 192.168.132.12:/opt/nfs-share /nfs-storage"]
      preStop:
        exec:
          command: ["/bin/sh","-c","umount /nfs-storage"]
node:
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
```

File `values-40-21.yaml`:
```yaml
---
csiDriver:
  name: "org.democratic-csi.nfs-40-21"
storageClasses:
- name: democratic-nfs-40-21
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
volumeSnapshotClasses: []
driver:
  config:
    driver: nfs-client
    instance_id:
    nfs:
      shareHost: "172.17.40.21"
      shareBasePath: "/opt/nfs-share"
      controllerBasePath: "/nfs-storage"
      dirPermissionsMode: "0700"
      dirPermissionsUser: 65534
      dirPermissionsGroup: 65534
controller:
  enabled: true
  externalResizer:
    enabled: false
  strategy: deployment
  hostNetwork: true
  hostIPC: true
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p /nfs-storage; mount 172.17.40.21:/opt/nfs-share /nfs-storage"]
      preStop:
        exec:
          command: ["/bin/sh","-c","umount /nfs-storage"]
node:
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
```

File `values-21-40.yaml`:
```yaml
---
csiDriver:
  name: "org.democratic-csi.nfs-21-40"
storageClasses:
- name: democratic-nfs-21-40
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
volumeSnapshotClasses: []
driver:
  config:
    driver: nfs-client
    instance_id:
    nfs:
      shareHost: "172.17.21.40"
      shareBasePath: "/opt/nfs-share"
      controllerBasePath: "/nfs-storage"
      dirPermissionsMode: "0700"
      dirPermissionsUser: 65534
      dirPermissionsGroup: 65534
controller:
  enabled: true
  externalResizer:
    enabled: false
  strategy: deployment
  hostNetwork: true
  hostIPC: true
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p /nfs-storage; mount 172.17.21.40:/opt/nfs-share /nfs-storage"]
      preStop:
        exec:
          command: ["/bin/sh","-c","umount /nfs-storage"]
node:
  driver:
    image: docker.io/democraticcsi/democratic-csi:v1.6.1
```

And deploy all releases for all servers.
Default storageClasses:
```sh
helm upgrade --install \
    democratic-nfs-client democratic-csi/democratic-csi \
    --create-namespace --namespace democratic-csi \
    --version 0.11.2 \
    --values values-132-12.yaml
```

Custom storageClasses for server 172.17.21.40:
```sh
helm upgrade --install \
    democratic-nfs-21-40 democratic-csi/democratic-csi \
    --create-namespace --namespace democratic-csi \
    --version 0.11.2 \
    --values values-21-40.yaml
```

Custom storageClasses for server 172.17.40.21:
```sh
helm upgrade --install \
    democratic-nfs-40-21 democratic-csi/democratic-csi \
    --create-namespace --namespace democratic-csi \
    --version 0.11.2 \
    --values values-40-21.yaml
```
