### ISSUE TITLE
401: Unauthorized when trying to claim

### ISSUE THREAD

**Issue by viloskovic** [democratic-csi/democratic-csi#23]
Goodevening @travisghansen 

I'm having some trouble with setting up everything. 
It feels like I'm in the last step of getting it to work..

When I try to create a pvc I get the following:

```sh
Name:          freenas-test-pvc
Namespace:     default
StorageClass:  freenas-nfs-csi
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: com.experus.nas.nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age                  From                                                                                                         Message
  ----     ------                ----                 ----                                                                                                         -------
  Normal   Provisioning          67s (x8 over 3m18s)  com.experus.nas.nfs_zfs-nfs-democratic-csi-controller-7d7476469c-z6668_7d1e5798-8156-46ac-94e3-41e93ba2e209  External provisioner is provisioning volume for claim "default/freenas-test-pvc"
  Warning  ProvisioningFailed    65s (x8 over 3m15s)  com.experus.nas.nfs_zfs-nfs-democratic-csi-controller-7d7476469c-z6668_7d1e5798-8156-46ac-94e3-41e93ba2e209  failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Unknown desc = received error creating nfs share - code: 401 body: "401: Unauthorized"
  Normal   ExternalProvisioning  9s (x14 over 3m18s)  persistentvolume-controller                                                                                  waiting for a volume to be created, either by external provisioner "com.experus.nas.nfs" or manually created by system administrator
```

But he actually manages to create everything:
![image](https://user-images.githubusercontent.com/12528648/99451361-62e90f80-2922-11eb-8de5-8ae09907f5fb.png)

First I only got 401 without message.. So I tried with apiVersion: 2 and I got "401: Unauthorized".
The k8s-tu user has Auxiliary group `wheel`. And I also granted him some permissions with the following command:
```sh
zfs allow csi create,destroy,mount,refquota,snapshot,userprop,send,receive ExperusNAS/k8s
```

This is my values.yaml file:

```yaml
csiDriver:
  name: "com.experus.nas.nfs"
storageClasses:
  - name: freenas-nfs-csi
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: nfs

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"

    mountOptions:
      - noatime
      - nfsvers=3
volumeSnapshotClasses: []
driver:
  config:
    driver: freenas-nfs
    instance_id: ExperusNAS
    httpConnection:
      apiVersion: 2
      protocol: http
      host: x.x.x.A
      port: 80
      username: k8s-tu
      password: "[REDACTED]"
      allowInsecure: true
    sshConnection:
      host: x.x.x.B
      port: 22
      username: k8s-tu
      password: "[REDACTED]"
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      #cli:
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      #datasetProperties:
      #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      datasetParentName: ExperusNAS/k8s/a/vols
      detachedSnapshotsDatasetParentName: ExperusNAS/k8s/a/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: root
      datasetPermissionsGroup: wheel
      #datasetPermissionsAcls:
      #- "-m everyone@:full_set:allow"
      #- "-m u:kube:full_set:allow"
    nfs:
      shareHost: x.x.x.B
      shareAlldirs: true
      shareAllowedHosts: [ ]
      shareAllowedNetworks: [ ]
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```

FreeNAS Version: FreeNAS-11.3-U5

Any idea what the actual problem is? Can you point me into a direction?

Best regards
Ruben

**Comment by viloskovic** [comment]
This is my test-claim.yaml:

```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freenas-test-pvc
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```
