### ISSUE TITLE
Unauthorized Error Retrieving System Version

### ISSUE THREAD

**Issue by Wizofgoz** [democratic-csi/democratic-csi#233]
I followed this article for setup https://www.lisenet.com/2021/moving-to-truenas-and-democratic-csi-for-kubernetes-persistent-storage/ and am seeing an error in the logs for the `csi-driver` container.

```
{"host":"zfs-nfs-democratic-csi-controller-85849c5f66-sz5tk","level":"debug","message":"FREENAS HTTP REQUEST: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":60000,\"method\":\"GET\",\"url\":\"http://192.168.0.103/api/v2.0/system/version/\"}","service":"democratic-csi","timestamp":"2022-08-31T16:53:18.796Z"}
{"host":"zfs-nfs-democratic-csi-controller-85849c5f66-sz5tk","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2022-08-31T16:53:18.796Z"}
{"host":"zfs-nfs-democratic-csi-controller-85849c5f66-sz5tk","level":"debug","message":"FREENAS HTTP STATUS: 401","service":"democratic-csi","timestamp":"2022-08-31T16:53:18.796Z"}
{"host":"zfs-nfs-democratic-csi-controller-85849c5f66-sz5tk","level":"debug","message":"FREENAS HTTP HEADERS: {\"server\":\"nginx\",\"date\":\"Wed, 31 Aug 2022 16:53:18 GMT\",\"content-type\":\"text/plain; charset=utf-8\",\"content-length\":\"17\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=63072000; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2022-08-31T16:53:18.796Z"}
{"host":"zfs-nfs-democratic-csi-controller-85849c5f66-sz5tk","level":"debug","message":"FREENAS HTTP BODY: \"401: Unauthorized\"","service":"democratic-csi","timestamp":"2022-08-31T16:53:18.797Z"}
```

When I run the same request in Postman, it returns without an error
![Screen Shot 2022-08-31 at 2 36 01 PM](https://user-images.githubusercontent.com/10892542/187789490-9812afd4-446b-4f4d-a766-83659e9fad25.png)

Any ideas what the problem could be?

driver config
```yaml
driver: freenas-nfs
instance_id:
httpConnection:
  protocol: http
  host: 192.168.0.103
  port: 80
  # use only 1 of apiKey or username/password
  # if both are present, apiKey is preferred
  # apiKey is only available starting in TrueNAS-12
  apiKey: [redacted]
  username: root
  password:
  allowInsecure: true
  # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
  # leave unset for auto-detection
  apiVersion: 2
sshConnection:
  host: 192.168.0.103
  port: 22
  username: root
  # use either password or key
  #password: ""
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    [redacted]
    -----END RSA PRIVATE KEY-----
zfs:
  # can be used to override defaults if necessary
  # the example below is useful for TrueNAS 12
  cli:
    sudoEnabled: true
  #
  #  leave paths unset for auto-detection
  #  paths:
  #    zfs: /usr/local/sbin/zfs
  #    zpool: /usr/local/sbin/zpool
  #    sudo: /usr/local/bin/sudo
  #    chroot: /usr/sbin/chroot
  
  # can be used to set arbitrary values on the dataset/zvol
  # can use handlebars templates with the parameters from the storage class/CO
  #datasetProperties:
  #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  #  "org.freenas:test": "{{ parameters.foo }}"
  #  "org.freenas:test2": "some value"

  datasetParentName: Main/Shared/k8s/vols
  # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
  # they may be siblings, but neither should be nested in the other
  detachedSnapshotsDatasetParentName: Main/Shared/k8s/snaps
  datasetEnableQuotas: true
  datasetEnableReservation: false
  datasetPermissionsMode: "0777"
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0
  #datasetPermissionsAcls:
  #- "-m everyone@:full_set:allow"
  #- "-m u:kube:full_set:allow"

nfs:
  #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  shareHost: 192.168.0.103
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks: []
  shareMaprootUser: root
  shareMaprootGroup: wheel
  shareMapallUser: ""
  shareMapallGroup: ""
```

Storage Class
```yaml
name: freenas-nfs-csi
defaultClass: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  fsType: nfs

mountOptions:
  - noatime
  - nconnect=8
  - nfsvers=4.1
secrets:
  provisioner-secret:
  controller-publish-secret:
  node-stage-secret:
  node-publish-secret:
  controller-expand-secret:
```

Environment
microk8s running v1.24.3
TrueNAS-12.0-U8.1
