### ISSUE TITLE
Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by Wizofgoz** [democratic-csi/democratic-csi#235]
When the controller tries to make an SSH connection, it returns with an error `Handshake failed: no matching key exchange algorithm`. Here are some relevant logs:

```
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"info","message":"initializing csi driver: freenas-nfs","service":"democratic-csi","timestamp":"2022-09-27T00:14:24.318Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"debug","message":"setting default identity service caps","service":"democratic-csi","timestamp":"2022-09-27T00:14:25.337Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"debug","message":"setting default identity volume_expansion caps","service":"democratic-csi","timestamp":"2022-09-27T00:14:25.338Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"debug","message":"setting default controller caps","service":"democratic-csi","timestamp":"2022-09-27T00:14:25.338Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"debug","message":"setting default node caps","service":"democratic-csi","timestamp":"2022-09-27T00:14:25.348Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"info","message":"starting csi server - node version: v16.16.0, package version: 1.7.6, config file: /config/..2022_09_27_00_06_31.1322805016/driver-config-file.yaml, csi-name: org.democratic-csi.nfs, csi-driver: freenas-nfs, csi-mode: controller, csi-version: 1.5.0, address: , socket: unix:///csi-data/csi.sock.internal","service":"democratic-csi","timestamp":"2022-09-27T00:14:25.350Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.6.8\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-09-27T00:15:32.566Z"}
{"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"debug","message":"performing exec sanity check..","service":"democratic-csi","timestamp":"2022-09-27T00:15:32.570Z"}
{"date":"Tue Sep 27 2022 00:15:32 GMT+0000 (Coordinated Universal Time)","error":{"fatal":true,"level":"handshake"},"exception":true,"host":"zfs-nfs-democratic-csi-controller-7cc544dd84-4tv26","level":"error","message":"uncaughtException: Handshake failed: no matching key exchange algorithm\nError: Handshake failed: no matching key exchange algorithm\n    at makeError (/home/csi/app/node_modules/ssh2/lib/protocol/utils.js:142:15)\n    at doFatalError (/home/csi/app/node_modules/ssh2/lib/protocol/utils.js:184:13)\n    at handleKexInit (/home/csi/app/node_modules/ssh2/lib/protocol/kex.js:239:12)\n    at Protocol.onKEXPayload (/home/csi/app/node_modules/ssh2/lib/protocol/kex.js:1755:14)\n    at NullDecipher.decrypt (/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js:612:26)\n    at Protocol.parsePacket [as _parse] (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)\n    at Protocol.parse (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/home/csi/app/node_modules/ssh2/lib/client.js:713:21)\n    at Socket.emit (node:events:527:28)\n    at addChunk (node:internal/streams/readable:315:12)","os":{"loadavg":[1.66,2.08,2.03],"uptime":289631.38},"process":{"argv":["/usr/local/bin/node","/home/csi/app/bin/democratic-csi","--csi-version=1.5.0","--csi-name=org.democratic-csi.nfs","--driver-config-file=/config/driver-config-file.yaml","--log-level=debug","--csi-mode=controller","--server-socket=/csi-data/csi.sock.internal"],"cwd":"/home/csi/app","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"arrayBuffers":146584,"external":17991234,"heapTotal":36696064,"heapUsed":33981472,"rss":87715840},"pid":1,"uid":0,"version":"v16.16.0"},"service":"democratic-csi","stack":"Error: Handshake failed: no matching key exchange algorithm\n    at makeError (/home/csi/app/node_modules/ssh2/lib/protocol/utils.js:142:15)\n    at doFatalError (/home/csi/app/node_modules/ssh2/lib/protocol/utils.js:184:13)\n    at handleKexInit (/home/csi/app/node_modules/ssh2/lib/protocol/kex.js:239:12)\n    at Protocol.onKEXPayload (/home/csi/app/node_modules/ssh2/lib/protocol/kex.js:1755:14)\n    at NullDecipher.decrypt (/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js:612:26)\n    at Protocol.parsePacket [as _parse] (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)\n    at Protocol.parse (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/home/csi/app/node_modules/ssh2/lib/client.js:713:21)\n    at Socket.emit (node:events:527:28)\n    at addChunk (node:internal/streams/readable:315:12)","timestamp":"2022-09-27T00:15:32.697Z","trace":[{"column":15,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/utils.js","function":"makeError","line":142,"method":null,"native":false},{"column":13,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/utils.js","function":"doFatalError","line":184,"method":null,"native":false},{"column":12,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/kex.js","function":"handleKexInit","line":239,"method":null,"native":false},{"column":14,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/kex.js","function":"Protocol.onKEXPayload","line":1755,"method":"onKEXPayload","native":false},{"column":26,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js","function":"NullDecipher.decrypt","line":612,"method":"decrypt","native":false},{"column":25,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.parsePacket [as _parse]","line":1994,"method":"parsePacket [as _parse]","native":false},{"column":16,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.parse","line":293,"method":"parse","native":false},{"column":21,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":null,"line":713,"method":null,"native":false},{"column":28,"file":"node:events","function":"Socket.emit","line":527,"method":"emit","native":false},{"column":12,"file":"node:internal/streams/readable","function":"addChunk","line":315,"method":null,"native":false}]}
running server shutdown, exit code: Error: Handshake failed: no matching key exchange algorithm
```

CSI Driver Config:
```yaml
driver: freenas-nfs
instance_id:
httpConnection:
  protocol: https
  host: 192.168.0.100
  port: 443
  # use only 1 of apiKey or username/password
  # if both are present, apiKey is preferred
  # apiKey is only available starting in TrueNAS-12
  apiKey: [redacted]
  username: root
  password:
  allowInsecure: true
  # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
  # leave unset for auto-detection
  apiVersion: 2
sshConnection:
  host: 192.168.0.100
  port: 22
  username: root
  # use either password or key
  #password: ""
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    [redacted]
    -----END RSA PRIVATE KEY-----
zfs:
  # can be used to override defaults if necessary
  # the example below is useful for TrueNAS 12
  #cli:
  #  sudoEnabled: true
  #
  #  leave paths unset for auto-detection
  #  paths:
  #    zfs: /usr/local/sbin/zfs
  #    zpool: /usr/local/sbin/zpool
  #    sudo: /usr/local/bin/sudo
  #    chroot: /usr/sbin/chroot
  
  # can be used to set arbitrary values on the dataset/zvol
  # can use handlebars templates with the parameters from the storage class/CO
  #datasetProperties:
  #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  #  "org.freenas:test": "{{ parameters.foo }}"
  #  "org.freenas:test2": "some value"

  datasetParentName: Main/Shared/k8s/vols
  # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
  # they may be siblings, but neither should be nested in the other
  detachedSnapshotsDatasetParentName: Main/Shared/k8s/snaps
  datasetEnableQuotas: true
  datasetEnableReservation: false
  datasetPermissionsMode: "0777"
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0
  #datasetPermissionsAcls:
  #- "-m everyone@:full_set:allow"
  #- "-m u:kube:full_set:allow"

nfs:
  shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  shareHost: 192.168.0.100
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks: []
  shareMaprootUser: root
  shareMaprootGroup: wheel
  shareMapallUser: ""
  shareMapallGroup: ""
```

Environment
microk8s running v1.25.0
TrueNAS-12.0-U8.1

**Comment by travisghansen** [comment]
It’s likely this: https://www.truenas.com/community/threads/ssh-access-ssh-rsa-not-in-pubkeyacceptedalgorithms.101715/


Although I didn’t think that was an issue until 13..

**Comment by Wizofgoz** [comment]
@travisghansen I just tried adding `PubkeyAcceptedAlgorithms +ssh-rsa` to the auxiliary parameters and the SSH service didn't want to start anymore.

Also, to add to the confusion, I'm able to SSH in from another machine using the same private key and the attempts that the CSI driver makes don't seem to be showing up in `/var/log/auth.log` but the successful connection from another machine does.

**Comment by travisghansen** [comment]
Can you exec into the container and check the actual contents of the file? Sometimes things get 'lost in translation' depending on how the values are set etc and the formatting of the key can be illegitimate. Also maybe make sure from within the container you can ping/reach the nas.

**Comment by Wizofgoz** [comment]
Weird, it looks like the `/config` dir doesn't exist.

From kubectl describe:
```
csi-driver:
    Container ID:  containerd://3dd9c9645d1680a04e7bf91ec28a36be25593eabaa5b875c172b5f548e165999
    Image:         docker.io/democraticcsi/democratic-csi:latest
    Image ID:      docker.io/democraticcsi/democratic-csi@sha256:d6e3aac0841a98faa6bf0cefed8bc3c48644dae43ebefdd52a5d184c9f4d6d25
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-version=1.5.0
      --csi-name=org.democratic-csi.nfs
      --driver-config-file=/config/driver-config-file.yaml
      --log-level=debug
      --csi-mode=controller
      --server-socket=/csi-data/csi.sock.internal
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 26 Sep 2022 19:15:36 -0700
      Finished:     Mon, 26 Sep 2022 19:16:28 -0700
    Ready:          False
    Restart Count:  16
    Liveness:       exec [bin/liveness-probe --csi-version=1.5.0 --csi-address=/csi-data/csi.sock.internal] delay=10s timeout=15s period=60s #success=1 #failure=3
    Environment:
      NODE_EXTRA_CA_CERTS:  /tmp/certs/extra-ca-certs.crt
    Mounts:
      /config from config (rw)
      /csi-data from socket-dir (rw)
      /tmp/certs from extra-ca-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ltwwt (ro)
```

ls /
```
bin       csi-data  dev       etc       home      lib       media     mnt       opt       proc      root      run       sbin      srv       sys       tmp       usr       var
```

I am able to ping the nas but if the config is missing the error probably makes sense. Any idea why it wouldn't be mounting?

**Comment by travisghansen** [comment]
Can you send over the values.yaml file for helm (obviously cleanse it)?

**Comment by Wizofgoz** [comment]
values.yaml
```yaml
# Default values for democratic-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

extraCaCerts: |-
  -----BEGIN CERTIFICATE-----
  [redacted]
  -----END CERTIFICATE-----
#extraCaCerts: |-
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----
#  -----BEGIN CERTIFICATE-----
#  ...
#  -----END CERTIFICATE-----

driver:
  # see the driver-config-secret.yaml for syntax
  # NOTE: if setting an existing secret you must still set `driver.config.driver`
  # to the corresponding value that you place in the secret as the value is used
  # by the chart for other purposes beyond secret creation
  existingConfigSecret:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: https
      host: 192.168.0.100
      port: 443
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      apiKey: [redacted]
      username: root
      password:
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    sshConnection:
      host: 192.168.0.100
      port: 22
      username: root
      # use either password or key
      #password: ""
      privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        [redacted]
        -----END RSA PRIVATE KEY-----
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      #cli:
      #  sudoEnabled: true
      #
      #  leave paths unset for auto-detection
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot
      
      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      datasetParentName: Main/Shared/k8s/vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      detachedSnapshotsDatasetParentName: Main/Shared/k8s/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
      #datasetPermissionsAcls:
      #- "-m everyone@:full_set:allow"
      #- "-m u:kube:full_set:allow"

    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: 192.168.0.100
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""

# https://kubernetes-csi.github.io/docs/csi-driver-object.html
csiDriver:
  # should be globally unique for a given cluster
  name: org.democratic-csi.nfs
  version: 1.5.0
  # create the kubernetes CSIDriver
  enabled: true
  attachRequired: false
  podInfoOnMount: true
  # https://kubernetes-csi.github.io/docs/support-fsgroup.html
  # k8s 1.19+ (ignored otherwise)
  # None|File|ReadWriteOnceWithFSType
  # fsGroupPolicy: ReadWriteOnceWithFSType
  
  # k8s 1.16+
  # volumeLifecycleModes: []
  
  # k8s 1.20+
  # tokenRequests: []

  # k8s 1.20+
  # requiresRepublish: false

  # k8s 1.19+
  # storageCapacity: false

controller:
  enabled: true
  rbac:
    enabled: true
    openshift:
      # set to true if running on openshift *and* you have need
      # ie: hostNetwork, hostIPC, etc are turned on
      privileged: false
  replicaCount: 1
  hostNetwork: false
  hostAliases: []
  hostIPC: false
  podAnnotations: {}
  podLabels: {}
  
  # deployment = deploy controller parts in a distinct deployment
  # node       = deploy controller as sidecars with node daemonset
  strategy: deployment

  # https://kubernetes-csi.github.io/docs/external-attacher.html
  externalAttacher:
    enabled: false
    image: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --csi-address={{ .csiSocketAddress }}
    # if you do not want to completely override the defaults use this
    extraArgs: []
    resources:

  # https://kubernetes-csi.github.io/docs/external-provisioner.html
  externalProvisioner:
    enabled: true
    image: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --extra-create-metadata
      - --csi-address={{ .csiSocketAddress }}
    # if you do not want to completely override the defaults use this
    extraArgs: []
    resources:

  # https://kubernetes-csi.github.io/docs/external-resizer.html
  externalResizer:
    enabled: true
    image: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --workers=10
      - --csi-address={{ .csiSocketAddress }}
    # if you do not want to completely override the defaults use this
    extraArgs: []
    resources:

  # https://kubernetes-csi.github.io/docs/external-snapshotter.html
  externalSnapshotter:
    enabled: true
    # 1.20+ should use v4.0.0+
    # READ *before* updating from beta https://github.com/kubernetes-csi/external-snapshotter#usage
    image: k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --csi-address={{ .csiSocketAddress }}
    # if you do not want to completely override the defaults use this
    extraArgs: []
    resources:

  # https://github.com/kubernetes-csi/external-health-monitor
  externalHealthMonitorController:
    enabled: false
    image: k8s.gcr.io/sig-storage/csi-external-health-monitor-controller:v0.6.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --csi-address={{ .csiSocketAddress }}
    #- --enable-node-watcher
    #- --list-volumes-interval
    # if you do not want to completely override the defaults use this
    extraArgs: []
    resources:

  # https://kubernetes-csi.github.io/docs/cluster-driver-registrar.html
  # not implemented, likely uncessary at this point
  clusterDriverRegistrar:
    enabled: false

  livenessProbe:
    enabled: true

  # democratic-csi controller
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:latest
    # imagePullPolicy: Always
    logLevel: debug
    lifecycle:
    #      postStart:
    #        exec:
    #          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
    #      preStop:
    #        exec:
    #          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]

    securityContext:
    #      allowPrivilegeEscalation: true
    #      capabilities:
    #        add:
    #        - SYS_ADMIN
    #      privileged: true

    resources:
    extraEnv: []
    extraVolumeMounts: []
  #    - name: foo
  #      mountPath: /foo

  extraVolumes: []
  #  - name: foo
  #    hostPath:
  #      path: /dev
  #      type: Directory

  nodeSelector: {}

  tolerations: []

  affinity: {}

node:
  # windows support
  windows:
    enabled: false
  rbac:
    enabled: true
    openshift:
      # set to true if running on openshift
      privileged: false
  enabled: true
  hostNetwork: true
  hostAliases: []
  hostIPC: true
  hostPID: false
  kubeletHostPath: /var/snap/microk8s/common/var/lib/kubelet
  podAnnotations: {}
  podLabels: {}

  livenessProbe:
    enabled: true

  cleanup:
    image: docker.io/busybox:1.32.0

  # democratic-csi node
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:latest
    # imagePullPolicy: Always
    logLevel: debug
    # set path to null if your OS has no localtime file
    # RancherOS, openshift, etc 
    localtimeHostPath: /etc/localtime
    lifecycle:
    #      postStart:
    #        exec:
    #          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
    #      preStop:
    #        exec:
    #          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]

    resources:
    extraEnv: []
    extraVolumeMounts: []
    #    - name: foo
    #      mountPath: /foo

    iscsiDirHostPath: /etc/iscsi
    iscsiDirHostPathType: Directory
  # https://kubernetes-csi.github.io/docs/node-driver-registrar.html
  driverRegistrar:
    enabled: true
    image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.1
    args:
      - --v=5
      - --csi-address={{ .csiSocketAddress }}
      - --kubelet-registration-path={{ .Values.node.kubeletHostPath }}/plugins/{{ .Values.csiDriver.name }}/csi.sock
    # if you do not want to completely override the defaults use this
    extraArgs: []
    resources:

  extraVolumes: []
  #  - name: foo
  #    hostPath:
  #      path: /dev
  #      type: Directory

  nodeSelector: {}

  tolerations: []

  affinity: {}

# add note here about volume expansion requirements
storageClasses:
  - name: freenas-nfs-csi
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs

    mountOptions:
      - noatime
      - nconnect=8
      - nfsvers=4.1
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses: []
#- name:
#  annotations: {}
#  labels: {}
#  deletionPolicy: Delete | Retain
#  parameters:
#  secrets:
#    snapshotter-secret:

# this is a temporary measure until all the k8s components are proper
# grpc clients and send valid :authority headers
# required to remove the deprecated/custom `grpc-uds` package with
#`@grpc/grpc-js` and subsequently pave the way for updating `nodejs` to current
# versions
#
# https://github.com/democratic-csi/csi-grpc-proxy
csiProxy:
  enabled: true
  image: docker.io/democraticcsi/csi-grpc-proxy:v0.5.3
  resources:

# Configure a pod security policy to allow privileged pods
enablePSP: false


```

**Comment by travisghansen** [comment]
Are you sure you exec'd into the correct container of the pod? Something seems off here that doesn't add up. If the config was not there at all the app would crash entirely and would not even know to attempt an ssh connection anywhere.

**Comment by Wizofgoz** [comment]
Nope, sorry I was using Lens and it doesn't give a choice of container. After doing it via kubectl I was able to verify that the file is there at `/config/driver-config-file.yaml` but the contents look good to me:

```yaml
driver: freenas-nfs
httpConnection:
  allowInsecure: true
  apiKey: [redacted]
  apiVersion: 2
  host: 192.168.0.100
  password: null
  port: 443
  protocol: https
  username: root
instance_id: null
nfs:
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks: []
  shareCommentTemplate: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name]
    }}'
  shareHost: 192.168.0.100
  shareMapallGroup: ""
  shareMapallUser: ""
  shareMaprootGroup: wheel
  shareMaprootUser: root
sshConnection:
  host: 192.168.0.100
  port: 22
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    [redacted]
    -----END RSA PRIVATE KEY-----
  username: root
zfs:
  datasetEnableQuotas: true
  datasetEnableReservation: false
  datasetParentName: Main/Shared/k8s/vols
  datasetPermissionsGroup: 0
  datasetPermissionsMode: "0777"
  datasetPermissionsUser: 0
  datasetProperties:
    org.freenas:description: '{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{
      parameters.[csi.storage.k8s.io/pvc/name] }}'
  detachedSnapshotsDatasetParentName: Main/Shared/k8s/snaps
```
