### ISSUE TITLE
iSCSI volume not being mounted in proper namespace

### ISSUE THREAD

**Issue by Feliksas** [democratic-csi/democratic-csi#237]
Greetings,
I'm experiencing a weird issue with freenas-iscsi CSI driver - somehow the provisioned volume is not getting properly mounted to the target container, as if mountpoints reside in different namespaces.
I'm using the official Helm chart to deploy democratic-csi, the driver container is running in privileged mode.
Judging by the logs, the volume is being properly provisioned, attached to the node, formatted and mounted - at least from the csi-node point of view:
```
root@microk8s-02:/home/csi/app# mount | grep sdb
/dev/sdb on /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount type ext4 (rw,relatime,stripe=2048)
/dev/sdb on /var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount type ext4 (rw,relatime,stripe=2048)
root@microk8s-02:/home/csi/app#

root@microk8s-02:/home/csi/app# lsblk
NAME                      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0                       7:0    0  55.6M  1 loop 
loop1                       7:1    0    48M  1 loop /host/snap/snapd/16778
loop2                       7:2    0    62M  1 loop /host/snap/core20/1611
loop3                       7:3    0 118.4M  1 loop /host/snap/docker/1779
loop4                       7:4    0  79.9M  1 loop /host/snap/lxd/22923
loop5                       7:5    0 219.9M  1 loop 
loop6                       7:6    0  55.6M  1 loop /host/snap/core18/2566
loop7                       7:7    0    47M  1 loop 
loop8                       7:8    0   103M  1 loop /host/snap/lxd/23541
loop9                       7:9    0  55.6M  1 loop /host/snap/core18/2560
loop10                      7:10   0  63.2M  1 loop /host/snap/core20/1623
loop11                      7:11   0 220.1M  1 loop /host/snap/microk8s/3719
loop12                      7:12   0    48M  1 loop /host/snap/snapd/17029
loop13                      7:13   0 218.5M  1 loop /host/snap/microk8s/4023
sda                         8:0    0   120G  0 disk 
├─sda1                      8:1    0     1G  0 part /host/boot/efi
├─sda2                      8:2    0     2G  0 part /host/boot
└─sda3                      8:3    0 116.9G  0 part 
  └─ubuntu--vg-ubuntu--lv 253:0    0  58.5G  0 lvm  /host
sdb                         8:16   0    20G  0 disk /var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount
```
dmesg output:
```
[4755319.437443] scsi host3: iSCSI Initiator over TCP/IP
[4755319.461265] scsi 3:0:0:0: Direct-Access     TrueNAS  iSCSI Disk       0123 PQ: 0 ANSI: 7
[4755319.478295] scsi 3:0:0:0: alua: supports implicit TPGS
[4755319.478344] scsi 3:0:0:0: alua: device naa.6589cfc000000e8303c588f3c07f1305 port group 1 rel port 3
[4755319.480088] sd 3:0:0:0: Attached scsi generic sg1 type 0
[4755319.482553] sd 3:0:0:0: Power-on or device reset occurred
[4755319.493494] sd 3:0:0:0: alua: transition timeout set to 60 seconds
[4755319.493507] sd 3:0:0:0: alua: port group 01 state A non-preferred supports TolUSNA
[4755319.513537] sd 3:0:0:0: [sdb] 41943040 512-byte logical blocks: (21.5 GB/20.0 GiB)
[4755319.516809] sd 3:0:0:0: [sdb] Write Protect is off
[4755319.516817] sd 3:0:0:0: [sdb] Mode Sense: 7f 00 10 08
[4755319.525511] sd 3:0:0:0: [sdb] Write cache: enabled, read cache: enabled, supports DPO and FUA
[4755319.533036] sd 3:0:0:0: [sdb] Optimal transfer size 8388608 bytes
[4755319.652223] sd 3:0:0:0: [sdb] Attached SCSI disk
[4755319.667847] sd 3:0:0:0: alua: supports implicit TPGS
[4755319.667864] sd 3:0:0:0: alua: device naa.6589cfc000000e8303c588f3c07f1305 port group 1 rel port 3
[4755324.632190] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
```

However, the mount is not visible on the host itself:
```
root@microk8s-02:/# mount | grep sdb
root@microk8s-02:/# 

root@microk8s-02:/# findmnt /var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount
root@microk8s-02:/#
```

Looks like the csi-node is in a separate mount namespace (not sure, if this is causing the issue, but weird nevertheless - Kubernetes NFS mounts are always visible on the host as well)

And finally, the pod's mountpoint is simply a directory on the host filesystem (as if a hostPath has been used):
```
root@pvc-test:/# mount     
overlay on / type overlay (rw,relatime,lowerdir=/var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/4355/fs,upperdir=/var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/4407/fs,workdir=/var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/4407/work)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup type cgroup2 (ro,nosuid,nodev,noexec,relatime)
/dev/mapper/ubuntu--vg-ubuntu--lv on /pvc type ext4 (rw,relatime)
/dev/mapper/ubuntu--vg-ubuntu--lv on /etc/hosts type ext4 (rw,relatime)
/dev/mapper/ubuntu--vg-ubuntu--lv on /dev/termination-log type ext4 (rw,relatime)
/dev/mapper/ubuntu--vg-ubuntu--lv on /etc/hostname type ext4 (rw,relatime)
/dev/mapper/ubuntu--vg-ubuntu--lv on /etc/resolv.conf type ext4 (rw,relatime)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k,inode64)
tmpfs on /run/secrets/kubernetes.io/serviceaccount type tmpfs (ro,relatime,size=12147808k,inode64)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/fs type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime,inode64)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
tmpfs on /proc/keys type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
tmpfs on /proc/timer_list type tmpfs (rw,nosuid,size=65536k,mode=755,inode64)
tmpfs on /proc/scsi type tmpfs (ro,relatime,inode64)
tmpfs on /sys/firmware type tmpfs (ro,relatime,inode64)

root@pvc-test:/# findmnt /pvc
TARGET SOURCE                                                                                                                                                                                          FSTYPE OPTIONS
/pvc   /dev/mapper/ubuntu--vg-ubuntu--lv[/var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount] ext4   rw,relatime

root@pvc-test:/# df
Filesystem                        1K-blocks     Used Available Use% Mounted on
overlay                            60034956 37824888  19128036  67% /
tmpfs                                 65536        0     65536   0% /dev
/dev/mapper/ubuntu--vg-ubuntu--lv  60034956 37824888  19128036  67% /pvc
shm                                   65536        0     65536   0% /dev/shm
tmpfs                              12147808       12  12147796   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                               6125104        0   6125104   0% /proc/acpi
tmpfs                               6125104        0   6125104   0% /proc/scsi
tmpfs                               6125104        0   6125104   0% /sys/firmware
root@pvc-test:/# 
```

Relevant log output from csi-node:
```
grpc implementation: @grpc/grpc-js
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"initializing csi driver: freenas-iscsi","service":"democratic-csi","timestamp":"2022-10-12T14:59:41.198Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"starting csi server - node version: v16.16.0, package version: 1.7.6, config file: /config/..2022_10_12_14_59_38.1262144370/driver-config-file.yaml, csi-name: org.democratic-csi.iscsi, csi-driver: freenas-iscsi, csi-mode: node, csi-version: 1.5.0, address: , socket: unix:///csi-data/csi.sock.internal","service":"democratic-csi","timestamp":"2022-10-12T14:59:42.550Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: GetPluginInfo call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.40.0\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T14:59:43.663Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: GetPluginInfo response: {\"name\":\"org.democratic-csi.iscsi\",\"vendor_version\":\"1.7.6\"}","service":"democratic-csi","timestamp":"2022-10-12T14:59:43.664Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetInfo call: {\"metadata\":{\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"],\"user-agent\":[\"grpc-go/1.40.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T14:59:43.902Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetInfo response: {\"node_id\":\"microk8s-02.office.altermail.lv\",\"max_volumes_per_node\":0}","service":"democratic-csi","timestamp":"2022-10-12T14:59:43.903Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"metadata\":{\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"],\"user-agent\":[\"grpc-go/1.40.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.392Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.394Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"metadata\":{\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"],\"user-agent\":[\"grpc-go/1.40.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.452Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.458Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.40.0\"],\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.471Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.473Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeStageVolume call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.40.0\"],\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"]},\"request\":{\"publish_context\":{},\"secrets\":\"redacted\",\"volume_context\":{\"storage.kubernetes.io/csiProvisionerIdentity\":\"1665586784169-8081-org.democratic-csi.iscsi\",\"interface\":\"\",\"iqn\":\"iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera\",\"lun\":\"0\",\"node_attach_driver\":\"iscsi\",\"portal\":\"10.0.0.193:3260\",\"portals\":\"\",\"provisioner_driver\":\"freenas-iscsi\"},\"volume_id\":\"pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6\",\"staging_target_path\":\"/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount\",\"volume_capability\":{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"ext4\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:11.509Z"}
retry - failed condition, not trying again
executing filesystem command: mkdir -p -m 0750 /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera -p 10.0.0.193:3260 -o new
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera -p 10.0.0.193:3260 -o update --name node.startup --value manual
executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera -p 10.0.0.193:3260 -l
executing iscsi command: iscsiadm -m session
executing iscsi command: iscsiadm -m session -r 6 --rescan
retry - failed condition, not trying again
executing filesystem command: realpath /dev/disk/by-path/ip-10.0.0.193:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera-lun-0
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"successfully logged into portal 10.0.0.193:3260 and created device /dev/disk/by-path/ip-10.0.0.193:3260-iscsi-iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera-lun-0 with realpath /dev/sdb","service":"democratic-csi","timestamp":"2022-10-12T15:00:15.016Z"}
executing filesystem command: sh -c for file in $(ls -la /dev/mapper/* | grep "\->" | grep -oP "\-> .+" | grep -oP " .+"); do echo $(F=$(echo $file | grep -oP "[a-z0-9-]+");echo $F":"$(ls "/sys/block/${F}/slaves/");); done;
executing filesystem command: realpath /dev/sdb
executing filesystem command: lsblk -a -b -J -O /dev/sdb
executing filesystem command: realpath /dev/sdb
executing filesystem command: lsblk -a -b -l -J -O
executing filesystem command: realpath /dev/loop0
executing filesystem command: realpath /dev/sdb
executing filesystem command: lsblk -a -b -J -O /dev/sdb
executing filesystem command: mkfs.ext4 /dev/sdb
executing filesystem command: blkid -p -o export /dev/sdb
executing filesystem command: realpath /dev/sdb
executing mount command: findmnt --source /dev/sdb --mountpoint /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount --output source,target,fstype,label,options -b -J --nofsroot
executing filesystem command: realpath /dev/sdb
executing mount command: findmnt --source /dev/sdb --mountpoint /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount --output source,target,fstype,label,options -b -J --nofsroot
executing filesystem command: realpath /dev/sdb
executing filesystem command: lsblk -a -b -l -J -O
executing filesystem command: realpath /dev/loop0
executing mount command: mount -t ext4 -o defaults /dev/sdb /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount
executing filesystem command: realpath /dev/sdb
executing filesystem command: lsblk -a -b -l -J -O
executing filesystem command: realpath /dev/loop0
executing filesystem command: resize2fs /dev/sdb
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeStageVolume response: {}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.190Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"metadata\":{\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"],\"user-agent\":[\"grpc-go/1.40.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.208Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.208Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.40.0\"],\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.256Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.257Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"metadata\":{\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"],\"user-agent\":[\"grpc-go/1.40.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.264Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.265Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: NodePublishVolume call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.40.0\"],\"x-forwarded-host\":[\"/var/lib/kubelet/plugins/org.democratic-csi.iscsi/csi.sock\"]},\"request\":{\"publish_context\":{},\"secrets\":\"redacted\",\"volume_context\":{\"portal\":\"10.0.0.193:3260\",\"portals\":\"\",\"provisioner_driver\":\"freenas-iscsi\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1665586784169-8081-org.democratic-csi.iscsi\",\"interface\":\"\",\"iqn\":\"iqn.2005-10.org.freenas.ctl:csi-pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6-clustera\",\"lun\":\"0\",\"node_attach_driver\":\"iscsi\",\"csi.storage.k8s.io/pod.name\":\"pvc-test\",\"csi.storage.k8s.io/serviceAccount.name\":\"default\",\"csi.storage.k8s.io/pod.namespace\":\"default\",\"csi.storage.k8s.io/pod.uid\":\"10a51352-9ff5-4079-90d8-81f6e5712175\",\"csi.storage.k8s.io/ephemeral\":\"false\"},\"volume_id\":\"pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6\",\"staging_target_path\":\"/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount\",\"target_path\":\"/var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount\",\"volume_capability\":{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"ext4\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"},\"readonly\":false},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.283Z"}
retry - failed condition, not trying again
executing filesystem command: mkdir -p -m 0750 /var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount
executing mount command: findmnt --mountpoint /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount --output source,target,fstype,label,options -b -J --nofsroot
executing mount command: findmnt --mountpoint /var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount --output source,target,fstype,label,options -b -J --nofsroot
executing mount command: mount --bind -o defaults /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/8e2a4442eb35491b57a87b755486405804ed07d796557763c902ae2b3571fc1e/globalmount /var/snap/microk8s/common/var/lib/kubelet/pods/10a51352-9ff5-4079-90d8-81f6e5712175/volumes/kubernetes.io~csi/pvc-265c43b3-6bb9-4a2c-946d-8b8d1aea2ab6/mount
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: NodePublishVolume response: {}","service":"democratic-csi","timestamp":"2022-10-12T15:00:18.464Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.6.8\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2022-10-12T15:00:39.944Z"}
{"host":"microk8s-02.office.altermail.lv","level":"info","message":"new response - driver: FreeNASSshDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi","timestamp":"2022-10-12T15:00:39.945Z"}
```

I'm using microk8s (Kubernetes v1.24.6) on Ubuntu 22.04 LTS

**Comment by travisghansen** [comment]
Was this working in the past and is not now? or you're just getting started? Can you send over the helm values you used (obviously scrub secrets if any)?

**Comment by Feliksas** [comment]
```
csiProxy:
  enabled: true
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"
node: # Been experimenting with those
  hostIPC: true
  hostPID: true
# add note here about volume expansion requirements
storageClasses:
- name: freenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
      
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"
    
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-nfs-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-iscsi
    instance-id:
    httpConnection:
      protocol: https
      host: 10.0.0.193
      port: 443
      allowInsecure: true
      username: root
      apiKey: <REDACTED>
      apiVersion: 2
    sshConnection:
      host: 10.0.0.193
      port: 22
      username: kubernetes
      password: <REDACTED>
    zfs:
      cli:
        sudoEnabled: true
      datasetParentName: data/k8s_iscsi/volumes
      detachedSnapshotsDatasetParentName: data/k8s_iscsi/snapshots
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    iscsi:
      targetPortal: "10.0.0.193:3260"
      # for multipath
      targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
      # leave empty to omit usage of -I with iscsiadm
      interface:

      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      # default is "{{ name }}"
      #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: csi-
      nameSuffix: "-clustera"

      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:

      #extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "10000"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
```

This is a new installation on this cluster, I'm also using democratic-csi on another cluster, but 1)nfs driver is used there 2)Kubernetes version is 1.22.
