### ISSUE TITLE
 malformed header: missing HTTP content-type

### ISSUE THREAD

**Issue by alexmc6** [democratic-csi/democratic-csi#250]
I am trying to set up a k8s cluster on Ubuntu 22.04 while provisioning volumes by NFS on a freenas 11.3.U5 NFS server. The NFS server has been serving NFS for some time, but not to k8s. I am trying to use democratic-csi to provision NFS volumes on that freenas box, but it is not working. 

Can anyone suggest more diagnostics or a workaround, or an alternative technique that might work? 

I have a yaml config which attempts to use a new user "k8s" for creating new volumes on the FreeNAS server instead of using the root account. (I am basically following this, but ignoring iSCSI https://jonathangazeley.com/2021/01/05/using-truenas-to-provide-persistent-storage-for-kubernetes/ )
When configured the zfs-nfs-democratic-csi-controller fails as follows:

```
I1119 10:22:02.656845       1 feature_gate.go:245] feature gates: &{map[]}
I1119 10:22:02.656890       1 csi-provisioner.go:139] Version: v3.1.0
I1119 10:22:02.656895       1 csi-provisioner.go:162] Building kube configs for running in cluster...
I1119 10:22:02.657454       1 connection.go:154] Connecting to unix:///csi-data/csi.sock
I1119 10:22:02.659777       1 common.go:111] Probing CSI driver for readiness
I1119 10:22:02.659843       1 connection.go:183] GRPC call: /csi.v1.Identity/Probe
I1119 10:22:02.659888       1 connection.go:184] GRPC request: {}
I1119 10:22:02.665152       1 connection.go:186] GRPC response: {}
I1119 10:22:02.665220       1 connection.go:187] GRPC error: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
E1119 10:22:02.665244       1 csi-provisioner.go:197] CSI driver probe failed: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
```

This error seems similar to https://github.com/kubernetes/kubernetes/pull/112597 

I don't really see a solution in that apart from wait for the core code to be fixed. Is that correct?

Here is my freenas_csi.yaml and the command with which I built the CSI provisioner
helm upgrade --install --create-namespace --values freenas_csi.yaml --namespace democratic-csi --set node.kubeletHostPath="/var/lib/kubelet"  zfs-nfs democratic-csi/democratic-csi

File  freenas_csi.yaml
```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

storageClasses:
- name: freenas-nfs-csi
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

driver:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.1.73
      port: 80
      username: k8s
      password: REDACTED
      allowInsecure: true
    sshConnection:
      host: 192.168.1.73
      port: 22
      username: k8s
      # use either password or key
      password: "REDACTED"
        #      privateKey: |
        #        -----BEGIN RSA PRIVATE KEY-----
        #        ...
        #        -----END RSA PRIVATE KEY-----
    zfs:
      datasetParentName: mnt/tank/k8s/nfs/vols
      detachedSnapshotsDatasetParentName: mnt/tank/k8s/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: k8s
      datasetPermissionsGroup: k8s
    nfs:
      shareHost: 192.168.1.73
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: k8s
      shareMaprootGroup: k8s
      shareMapallUser: ""
      shareMapallGroup: ""
```

And I am trying to create a test PVC with this

kubectl -n democratic-csi create -f test-claim-nfs.yaml

File test-claim-nfs.yaml
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
  storageClassName: freenas-nfs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
