### ISSUE TITLE
PVC not created when using volumeName in PVC spec

### ISSUE THREAD

**Issue by D1StrX** [democratic-csi/democratic-csi#254]
Trying to work with a predefined volumeName in the PVC. Dynamically with pvc-<iscsi_hash> it works perfectly fine.
All values within the helmchart work;
- Set iscsi target naming convention
- Setting the description of the zvol
But I cannot get the volumeName spec in a pvc yaml file to work. The pvc stays on pending with zero logging.
![image](https://user-images.githubusercontent.com/40062371/204037686-3aa03848-0c21-4052-95d5-523a38fff76f.png)

With no volumeName specified it binds almost instantly:
![image](https://user-images.githubusercontent.com/40062371/204038150-406bfc50-6417-4694-8dbb-0a03af01fb59.png)

With VolumeName specified it doesn't work (started with testing by just adding volumeName to the basic setup):
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
  labels:
    app: test-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "truenas-iscsi-csi"
    volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
    volume.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
spec:
  storageClassName: truenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: test-pvc
```

With a basic setup it works:
``` yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: truenas-iscsi-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

In the values.yml for the Helm chart I specified the following propertiesL
- datasetProperties (applies to the zvol)
   - "org.freenas:description"
- nameTemplate (applies to iscsi target)
- nameSuffix (applies to iscsi target)
- extentCommentTemplate (applies to the iscsi extents)

What is missing?

**Comment by travisghansen** [comment]
If I understand your question you are approaching this situation in reverse. volumeName is trying to bind the pvc to an already existing pv with such a name, it’s not giving you an ability to determine what the pv name will be of the created pv to fulfill the pvc.

**Comment by D1StrX** [comment]
I see. Understanding now what the relation of volumeName and PV is. I am trying to figure out the correct/good use case of PV and dynamic PV. While dynamic pvc should be resilient enough when the Kubernetes Cluster is heathy, it is less convenient to remount a _pvc-abcxyz1234_ then a PV with a volumeName. 

To put it in another perspective; 
- **Would a dynamic PV be good to use for databases?** Perfect for up/down scaling and still traceable when using the annotations functionality of Democratic-CSI inside TrueNAS/TrueNAS Scale, but still a pain to work with _pvc-abcxyz1234_ if you need to remount them. 
- **Is a dynamic PV a good use case for storage, lets say for Nextcloud data?** This data is "permanent" and will not scale... so would a PV be a better solution? 
Databases in a statefulSet do have their own PVC and can leverage the flexibility of dynamic PV, if they can survive a cluster crash for example.

I might overcomplicate stuff.. but to get back to the original question of volumeName. Could/Should it be possible to request a dynamic provisioned PVC with a predefined name, for better readability inside the cluster?
Or are there better options? (snapshots?)

PS: Aside of this question, trying to configure CHAP. Could I drop my questions in this issue, or create a new one?

**Comment by travisghansen** [comment]
If you wish to provision storage manually you could deploy the `node-manual` driver which does no provisioning/deprovisioning.

It’s really personal preference about provisioning manually or not, but it is possible to create a pv manually and subsequently link a pvc to a pre-provisioned pv using selectors and/or volume name in the pvc.

It’s also possible to set the reclaim value if you are worried that a pv would be deleted by accident.

You are welcome to shout out questions here about CHAP here.

**Comment by D1StrX** [comment]
Thanks for your reply. Regarding CHAP I made progress, perhaps even got it to work. What exactly happens from Democratic-CSI with CHAP?
- Are the credentials used to authenticate against the _datasetParentName_ ?
- Is the secret base64 encoded or plaintext?
- I see CHAP is enabled on newly created iscsi Targets, but that evens happens with random stuff on `node-db.node.session.auth.password:` why/what happens?

```
storageClasses:
  - name: truenas-iscsi-csi
   ...
    secrets:
      provisioner-secret: <usage?>
      controller-publish-secret: <usage?>
      node-stage-secret:
        node-db.node.session.auth.authmethod: CHAP
        node-db.node.session.auth.username: <base64 or plaintext?>
        node-db.node.session.auth.password: <base64 or plaintext?>
      node-publish-secret: <usage?>
      controller-expand-secret: <usage?>
```
