### ISSUE TITLE
Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway);

### ISSUE THREAD

**Issue by adeelkhalid9** [democratic-csi/democratic-csi#258]
I1229 17:27:37.166847 1 feature_gate.go:245] feature gates: &{map[]}
I1229 17:27:37.167196 1 csi-provisioner.go:139] Version: v3.1.0
I1229 17:27:37.167301 1 csi-provisioner.go:162] Building kube configs for running in cluster...
I1229 17:27:37.168338 1 connection.go:154] Connecting to unix:///csi-data/csi.sock
I1229 17:27:37.168958 1 common.go:111] Probing CSI driver for readiness
I1229 17:27:37.168973 1 connection.go:183] GRPC call: /csi.v1.Identity/Probe
I1229 17:27:37.168977 1 connection.go:184] GRPC request: {}
I1229 17:27:37.170527 1 connection.go:186] GRPC response: {}
I1229 17:27:37.170590 1 connection.go:187] GRPC error: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
E1229 17:27:37.170607 1 csi-provisioner.go:197] CSI driver probe failed: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type

**Comment by travisghansen** [comment]
Which driver? Can you send the config (cleansed of secrets)?

**Comment by adeelkhalid9** [comment]
Thanks for the reply.
Below is the config:

csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
- name: truenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs
      
  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

driver:
  config:
    driver: truenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 10.31.40.167
      port: 80
      # This is the API key that we generated previously
      apiKey: ******
      username: root
      allowInsecure: true
      apiVersion: 2
    sshConnection:
      host: 10.31.40.167
      port: 22
      username: root
      # This is the SSH key that we generated for passwordless authentication
      privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
      ******
        -----END RSA PRIVATE KEY-----
    zfs:
      # Make sure to use the storage pool that was created previously
      datasetParentName: data/k8s/nfs/vols
      detachedSnapshotsDatasetParentName: data/k8s/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: 10.30.39.160
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""

**Comment by monotok** [comment]
Hello,

I am getting the same issue. Everything was working fine a few weeks ago, then TrueNAS VM froze (I had to reboot the entire server). Then I decided to upgrade from TrueNAS 12 - TrueNAS 13. 

So not sure if it was the reboot or the upgrade. The node pod starts up but the controller pod won't do anything. Is the controller pod checking the node pod; or is it checking TrueNAS?

I1230 17:42:41.268348       1 feature_gate.go:245] feature gates: &{map[]}
I1230 17:42:41.268478       1 csi-provisioner.go:139] Version: v3.1.0
I1230 17:42:41.268493       1 csi-provisioner.go:162] Building kube configs for running in cluster...
I1230 17:42:41.270134       1 connection.go:154] Connecting to unix:///csi-data/csi.sock
I1230 17:42:41.272911       1 common.go:111] Probing CSI driver for readiness
I1230 17:42:41.273814       1 connection.go:183] GRPC call: /csi.v1.Identity/Probe
I1230 17:42:41.274086       1 connection.go:184] GRPC request: {}
I1230 17:42:41.295586       1 connection.go:186] GRPC response: {}
I1230 17:42:41.295707       1 connection.go:187] GRPC error: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
E1230 17:42:41.295752       1 csi-provisioner.go:197] CSI driver probe failed: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type

**Comment by monotok** [comment]
For reference.

```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4

    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"

    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
#      # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
#      # if doing CHAP
#      node-db.node.session.auth.authmethod: CHAP
#      node-db.node.session.auth.username: foo
#      node-db.node.session.auth.password: bar
#
#      # if doing mutual CHAP
#      node-db.node.session.auth.username_in: baz
#      node-db.node.session.auth.password_in: bar
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: http
      host: 192.16.20.31
      port: 80
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      apiKey: *******
      username: root
#      password:
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    sshConnection:
      host: 192.16.20.31
      port: 22
      username: root
      # use either password or key
      password: ""
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        *******
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      cli:
        sudoEnabled: False

        # leave paths unset for auto-detection
        paths:
          zfs: /usr/local/sbin/zfs
          zpool: /usr/local/sbin/zpool
          sudo: /usr/local/bin/sudo
          chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below (SCALE and 13+ do not have the same limits)
      # for work-arounds see https://github.com/democratic-csi/democratic-csi/issues/54
      datasetParentName: SP_01/K8s/Vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      detachedSnapshotsDatasetParentName: SP_01/K8s/Snaps
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression: inherit
      # "" (inherit), on, off, verify
      zvolDedup: inherit
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:
    iscsi:
#      targetPortal: "server[:port]"
      targetPortal: "10.120.30.10:3260"
      # for multipath
#      targetPortals: ["10.120.40.10[:3260],10.120.30.10[:3260]"] # [ "server[:port]", "server[:port]", ... ]
      # leave empty to omit usage of -I with iscsiadm
      interface: "ens192"

      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      # default is "{{ name }}"
      nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: "csi-"
      nameSuffix: "-clustera"

      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:

      extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0

```
