### ISSUE TITLE
cannot change root directory to '/host': No such file or directory

### ISSUE THREAD

**Issue by bo0tzz** [democratic-csi/democratic-csi#263]
I'm getting the following error when a new PVC is requested to be provisioned:
```
failed to provision volume with StorageClass "zfs": rpc error: code = Internal desc = Error: chroot: cannot change root directory to '/host': No such file or directory...
```

This is logged in Kubernetes events and on the -controller pod, which does indeed not have the host mount. I would expect this to be running in the -node pod instead?

## Background
I'm deploying to a single Oracle cloud ARM VM. It has a single separate block volume attached which is set up as a zfs pool.

<details><summary>ZFS details</summary>

```
ubuntu@preview-cluster:~$ zpool status
  pool: storage
 state: ONLINE
config:

	NAME                                      STATE     READ WRITE CKSUM
	storage                                   ONLINE       0     0     0
	  scsi-360bf6645c81645ac80f100af5539b78c  ONLINE       0     0     0

errors: No known data errors
ubuntu@preview-cluster:~$ zfs list
NAME                    USED  AVAIL     REFER  MOUNTPOINT
storage                1.00M  48.0G       96K  /storage
storage/k8s             296K  48.0G      104K  /storage/k8s
storage/k8s/snapshots    96K  48.0G       96K  /storage/k8s/snapshots
storage/k8s/volumes      96K  48.0G       96K  /storage/k8s/volumes
```
</details>

I'm trying to use the `zfs-local-dataset` driver. You can find my config and full deployment at https://github.com/bo0tzz/immich-preview-cluster/blob/main/kubernetes/apps/storage/democratic-csi/app/helmrelease.yaml.  

## Logs

See https://gist.github.com/bo0tzz/7739bf8fab3b2e9abadbb5898db94ef0

## Other

For completeness, the volume and deployment I'm using to trigger this:
<details><summary>volume.yaml</summary>

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: testing
spec:
  storageClassName: zfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
```
</details>
<details><summary>deployment.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: testing
  labels:
    app: podinfo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: podinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
      containers:
        - name: podinfo
          image: stefanprodan/podinfo
          volumeMounts:
            - name: data
              mountPath: /data
```
</details>

If there's any other info I can supply, please let me know. Thanks for building this CSI, it's great! :D
