### ISSUE TITLE
[FR] Allow iscsi.nameTemplate in Synology driver

### ISSUE THREAD

**Issue by Twanislas** [democratic-csi/democratic-csi#282]
Hi team,

It would be very cool to be able to template the generated name of the iSCSI LUN created on Synology. This is already available for [ZFS](https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs-generic/index.js#L185) datasets or [FreeNAS](https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/freenas/api.js#L663).

It would also facilitate reusing LUNs a lot, as we could just destroy pvc+pv and recreate a pvc and using the templated name, reconnect to an existing iSCSI LUN.

My use case for instance would be to have the following in my config :
```yaml
namePrefix: "k8s-"
nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
nameSuffix: ""
```
Which would generate a LUN like `k8s-infra-unifi` for a pv named `unifi` in the `infra` namespace.

Thanks for your consideration, and for `democratic-csi` 😃

Ref: [Synology code](src/driver/controller-synology/index.js#L179)
