### ISSUE TITLE
zfs-local-dataset /host mount error

### ISSUE THREAD

**Issue by b0bd** [democratic-csi/democratic-csi#290]
I'm unable to provision any zfs-local-* types, with the following error:

External provisioner is provisioning volume for claim "default/cph-data"
Source: zfs-localpv_zfs-localpv-eph-democratic-csi-controller-57498d99c4-lqphq_b9b141ae-f571-4981-b592-e6bf3629fa2f

`failed to provision volume with StorageClass "zfs-localpv": rpc error: code = Internal desc = Error: chroot: cannot change root directory to '/host': No such file or directory Error: chroot: cannot change root directory to '/host': No such file or directory at Object.zfsError (/home/csi/app/src/utils/zfs.js:78:16) at /home/csi/app/src/utils/zfs.js:1432:51 at ChildProcess.<anonymous> (/home/csi/app/src/utils/zfs.js:1611:11) at ChildProcess.emit (node:events:525:35) at maybeClose (node:internal/child_process:1100:16) at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

kubenetes: 1.26.3, provisioned using kudeadm, on archlinux

helm values:
```
csiDriver:
  name: zfs-localpv

driver:
  config:
    driver: zfs-local-dataset
    zfs:
      datasetParentName: rpool/localpv
      detachedSnapshotsDatasetParentName: rpool/localpv-snaps
      datasetProperties: {}
      datasetEnableQuotas: true
      datasetEnableReservation: false

node:
  driver:
    localtimeHostPath: false

storageClasses:
  - name: zfs-localpv
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
```
