### ISSUE TITLE
Proper way to setup files access rights of provisioned volume?

### ISSUE THREAD

**Issue by mprusinski** [democratic-csi/democratic-csi#296]
Hello,

I decided to use democratic-csi as a storage provisioner for my k8s cluster. I have followed the available tutorials, chosen freenas-nfs driver to go with and even have some sort of success (PVCs are being created correctly and datasets are being created on my TrueNas instance). The issue I'm now facing is that the files created by the pods have different ownership than originally (when different storageClass was used).
For example, I have set up 2 exactly the same Bitnami Mariadb instances (lets call them A and B) - with just one difference - storageClass. The A uses storageClass: freenas-nfs-csi while the B storageClass: local-storage (which uses locally mounted filesystem on node).
After deployment of both pods that is what happens:
- A creates PVC which is created on TrueNas and bounds to the pod
- B creates PVC which is created on Node and bounds to the pod
- from inside of the pod A DB files have 1001:root access rights:
`drwxr-xr-x 2 1001 root 6 May 14 08:27 data`
- while inside B pod the access rights are 1001:1001 (which is the correct)
`drwxr-sr-x 8 1001 1001 4096 May 14 08:19 data`

As a result - the DB works properly on B while on A (freenas-nfs) the DB fails to initialize.

I couldn't find any docs that could explain if this user:group mapping can be changed? Is it even possible to set up csi-democratic so it works with multiple pods and therefore multiple user/group requirements within single democratic-csi configuration (storageClass)?

System info:
TrueNas Core 13.0-U4
democratic-csi chart version: 0.13.7

values file:
```yaml
democratic-csi:
  driver:
    config:
      driver: freenas-nfs
      instance_id:
      httpConnection:
        protocol: http
        host: 192.168.8.99
        port: 80
        apiKey: 1-myAPIKeyasdasdasd
        username: staging
        allowInsecure: true
        apiVersion: 2
      sshConnection:
        host: 192.168.8.99
        port: 22
        username: staging
        privateKey: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          someKey
          -----END OPENSSH PRIVATE KEY-----
      zfs:
        datasetParentName: k8s-staging/nfs/vols
        detachedSnapshotsDatasetParentName: k8s-staging/nfs/snaps
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        cli:
          sudoEnabled: true
      nfs:
        shareHost: 192.168.8.99
        shareAlldirs: false
  csiDriver:
    name: "org.democratic-csi.nfs"

  storageClasses:
  - name: freenas-nfs-csi
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:
```

Am I missing something?

**Comment by travisghansen** [comment]
Welcome! Can you send the yaml output of both storage classes? And maybe a send a screenshot of the share details inside truenas including all the advanced options?

**Comment by travisghansen** [comment]
And the csidriver k8s yamls as well :)

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/issues/274

**Comment by mprusinski** [comment]
Sure!
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/opt/ai"
    openebs.io/cas-type: local
  labels:
    argocd.argoproj.io/instance: openebs
  name: openebs-hostpath
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```


```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: democratic-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    argocd.argoproj.io/instance: democratic-csi
    helm.sh/chart: democratic-csi-0.13.7
  name: freenas-nfs-csi
mountOptions:
  - noatime
  - nfsvers=4
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: controller-expand-secret-freenas-nfs-csi-democratic-csi
  csi.storage.k8s.io/controller-expand-secret-namespace: argocd
  csi.storage.k8s.io/controller-publish-secret-name: controller-publish-secret-freenas-nfs-csi-democratic-csi
  csi.storage.k8s.io/controller-publish-secret-namespace: argocd
  csi.storage.k8s.io/node-publish-secret-name: node-publish-secret-freenas-nfs-csi-democratic-csi
  csi.storage.k8s.io/node-publish-secret-namespace: argocd
  csi.storage.k8s.io/node-stage-secret-name: node-stage-secret-freenas-nfs-csi-democratic-csi
  csi.storage.k8s.io/node-stage-secret-namespace: argocd
  csi.storage.k8s.io/provisioner-secret-name: provisioner-secret-freenas-nfs-csi-democratic-csi
  csi.storage.k8s.io/provisioner-secret-namespace: argocd
  fsType: nfs
provisioner: org.democratic-csi.nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate

```

```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    app.kubernetes.io/instance: democratic-csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    argocd.argoproj.io/instance: democratic-csi
    helm.sh/chart: democratic-csi-0.13.7
  name: org.democratic-csi.nfs
spec:
  attachRequired: false
  podInfoOnMount: true
```
![Zrzut ekranu 2023-05-14 162806](https://github.com/democratic-csi/democratic-csi/assets/19949140/91516d93-e1c9-4de4-979e-05072358cdbf)
