### ISSUE TITLE
"Portal not found in database" using freenas-api-iscsi on Talos Linux

### ISSUE THREAD

**Issue by Eyeless77** [democratic-csi/democratic-csi#302]
Hello,

I'm trying to setup a storage for my Kubernetes cluster on top of Talos Linux v1.4.4 and TrueNAS Scale 22.12.2. I followed the instructions and here what have been done:

1. I patched all talos nodes, iscsi tools are installed on all of them:

```
talosctl -n 192.168.77.201 get extensions
NODE             NAMESPACE   TYPE              ID                                          VERSION   NAME          VERSION
192.168.77.201   runtime     ExtensionStatus   000.ghcr.io-siderolabs-iscsi-tools-v0.1.1   1         iscsi-tools   v0.1.1
```

2. I created an API key for root user in TrueNAS UI.
3. I added a dataset "k8s" in TrueNAS UI:

![2023-05-22_18-48-36](https://github.com/democratic-csi/democratic-csi/assets/4126124/19b436dc-ba4c-411c-8f6a-8289ab24534b)

4. I configured iSCSI portal, initiator groups and targets in TrueNAS UI:

![2023-05-22_18-50-59](https://github.com/democratic-csi/democratic-csi/assets/4126124/83b85c93-8594-4bc0-b425-ff4d242c845f)

![2023-05-22_18-51-09](https://github.com/democratic-csi/democratic-csi/assets/4126124/ab2828d9-a3e5-493f-900f-6f44485fd69f)

![2023-05-22_18-51-31](https://github.com/democratic-csi/democratic-csi/assets/4126124/9c3a3b8d-6e70-4239-977e-e9e8ecba1455)

![2023-05-22_18-51-44](https://github.com/democratic-csi/democratic-csi/assets/4126124/4a2fb510-ab7e-4ffa-bf2a-a8c95f7c1ca3)

5. I created a namespace and labeled it according to the instruction:
`kubectl create ns democratic-csi`
`kubectl label --overwrite namespace democratic-csi pod-security.kubernetes.io/enforce=privileged`

```
k describe ns democratic-csi
Name:         democratic-csi
Labels:       kubernetes.io/metadata.name=democratic-csi
              pod-security.kubernetes.io/enforce=privileged
```

6. I installed the driver using helm with following values:

```
csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
- name: freenas-iscsi-csi
  defaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

volumeSnapshotClasses: []

driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 192.168.77.4
      port: 443
      apiKey: <redacted>
      allowInsecure: true
    zfs:
      datasetParentName: main-pool/k8s/vols
      detachedSnapshotsDatasetParentName: main-pool/k8s/snaps
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize: 4K
    iscsi:
      targetPortal: "192.168.77.4:3260"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-cluster"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 3
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
```

`helm upgrade --install --values freenas-iscsi.yaml --namespace democratic-csi zfs-iscsi democratic-csi/democratic-csi`

All pods within the namespace are up and running.

After that I try to create a test PVC:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "500Mi"
```

And it gets into Pending status

```
k get pvc
NAME       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS        AGE
test-pvc   Pending                                      freenas-iscsi-csi   35s
```

Inspecting the PVC:

```
k describe pvc test-pvc
Name:          test-pvc
Namespace:     default
StorageClass:  freenas-iscsi-csi
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
               volume.kubernetes.io/storage-provisioner: org.democratic-csi.iscsi
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                From                                                                                                                Message
  ----     ------                ----               ----                                                                                                                -------
  Normal   Provisioning          31s (x6 over 63s)  org.democratic-csi.iscsi_zfs-iscsi-democratic-csi-controller-5475f9b6db-plpns_db697754-f40f-41d5-abdd-47353eb34d3f  External provisioner is provisioning volume for claim "default/test-pvc"
  Warning  ProvisioningFailed    30s (x6 over 63s)  org.democratic-csi.iscsi_zfs-iscsi-democratic-csi-controller-5475f9b6db-plpns_db697754-f40f-41d5-abdd-47353eb34d3f  failed to provision volume with StorageClass "freenas-iscsi-csi": rpc error: code = Unknown desc = received error creating iscsi target - code: 422 body: {"iscsi_target_create.groups.0.portal":[{"message":"1 Portal not found in database","errno":22}]}
  Normal   ExternalProvisioning  9s (x6 over 63s)   persistentvolume-controller                                                                                         waiting for a volume to be created, either by external provisioner "org.democratic-csi.iscsi" or manually created by system administrator
```

Error message briefly:
`received error creating iscsi target - code: 422 body: {"iscsi_target_create.groups.0.portal":[{"message":"1 Portal not found in database","errno":22}]}`
This error is generated by `external-provisioner` container.

But at the same time I can see that the Zvol has been created in the dataset:

![2023-05-22_19-07-27](https://github.com/democratic-csi/democratic-csi/assets/4126124/bd856622-feda-499e-a030-26fe74063261)

If I delete this PVC using `kubectl`, it remains in that Zvol.

So what am I doing wrong? Could you help me in investigating this issue?
