### ISSUE TITLE
Cannot read properties of undefined (reading 'apiVersion')

### ISSUE THREAD

**Issue by DevangRadadiya** [democratic-csi/democratic-csi#304]
Getting below error while trying to crate PVC (openshift 4.13.4)

failed to provision volume with StorageClass "iscsi": rpc error: code = Internal desc = TypeError: Cannot read properties of undefined (reading 'apiVersion') TypeError: Cannot read properties of undefined (reading 'apiVersion') at /home/csi/app/src/driver/freenas/ssh.js:107:65 at Registry.getAsync (/home/csi/app/src/utils/registry.js:37:28) at FreeNASSshDriver.getHttpClient (/home/csi/app/src/driver/freenas/ssh.js:101:21) at FreeNASSshDriver.createShare (/home/csi/app/src/driver/freenas/ssh.js:229:35) at FreeNASSshDriver.CreateVolume (/home/csi/app/src/driver/controller-zfs/index.js:1213:33) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)

*****************************************************************
freenas-iscsi.yaml
*****************************************************************
```yaml
csiDriver:
  name: "iscsi"
storageClasses:
- name: iscsi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
    detachedVolumesFromSnapshots: "false"
  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
volumeSnapshotClasses:
- name: iscsi
  parameters:
    detachedSnapshots: "true"
driver:
  config:
    driver: freenas-iscsi
    instance_id:
    sshConnection:
      host: 172.25.10.XXX
      port: 22
      username: cli
      # use either password or key
      password: XXXXXX
    zfs:
      cli:
        sudoEnabled: true
        paths:
          zfs: /usr/local/sbin/zfs
          zpool: /usr/local/sbin/zpool
          sudo: /usr/local/bin/sudo
          chroot: /usr/sbin/chroot
      datasetParentName: OpenShiftNAS/openshift-ds/openshift/storage
      detachedSnapshotsDatasetParentName: OpenShiftNAS/openshift-ds/openshift/snapshots
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "172.25.10.251:3260"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-clustera"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
```

*****************************************************************

helm upgrade --install --create-namespace --values freenas-iscsi.yaml --namespace storage iscsi democratic-csi/democratic-csi --set node.rbac.openshift.privileged=true --set node.driver.localtimeHostPath=false --set controller.rbac.openshift.privileged=true

*****************************************************************
# oc get all -n storage
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/iscsi-democratic-csi-controller-6c8dfbd474-lxdwq   5/5     Running   0          11m
pod/iscsi-democratic-csi-node-c2ttv                    4/4     Running   0          11m
pod/iscsi-democratic-csi-node-lvpxk                    4/4     Running   0          11m
pod/iscsi-democratic-csi-node-mxnpc                    4/4     Running   0          11m

NAME                                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/iscsi-democratic-csi-node   3         3         3       3            3           kubernetes.io/os=linux   11m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/iscsi-democratic-csi-controller   1/1     1            1           11m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/iscsi-democratic-csi-controller-6c8dfbd474   1         1         1       11m
