### ISSUE TITLE
k8s RWO possible corruption

### ISSUE THREAD

**Issue by travisghansen** [democratic-csi/democratic-csi#307]
In order to ensure proper `RWO` constraints k8s requires `attachRequired: true` on the `CSIDriver` object along with enabling the `external-attacher`. If not enabled the volume could be attached on multiple nodes simultaneously possibly resulting in data corruption. The `skip-attach` documentation makes a strong connection between k8s attachments and csi `Controller (Un)Publish` but unfortunately fails to mention how disabling k8s attachments breaks `RWO`.

Details here:

- https://kubernetes-csi.github.io/docs/skip-attach.html
- https://github.com/kubernetes-csi/external-attacher
- https://github.com/kubernetes/kubernetes/issues/103305

In order to fix the issue you can use `v0.14.0` version of the chart which changes the defaults as necessary (see here: https://github.com/democratic-csi/charts/commit/b425a8054b52f99073a98caf8c3072b0329d6dbb) or you can add the following to your `values.yaml`:

```yaml
csiDriver:
  attachRequired: true

controller:
  externalAttacher:
    enabled: true
```

Upgrading `CSIDriver.spec.attachRequired` is not allowed (immutable field) so you must first `kubectl delete csidrivers.storage.k8s.io <your driver>` before using the updated chart/values. It's entirely safe to remove the `CSIDriver` resource and let it recreate.

If you are using any of the `*-local` drivers then please do the inverse as attacher is not required in such scenarios and the defaults have changed:

```yaml
csiDriver:
  attachRequired: false

controller:
  externalAttacher:
    enabled: false
```

After the updates have been applied you should be able to run `kubectl get volumeattachments.storage.k8s.io` to see/ensure relevant entries for your driver(s). If entries are present you should be safe from the k8s side and it should be properly enforcing `RWO` semantics.
