### ISSUE TITLE
Can't use MULTI_NODE_MULTI_WRITER with freenas-api-nfs driver

### ISSUE THREAD

**Issue by dani** [democratic-csi/democratic-csi#309]
Playing with democratic-csi 1.8.3 on my Nomad cluster. I can get the freenas-api-iscsi and freenas-api-nfs drivers to work based on the documentation you provide. But I can't get MULTI_NODE_MULTI_WRITER access when using the nfs driver.

The logs when I start the controller
```
{"host":"ct-w-1","level":"info","message":"new response - driver: FreeNASApiDriver method: ControllerGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"CREATE_DELETE_VOLUME\"}},{\"rpc\":{\"type\":\"LIST_VOLUMES\"}},{\"rpc\":{\"type\":\"GET_CAPACITY\"}},{\"rpc\":{\"type\":\"CREATE_DELETE_SNAPSHOT\"}},{\"rpc\":{\"type\":\"LIST_SNAPSHOTS\"}},{\"rpc\":{\"type\":\"CLONE_VOLUME\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2023-07-19T21:45:49.899Z"}
{"host":"ct-w-1","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.53.0\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-07-19T21:45:49.914Z"}
{"host":"ct-w-1","level":"info","message":"new response - driver: FreeNASApiDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi","timestamp":"2023-07-19T21:45:49.915Z"}
```

My controller's config is quite simple
```yaml
driver: freenas-api-nfs
instance_id:
httpConnection:
  protocol: http
  host: 10.99.3.27
  port: 80
  apiKey: <my API key>
  allowInsecure: false
  apiVersion: 2
zfs:
  datasetParentName: zpool/csi/nfs
  detachedSnapshotsDatasetParentName: zpool/csi/nfssnap
  datasetEnableQuotas: false
  datasetEnableReservation: false
  datasetPermissionsMode: "0770"
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0

nfs:
  shareHost: 10.99.3.27
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks:
    - 10.99.9.0/24
  shareMaprootUser: root
  shareMaprootGroup: root
  shareMapallUser: ""
  shareMapallGroup: ""
```
If I mount my volume asking for single-node-writer access, like
```hcl
    volume "test" {
      type            = "csi"
      source          = "csi-volume-nfs"
      access_mode     = "single-node-writer"
      attachment_mode = "file-system"
    }
```
My volume is correctly mounted, but as soon as I try to use multi-node-multi-writer, the tast fails to start with error message
```
failed to setup alloc: pre-run hook "csi_hook" failed: mounting volumes: rpc error: code = InvalidArgument desc = invalid capability: invalid access_mode, MULTI_NODE_MULTI_WRITER
```
Will try the freenas-nfs driver to see if I can also reproduce (but using the API is nicer)
