### ISSUE TITLE
TrueNAS Scale API iSCSI - Device does not exist

### ISSUE THREAD

**Issue by jpylypiw** [democratic-csi/democratic-csi#310]
Hi there!
I am currently trying to run the TrueNAS Scale API csi in my homelab. The setup worked pretty fine, but when I try to create a new persistent volume the "external provisioner" throws this exception:

```bash
I0721 00:57:08.603687       1 connection.go:194] GRPC request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-8476ae48-0004-4105-bcb1-f9911be24908","parameters":{"csi.storage.k8s.io/pv/name":"pvc-8476ae48-0004-4105-bcb1-f9911be24908","csi.storage.k8s.io/pvc/name":"adguard-pvc","csi.storage.k8s.io/pvc/namespace":"adguard","fsType":"ext4"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}}]}
I0721 00:57:09.446644       1 connection.go:200] GRPC response: {}
I0721 00:57:09.446728       1 connection.go:201] GRPC error: rpc error: code = Unknown desc = received error creating iscsi extent - code: 422 body: {"iscsi_extent_create.disk":[{"message":"Device '/dev/zvol/SSD Pool/k8s/Vol/pvc-8476ae48-0004-4105-bcb1-f9911be24908' for volume 'SSD Pool/k8s/Vol/pvc-8476ae48-0004-4105-bcb1-f9911be24908' does not exist","errno":22}]}
I0721 00:57:09.446802       1 controller.go:816] CreateVolume failed, supports topology = false, node selected false => may reschedule = false => state = Finished: rpc error: code = Unknown desc = received error creating iscsi extent - code: 422 body: {"iscsi_extent_create.disk":[{"message":"Device '/dev/zvol/SSD Pool/k8s/Vol/pvc-8476ae48-0004-4105-bcb1-f9911be24908' for volume 'SSD Pool/k8s/Vol/pvc-8476ae48-0004-4105-bcb1-f9911be24908' does not exist","errno":22}]}
I0721 00:57:09.447010       1 controller.go:1075] Final error received, removing PVC 8476ae48-0004-4105-bcb1-f9911be24908 from claims in progress
```

I installed the csi using Helm and my Operating System is `Talos Linux 1.4.6`. TrueNAS Scale is on Version `TrueNAS-SCALE-22.12.3.2
` 

```yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"

# add note here about volume expansion requirements
storageClasses:
  - name: "truenas-iscsi"
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: ext4

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
        # # any arbitrary iscsiadm entries can be add by creating keys starting with node-db.<entry.name>
        # # if doing CHAP
        # node-db.node.session.auth.authmethod: CHAP
        # node-db.node.session.auth.username: foo
        # node-db.node.session.auth.password: bar

        # # if doing mutual CHAP
        # node-db.node.session.auth.username_in: baz
        # node-db.node.session.auth.password_in: bar
      node-publish-secret:
      controller-expand-secret:

driver:
  # see the driver-config-secret.yaml for syntax
  # NOTE: if setting an existing secret you must still set `driver.config.driver`
  # to the corresponding value that you place in the secret as the value is used
  # by the chart for other purposes beyond secret creation
  existingConfigSecret:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 192.168.xxx.xxx
      port: 443
      allowInsecure: true
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      #apiKey:
      username: xxx
      password: xxx
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      #apiVersion: 2
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      #cli:
      #  sudoEnabled: true
      #
      #  leave paths unset for auto-detection
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      #datasetProperties:
      #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less when using TrueNAS 12 or below (SCALE and 13+ do not have the same limits)
      # for work-arounds see https://github.com/democratic-csi/democratic-csi/issues/54
      datasetParentName: "SSD Pool/k8s/Vol"
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
      detachedSnapshotsDatasetParentName: "SSD Pool/k8s/Snap"
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression:
      # "" (inherit), on, off, verify
      zvolDedup:
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:
    iscsi:
      targetPortal: "192.168.xxx.xxx:3260"
      # for multipath
      targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
      # leave empty to omit usage of -I with iscsiadm
      interface:

      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      # default is "{{ name }}"
      #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: "csi-"
      nameSuffix: ""

      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 3
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:

      #extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: false
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
```

The target is always created, but the extend is failing. I have to say that I migrated from TrueNAS Core to TrueNAS Scale. Maybe I should try reinstalling TrueNAS Scale.

Can someone help me with this problem?
