### ISSUE TITLE
NFS CSI unable to provision volumes  

### ISSUE THREAD

**Issue by darioneto** [democratic-csi/democratic-csi#315]
I've followed some basic guides on nfs csi and while the operator is installed with no problems the pv is not being created on truenas. 

`  Warning  ProvisioningFailed    5s (x2 over 12s)   org.democratic-csi.nfs_truenas-ugly-nfs-democratic-csi-controller-554d65d557-879s8_1de36e40-af55-47f7-b63c-005d91b04d0a  failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Unknown desc = received error creating nfs share - code: 422 body: {"sharingnfs_create.path":[{"message":"/mnt/SSD_POOL/k8s_nfs/vols/pvc-57aa823b-e02b-4bb5-a063-4627260635cc is a subtree of /mnt/SSD_POOL/k8s_nfs and already exports this dataset for 'everybody', i.e. '*'","errno":22}]}`

I changed to group to a wheel but it seems that deployment overrides it with root 
![image](https://github.com/democratic-csi/democratic-csi/assets/31065537/9d2b7784-64ca-4f66-ac0c-833fbe82096f)

Any idea what could be wrong with this?
the manifest :
```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

driver:
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.3.71
      port: 80
      username: root
      password: XXXX
      allowInsecure: true
    sshConnection:
      host: 192.168.3.71
      port: 22
      username: root
      # use either password or key
      password: "XXX"
        #      privateKey: |
        #        -----BEGIN RSA PRIVATE KEY-----
        #        ...
        #        -----END RSA PRIVATE KEY-----
    zfs:
      datasetParentName: SSD_POOL/k8s_nfs/vols
      detachedSnapshotsDatasetParentName:
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: 192.168.3.71
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```
