### ISSUE TITLE
Try to enable volumesnapshot helm error

### ISSUE THREAD

**Issue by lzhengqc** [democratic-csi/democratic-csi#32]
After finish install freenas-nfs-csi, trying to enable snaphost with helm upgrade got an error

```
# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
- name: freenas-nfs-csi
 parameters:
 # if true, snapshots will be created with zfs send/receive
 # detachedSnapshots: "false"
 secrets:
   snapshotter-secret:

```
helm upgrade --values charts\stable\democratic-csi\examples\freenas-nfs.yaml --namespace democratic-csi  zfs-nfs democratic-csi/democratic-csi
Error: failed to parse charts\stable\democratic-csi\examples\freenas-nfs.yaml: error converting YAML to JSON: yaml: line 37: did not find expected key
