### ISSUE TITLE
Issues with values.yaml

### ISSUE THREAD

**Issue by killroy1971** [democratic-csi/democratic-csi#320]
I'm trying to deploy on talos, and I noticed that freenas-iscsi.yaml hadn't been touched in two years, but the values.yaml file is actively maintained. Here are my issues:

I can't deploy pod security. enablePSP generates the following error message:
Error: YAML parse error on democratic-csi/templates/psp.yaml: error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context

If I don't use enablePSP, I get a different error message:
Error: YAML parse error on democratic-csi/templates/storage-classes.yaml: error converting YAML to JSON: yaml: line 8: mapping values are not allowed in this context

For reference, I'm running TrueNAS Core and the latest Talos Linux release.  I've installed the iscsi package and prepped the nodes as instructed here: [https://www.talos.dev/v1.4/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/](url)

Any idea why I'm having these issues?

Here is my cleaned up values.yaml file for reference:

```yaml
nameOverride: ""
fullnameOverride: ""

extraCaCerts: |-
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----

driver:
  existingConfigSecret: []
  config:
    driver: "freenas-iscsi"
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.1.10
      port: 80
      apiKey: < api-key >
      username: root
      allowInsecure: true
    sshConnection:
      host: 192.168.1.10
      port: 22
      username: root
      password: ""
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      cli:
        paths:
          zfs: /usr/local/sbin/zfs
          zpool: /usr/local/sbin/zpool
          sudo: /usr/local/sbin/sudo
          chroot: /usr/local/bin/chroot
      datasetParentName: "ssd02/nuc/v"
      detachedSnapshotDatasetParentName: "ssd02/nuc/s"
      zvolCompression: "lz4"
      zvolDedup: "off"
      zvolEnableReservartion: false
      zvolBlocks: 16k
    iscsi:
      targetPortal: []
     targetPortals: "192.168.1.10:3260"
      interface:
        namePrefix: csi-
        nameSuffix: "-truenas"

csiDriver:
  name: "org.democratic-csi.iscsi"
  version: 1.5.0
  enabled: true
  attachRequired: true
  podInfoOnMount: true

controller:
  enabled: true
  rbac:
    enabled: true
    openshift:
      privileged: false
  replicaCount: 1
  hostNetwork: false
  hostAliases: []
  hostIPC: false
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ""
  strategy: deployment
  externalAttacher:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-attacher:v4.3.0
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources:

  externalProvisioner:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
   args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --extra-create-metadata
    - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources:

  externalResizer:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-resizer:v1.8.0
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --workers=10
    - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources:

  externalSnapshotter:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2
    args:
    - --v=5
    - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources:

  externalHealthMonitorController:
    enabled: false
    image: registry.k8s.io/sig-storage/csi-external-health-monitor-controller:v0.9.0
    args:
    - --v=5
   - --leader-election
    - --leader-election-namespace={{ .Release.Namespace }}
    - --timeout=90s
    - --worker-threads=10
    - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources:

  clusterDriverRegistrar:
    enabled: false

  livenessProbe:
    enabled: true

  # democratic-csi controller
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:latest
    logLevel: info
    lifecycle:
    securityContext:
      allowPrivilegeEscalation: true

    resources:
    extraEnv: []
    extraVolumeMounts: []

  extraVolumes: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

node:
  windows:
    enabled: false
  rbac:
    enabled: true
    openshift:
      privileged: false
  enabled: true
  hostNetwork: true
  hostAliases: []
 hostIPC: true
  hostPID: true
  kubeletHostPath: /var/lib/kubelet
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ""

  livenessProbe:
    enabled: true

  cleanup:
    image: docker.io/busybox:1.32.0

  # democratic-csi node
  driver:
    enabled: true
    image: docker.io/democraticcsi/democratic-csi:latest
    logLevel: info
    localtimeHostPath: /etc/localtime
    lifecycle:

    resources:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
    extraVolumeMounts: []

    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: Directory
  driverRegistrar:
    enabled: true
    image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
    args:
    - --v=5
    - --csi-address={{ .csiSocketAddress }}
    - --kubelet-registration-path={{ .Values.node.kubeletHostPath }}/plugins/{{ .Values.csiDriver.name }}/csi.sock
    extraArgs: []
    resources:
  extraVolumes: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

# add note here about volume expansion requirements
storageClasses:
- name: truenas
  annotations: {}
  labels: "node-role.kubernetes.io/worker="
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
  mountOptions: []
  secrets:
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: "iscsi_admin"
      node-db.node.session.auth.password: "4E9y#O*bWDlG"

volumeSnapshotClasses: []

csiProxy:
  enabled: true
  image: "docker.io/democraticcsi/csi-grpc-proxy:v0.5.3"
  resources: []

enablePSP: true
```
