### ISSUE TITLE
node-manual volumeattachments

### ISSUE THREAD

**Issue by TheAceMan** [democratic-csi/democratic-csi#324]
I upgraded to democratic-csi-0.14.1 and am having issues with node-manual PV. When running version 0.13.7 everything works as expected.

The PV and PVC appear to be created correctly, but the pods that attempt to use them have this error:

```
  Warning  FailedMount             <invalid> (x2 over <invalid>)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[sharename], unattached volumes=[sharename]: timed out waiting for the condition
  Warning  FailedAttachVolume      <invalid> (x12 over <invalid>)  attachdetach-controller  AttachVolume.Attach failed for volume "sharename-pv" : timed out waiting for external-attacher of org.democratic-csi.node-manual CSI driver to attach volume sharename.node-manual.democratic.csi
```
And also I noticed kubectl get -A volumeattachments.storage.k8s.io returned, attached = false:

```
NAME                                                                   ATTACHER                         PV                                              NODE    ATTACHED   AGE
csi-d066458aee053529e52d47b036bac650f9f73fb739790dce2aa031e84370a871   org.democratic-csi.node-manual   sharename-pv                                    k3s42   false      7h57m
```

In version 0.13.7 I do not see any node-manual records in volumeattachments.

I have downgraded back to 0.13.7 and the node-manual PV works again as expected.

**Comment by travisghansen** [comment]
Yeah it’s something I need to work on. It’s related to https://github.com/democratic-csi/democratic-csi/issues/307

`node-manual` doesn’t run the/a controller which is what handles creating volume attachments. I need to make the controller compatible in such cases (it honestly probably already is and just needs to be deployed in a dummy state).

**Comment by Routhinator** [comment]
What chart version should we downgrade to until this is remedied - I've been banging my head against getting node-manual to work and finally found this issue.

**Comment by rouke-broersma** [comment]
> What chart version should we downgrade to until this is remedied - I've been banging my head against getting node-manual to work and finally found this issue.

Just apply the Helm values as specified in the linked issue:

```
csiDriver: 
  attachRequired: false 

controller: 
  externalAttacher: 
    enabled: false
```

**Comment by Routhinator** [comment]
Coming back to this to try and understand the PROPER way to configure the node-manual driver because trying to implement the suggested settings here leads to a broken deployment.


Now to start from the docs (which, for node-manual seems to be the example file: 

```yaml
driver: node-manual
```

Not much there in the way of config or guidance.

I ended up with this for an actual working config:

```yaml
---
controller: 
  enabled: false
node:
  driver:
    image: ghcr.io/democratic-csi/democratic-csi:latest
csiDriver:
  name: "org.democratic-csi.node-manual"
driver:
  config:
    driver: node-manual
```

Now the latest comment here seems to imply I SHOULD be using this:

```yaml

---
controller: 
  enabled: true
  externalAttacher: 
    enabled: false
node:
  driver:
    image: ghcr.io/democratic-csi/democratic-csi:latest
csiDriver:
  name: "org.democratic-csi.node-manual"
  attachRequired: false 
driver:
  config:
    driver: node-manual
```

But that leads to a controller being spun up for a node-manual deployment that has externalProvisioner and externalResizer containers, and they constantly spin with errors.

What's the full deployment example for node-manual in 2024? We need and update to the example and a full clarification on this.

**Comment by travisghansen** [comment]
Can you try a deployment based on this?

```
# driver only works with 1.16+
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.node-manual"

controller:
  externalAttacher:
    enabled: true
  externalProvisioner:
    enabled: false
  externalResizer:
    enabled: false
  externalSnapshotter:
    enabled: false

driver:
  config:
    #driver:
    # rest of per-driver config data/syntax
    driver: node-manual
```

**Comment by Routhinator** [comment]
Will do, just give me a bit - working through another problem at the moment.

**Comment by Routhinator** [comment]
Up and running with that now. My full config (I've set resources so that these pods become "guaranteed" instead of "besteffort")

```yaml
---
controller: 
  externalAttacher:
    enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
  externalProvisioner:
    enabled: false
  externalResizer:
    enabled: false
  externalSnapshotter:
    enabled: false
  driver:
    image: ghcr.io/democratic-csi/democratic-csi:latest
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
node:
  driver:
    image: ghcr.io/democratic-csi/democratic-csi:latest
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
csiDriver:
  name: "org.democratic-csi.node-manual"
driver:
  config:
    driver: node-manual

```
