### ISSUE TITLE
`freenas-api-nfs` seems to incorrectly set dataset quotas

### ISSUE THREAD

**Issue by LarssonOliver** [democratic-csi/democratic-csi#325]
Hi!

Tried out the `freenas-api-nfs` driver today and noticed that storage quotas were being incorrectly set in zfs datasets.

Exapmle PVC:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <redacted>
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: <redacted>
  resources:
    requests:
      storage: 256Mi
```

The created dataset is listed as having a 1GiB quota.

![Selection_008](https://github.com/democratic-csi/democratic-csi/assets/15251568/7f6e84ce-3f1a-4779-808d-c6e0d027b985)

This seems to work as expected when using the `freenas-nfs` driver.
