### ISSUE TITLE
the created PVC remains in a pending state

### ISSUE THREAD

**Issue by kongzi68** [democratic-csi/democratic-csi#326]
Hi, Can you help me take a look at the following error message? Thank you.
The created PVC (Persistent Volume Claim) remains in a pending state. Attached below is the log information.
I have tried both FreeNAS API CSI and FreeNAS NFS CSI (SSH), and they both report the same error message: 'Field was not expected.'"

TrueNAS version: TrueNAS-SCALE-22.12.3.3
OS: ubuntu22.04.3 LTS
k8s version:  kubeadm install k8s v1.27.6
helm install democratic-csi chart version:  democratic-csi-0.14.1

k8s get pvc status:
```bash
betalpha@k8s-tools:~/colin$ kubectl get pvc
NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
test-claim-nfs   Pending                                      freenas-nfs-csi   4h42m
betalpha@k8s-tools:~/colin$ kubectl get pv
No resources found
betalpha@k8s-tools:~/colin$ kubectl describe pvc test-claim-nfs
Name:          test-claim-nfs
Namespace:     default
StorageClass:  freenas-nfs-csi
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-class: freenas-nfs-csi
               volume.beta.kubernetes.io/storage-provisioner: org.democratic-csi.nfs
               volume.kubernetes.io/storage-provisioner: org.democratic-csi.nfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       <none>
Events:
  Type     Reason                Age                       From                                                                                                                         Message
  ----     ------                ----                      ----                                                                                                                         -------
  Warning  ProvisioningFailed    11m (x76 over 4h26m)      org.democratic-csi.nfs_freenas-nfs-noapi-csi-democratic-csi-controller-6bdfb88f88zffmw_33427737-5999-4076-a99f-8a5a23dd6ba6  failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Unknown desc = received error creating nfs share - code: 422 body: {"sharingnfs_create.paths":[{"message":"Field was not expected","errno":22}],"sharingnfs_create.alldirs":[{"message":"Field was not expected","errno":22}],"sharingnfs_create.path":[{"message":"attribute required","errno":22}]}
  Normal   ExternalProvisioning  2m51s (x1123 over 4h42m)  persistentvolume-controller                                                                                                  waiting for a volume to be created, either by external provisioner "org.democratic-csi.nfs" or manually created by system administrator
  Normal   Provisioning          2m27s (x78 over 4h26m)    org.democratic-csi.nfs_freenas-nfs-noapi-csi-democratic-csi-controller-6bdfb88f88zffmw_33427737-5999-4076-a99f-8a5a23dd6ba6  External provisioner is provisioning volume for claim "default/test-claim-nfs"
```

ssh freenas nfs, freenas-nfs.yaml
```yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: nfs

    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"

    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-nfs-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 172.16.60.9
      port: 80
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      #apiKey:
      username: admin
      password: password123
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    sshConnection:
      host: 172.16.60.9
      port: 22
      username: admin
      # use either password or key
      password: "password123"
      #privateKey: |
      #  -----BEGIN RSA PRIVATE KEY-----
      #  ...
      #  -----END RSA PRIVATE KEY-----
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      cli:
        sudoEnabled: true
      #
      #  leave paths unset for auto-detection
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      datasetParentName: bf-nvme-pool1/k8s-pv1/nfs/vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
      detachedSnapshotsDatasetParentName: bf-nvme-pool1/k8s-pv1/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
      #datasetPermissionsAcls:
      #- "-m everyone@:full_set:allow"
      #- "-m u:kube:full_set:allow"

    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: 172.16.60.9
      shareAlldirs: true
      shareAllowedHosts: []
      shareAllowedNetworks: ['172.16.60.0/24']
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```

csi-democratic-csi-controller container csi-driver log：
```
{"level":"debug","message":"FREENAS HTTP HEADERS: {\"server\":\"nginx\",\"date\":\"Thu, 21 Sep 2023 10:23:21 GMT\",\"content-type\":\"application/json; charset=utf-8\",\"content-length\":\"25\",\"connection\":\"close\",\"strict-transport-security\":\"max-age=0; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi"}
{"level":"debug","message":"FREENAS HTTP BODY: \"TrueNAS-SCALE-22.12.3.3\"","service":"democratic-csi"}
{"level":"verbose","message":"validating capabilities: [{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[\"noatime\",\"nfsvers=4\"],\"fs_type\":\"nfs\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}]","service":"democratic-csi"}
{"level":"verbose","message":"ZfsProcessManager command: /usr/bin/sudo /sbin/zfs get -Hp -o name,property,value,received,source volsize,refquota bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865","service":"democratic-csi"}
{"level":"verbose","message":"ZfsProcessManager command: /usr/bin/sudo /sbin/zfs create -p -o org.freenas:description=\"default/test-claim-nfs\" -o democratic-csi:csi_volume_name=\"pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865\" -o democratic-csi:managed_resource=\"true\" -o democratic-csi:volume_context_provisioner_driver=\"freenas-nfs\" bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865","service":"democratic-csi"}
{"level":"verbose","message":"ZfsProcessManager command: /usr/bin/sudo /sbin/zfs set refquota=\"1073741824\" bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865","service":"democratic-csi"}
{"level":"verbose","message":"ZfsProcessManager command: /usr/bin/sudo /sbin/zfs get -Hp -o name,property,value,received,source mountpoint,refquota,compression,democratic-csi:csi_volume_name,democratic-csi:csi_volume_content_source_type,democratic-csi:csi_volume_content_source_id bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865","service":"democratic-csi"}
{"level":"debug","message":"zfs props data: {\"mountpoint\":{\"value\":\"/mnt/bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865\",\"received\":\"-\",\"source\":\"default\"},\"refquota\":{\"value\":\"1073741824\",\"received\":\"-\",\"source\":\"local\"},\"compression\":{\"value\":\"off\",\"received\":\"-\",\"source\":\"inherited from bf-nvme-pool1/k8s-pv1\"},\"democratic-csi:csi_volume_name\":{\"value\":\"pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865\",\"received\":\"-\",\"source\":\"local\"},\"democratic-csi:csi_volume_content_source_type\":{\"value\":\"-\",\"received\":\"-\",\"source\":\"-\"},\"democratic-csi:csi_volume_content_source_id\":{\"value\":\"-\",\"received\":\"-\",\"source\":\"-\"}}","service":"democratic-csi"}
{"level":"verbose","message":"set permission command: /usr/bin/sudo chmod 0777 /mnt/bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865","service":"democratic-csi"}
{"level":"verbose","message":"ZfsProcessManager command: /usr/bin/sudo /sbin/zfs get -Hp -o name,property,value,received,source mountpoint,democratic-csi:freenas_nfs_share_id bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865","service":"democratic-csi"}
{"level":"debug","message":"zfs props data: {\"mountpoint\":{\"value\":\"/mnt/bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865\",\"received\":\"-\",\"source\":\"default\"},\"democratic-csi:freenas_nfs_share_id\":{\"value\":\"-\",\"received\":\"-\",\"source\":\"-\"}}","service":"democratic-csi"}
{"level":"debug","message":"FREENAS HTTP REQUEST: {\"method\":\"POST\",\"url\":\"http://172.16.60.9/api/v2.0/sharing/nfs\",\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\"},\"json\":true,\"body\":{\"paths\":[\"/mnt/bf-nvme-pool1/k8s-pv1/nfs/vols/pvc-0de2c2ea-fb54-43fb-96f0-2fa020a0c865\"],\"comment\":\"default-test-claim-nfs\",\"networks\":[\"172.16.60.0/24\"],\"hosts\":[],\"alldirs\":true,\"ro\":false,\"quiet\":false,\"maproot_user\":\"root\",\"maproot_group\":\"wheel\",\"mapall_user\":\"\",\"mapall_group\":\"\",\"security\":[]},\"agentOptions\":{\"rejectUnauthorized\":false}}","service":"democratic-csi"}
{"level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi"}
{"level":"debug","message":"FREENAS HTTP STATUS: 422","service":"democratic-csi"}
{"level":"debug","message":"FREENAS HTTP HEADERS: {\"server\":\"nginx\",\"date\":\"Thu, 21 Sep 2023 10:23:22 GMT\",\"content-type\":\"application/json; charset=utf-8\",\"content-length\":\"290\",\"connection\":\"close\",\"strict-transport-security\":\"max-age=0; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi"}
{"level":"debug","message":"FREENAS HTTP BODY: {\"sharingnfs_create.paths\":[{\"message\":\"Field was not expected\",\"errno\":22}],\"sharingnfs_create.alldirs\":[{\"message\":\"Field was not expected\",\"errno\":22}],\"sharingnfs_create.path\":[{\"message\":\"attribute required\",\"errno\":22}]}","service":"democratic-csi"}
{"level":"error","message":"handler error - driver: FreeNASSshDriver method: CreateVolume error: {\"name\":\"GrpcError\",\"code\":2,\"message\":\"received error creating nfs share - code: 422 body: {\\\"sharingnfs_create.paths\\\":[{\\\"message\\\":\\\"Field was not expected\\\",\\\"errno\\\":22}],\\\"sharingnfs_create.alldirs\\\":[{\\\"message\\\":\\\"Field was not expected\\\",\\\"errno\\\":22}],\\\"sharingnfs_create.path\\\":[{\\\"message\\\":\\\"attribute required\\\",\\\"errno\\\":22}]}\"}","service":"democratic-csi"}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"debug","message":"performing ssh sanity check..","service":"democratic-csi"}
{"level":"info","message":"new response - driver: FreeNASSshDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi"}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"debug","message":"performing ssh sanity check..","service":"democratic-csi"}
{"level":"info","message":"new response - driver: FreeNASSshDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi"}
{"level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)\"]},\"flags\":0},\"request\":{}}","service":"democratic-csi"}
{"level":"debug","message":"performing ssh sanity check..","service":"democratic-csi"}
{"level":"info","message":"new response - driver: FreeNASSshDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi"}
```
