### ISSUE TITLE
`freenas-api-iscsi`: Concurrently taken snapshots become stuck

### ISSUE THREAD

**Issue by pf56** [democratic-csi/democratic-csi#332]
I'm using `freenas-api-iscsi` in conjunction with [VolSync](https://github.com/backube/volsync) to take regular backups of my data. VolSync takes a snapshot of the PV, mounts it and copies the data offsite. While this is generally functional, scheduling multiple backups at the same time results in some of them becoming stuck.

Right now I have scheduled five different backups at 2am. Every morning, three have been successfully completed and two are stuck in a pending state. Apparently, the driver couldn't create some of the snapshot and timed out after 90 seconds:

```
$ kubectl -n sonarr get volumesnapshots -o yaml
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshot
  metadata:
    creationTimestamp: "2023-10-21T02:00:00Z"
    finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    - snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
    generation: 1
    labels:
      app.kubernetes.io/created-by: volsync
      volsync.backube/cleanup: 390ed6ce-1aa3-4b2d-8788-f7b1a998c62a
    name: volsync-sonarr-backup-src
    namespace: sonarr
    ownerReferences:
    - apiVersion: volsync.backube/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationSource
      name: sonarr-backup
      uid: 390ed6ce-1aa3-4b2d-8788-f7b1a998c62a
    resourceVersion: "37473618"
    uid: 196a9cf2-6bc4-4713-a823-38eb6363202e
  spec:
    source:
      persistentVolumeClaimName: data-sonarr-0
    volumeSnapshotClassName: freenas-api-iscsi-csi
  status:
    boundVolumeSnapshotContentName: snapcontent-196a9cf2-6bc4-4713-a823-38eb6363202e
    error:
      message: 'Failed to check and update snapshot content: failed to take snapshot
        of the volume pvc-2f49a909-d88e-417e-a6a7-94a7e778f49c: "rpc error: code =
        Aborted desc = operation locked due to in progress operation(s): [\"create_snapshot_name_snapshot-196a9cf2-6bc4-4713-a823-38eb6363202e\",\"volume_id_pvc-2f49a909-d88e-417e-a6a7-94a7e778f49c\"]"'
      time: "2023-10-21T02:01:30Z"
    readyToUse: false
kind: List
metadata:
  resourceVersion: ""
```

TrueNAS shows the operation as 'in progress':
![20231021_11h34m18s_grim](https://github.com/democratic-csi/democratic-csi/assets/1151278/af8666f1-a4de-4462-8534-4dc44617668c)

The actual snapshot has not been created:
![20231021_11h35m38s_grim](https://github.com/democratic-csi/democratic-csi/assets/1151278/f217261c-65f0-458d-ac31-7ca54ae7388f)

Restarting the democratic-csi controller causes it to pick up the failed snapshots and successfully create them (sometimes multiple restarts are necessary because one times out again). TrueNAS keeps displaying the jobs in the UI until I reboot the server or manually restart the middleware.

I can work around the issue by scheduling the backups five minutes apart from each other.

The helm release (I'm using Talos):
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-freenas-api-iscsi
spec:
  interval: 10m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 15m
  values:
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
    csiDriver:
      name: org.democratic-csi.freenas-api-iscsi
    storageClasses:
      - name: freenas-api-iscsi-csi
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
        secrets:
          node-stage-secret:
            node-db.node.session.auth.authmethod: CHAP
            node-db.node.session.auth.username: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME}
            node-db.node.session.auth.password: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD}
            node-db.node.session.auth.username_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME_IN}
            node-db.node.session.auth.password_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD_IN}
    volumeSnapshotClasses:
      - name: freenas-api-iscsi-csi
        parameters:
          detachedSnapshots: true
    driver:
      config:
        driver: freenas-api-iscsi
        httpConnection:
          protocols: https
          host: storage.internal.paulfriedrich.me
          port: 443
          apiKey: ${TRUENAS_DEMOCRATIC_CSI_API_KEY}
          allowInsecure: false
        zfs:
          datasetProperties:
            "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          datasetParentName: local/k8s/volumes
          detachedSnapshotsDatasetParentName: local/k8s/snapshots
          zvolEnableReservation: false
        iscsi:
          targetPortal: "10.0.60.3:3260"
          nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          namePrefix: "csi-"
          targetGroups:
            - targetGroupAuthGroup: 1
              targetGroupAuthType: CHAP Mutual
              targetGroupInitiatorGroup: 1
              targetGroupPortalGroup: 2
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 512
          extentRpm: SSD
          extentAvailThreshold: 80
```

The installed snapshot-controller is the democratic-csi one:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-snapshot-controller
spec:
  interval: 10m
  chart:
    spec:
      chart: snapshot-controller
      version: 0.2.4
      sourceRef:
        kind: HelmRepository
        name: democratic-csi-charts
        namespace: flux-system
      interval: 15m
```

TrueNAS is running version `TrueNAS-SCALE-22.12.3.3`.
