### ISSUE TITLE
ProtobufJS Critical Vulnerability

### ISSUE THREAD

**Issue by kusold** [democratic-csi/democratic-csi#339]
Trivy is reporting that the `latest` image contains a Critical vulnerability (9.8) in protobufjs.

https://avd.aquasec.com/nvd/2023/cve-2023-36665/

EDIT: The fixed version is > 7.2.5

I see that Dependabot hasn't attempted a PR in over a year. Is it still configured correctly?

Here is the full scan report:
```
report:
  artifact:
    digest: sha256:fded1d6b6dca9f235cde98667ceb586382d88b17b3c10f2a8742b5167b9a6889
    repository: democraticcsi/democratic-csi
    tag: latest
  registry:
    server: index.docker.io
  scanner:
    name: Trivy
    vendor: Aqua Security
    version: 0.45.1
  summary:
    criticalCount: 1
    highCount: 10
    lowCount: 0
    mediumCount: 13
    noneCount: 0
    unknownCount: 0
  updateTimestamp: '2023-11-09T17:39:15Z'
  vulnerabilities:
    - fixedVersion: 2.31-13+deb11u7
      installedVersion: 2.31-13+deb11u6
      lastModifiedDate: '2023-11-07T04:23:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-4911
      publishedDate: '2023-10-03T18:15:00Z'
      resource: libc-bin
      score: 7.8
      severity: HIGH
      target: ''
      title: buffer overflow in ld.so leading to privilege escalation
      vulnerabilityID: CVE-2023-4911
    - fixedVersion: 2.31-13+deb11u7
      installedVersion: 2.31-13+deb11u6
      lastModifiedDate: '2023-11-07T04:23:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-4911
      publishedDate: '2023-10-03T18:15:00Z'
      resource: libc-l10n
      score: 7.8
      severity: HIGH
      target: ''
      title: buffer overflow in ld.so leading to privilege escalation
      vulnerabilityID: CVE-2023-4911
    - fixedVersion: 2.31-13+deb11u7
      installedVersion: 2.31-13+deb11u6
      lastModifiedDate: '2023-11-07T04:23:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-4911
      publishedDate: '2023-10-03T18:15:00Z'
      resource: libc6
      score: 7.8
      severity: HIGH
      target: ''
      title: buffer overflow in ld.so leading to privilege escalation
      vulnerabilityID: CVE-2023-4911
    - fixedVersion: 1.18.3-6+deb11u4
      installedVersion: 1.18.3-6+deb11u3
      lastModifiedDate: '2023-10-22T23:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-36054
      publishedDate: '2023-08-07T19:15:00Z'
      resource: libgssapi-krb5-2
      score: 6.5
      severity: MEDIUM
      target: ''
      title: Denial of service through freeing uninitialized pointer
      vulnerabilityID: CVE-2023-36054
    - fixedVersion: 1.18.3-6+deb11u4
      installedVersion: 1.18.3-6+deb11u3
      lastModifiedDate: '2023-10-22T23:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-36054
      publishedDate: '2023-08-07T19:15:00Z'
      resource: libk5crypto3
      score: 6.5
      severity: MEDIUM
      target: ''
      title: Denial of service through freeing uninitialized pointer
      vulnerabilityID: CVE-2023-36054
    - fixedVersion: 1.18.3-6+deb11u4
      installedVersion: 1.18.3-6+deb11u3
      lastModifiedDate: '2023-10-22T23:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-36054
      publishedDate: '2023-08-07T19:15:00Z'
      resource: libkrb5-3
      score: 6.5
      severity: MEDIUM
      target: ''
      title: Denial of service through freeing uninitialized pointer
      vulnerabilityID: CVE-2023-36054
    - fixedVersion: 1.18.3-6+deb11u4
      installedVersion: 1.18.3-6+deb11u3
      lastModifiedDate: '2023-10-22T23:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-36054
      publishedDate: '2023-08-07T19:15:00Z'
      resource: libkrb5support0
      score: 6.5
      severity: MEDIUM
      target: ''
      title: Denial of service through freeing uninitialized pointer
      vulnerabilityID: CVE-2023-36054
    - fixedVersion: 6.2+20201114-2+deb11u2
      installedVersion: 6.2+20201114-2+deb11u1
      lastModifiedDate: '2023-11-07T04:11:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-29491
      publishedDate: '2023-04-14T01:15:00Z'
      resource: libncurses6
      score: 7.8
      severity: HIGH
      target: ''
      title: >-
        Local users can trigger security-relevant memory corruption via
        malformed data
      vulnerabilityID: CVE-2023-29491
    - fixedVersion: 6.2+20201114-2+deb11u2
      installedVersion: 6.2+20201114-2+deb11u1
      lastModifiedDate: '2023-11-07T04:11:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-29491
      publishedDate: '2023-04-14T01:15:00Z'
      resource: libncursesw6
      score: 7.8
      severity: HIGH
      target: ''
      title: >-
        Local users can trigger security-relevant memory corruption via
        malformed data
      vulnerabilityID: CVE-2023-29491
    - fixedVersion: 1.1.1n-0+deb11u5
      installedVersion: 1.1.1n-0+deb11u4
      lastModifiedDate: '2023-06-08T19:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-0464
      publishedDate: '2023-03-22T17:15:00Z'
      resource: libssl1.1
      score: 7.5
      severity: HIGH
      target: ''
      title: >-
        Denial of service by excessive resource usage in verifying X509 policy
        constraints
      vulnerabilityID: CVE-2023-0464
    - fixedVersion: 1.1.1n-0+deb11u5
      installedVersion: 1.1.1n-0+deb11u4
      lastModifiedDate: '2023-06-08T19:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-0465
      publishedDate: '2023-03-28T15:15:00Z'
      resource: libssl1.1
      score: 5.3
      severity: MEDIUM
      target: ''
      title: Invalid certificate policies in leaf certificates are silently ignored
      vulnerabilityID: CVE-2023-0465
    - fixedVersion: 1.1.1n-0+deb11u5
      installedVersion: 1.1.1n-0+deb11u4
      lastModifiedDate: '2023-09-28T18:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-0466
      publishedDate: '2023-03-28T15:15:00Z'
      resource: libssl1.1
      score: 5.3
      severity: MEDIUM
      target: ''
      title: Certificate policy check not enabled
      vulnerabilityID: CVE-2023-0466
    - fixedVersion: 1.1.1n-0+deb11u5
      installedVersion: 1.1.1n-0+deb11u4
      lastModifiedDate: '2023-10-27T15:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-2650
      publishedDate: '2023-05-30T14:15:00Z'
      resource: libssl1.1
      score: 6.5
      severity: MEDIUM
      target: ''
      title: Possible DoS translating ASN.1 object identifiers
      vulnerabilityID: CVE-2023-2650
    - fixedVersion: 1.1.1v-0~deb11u1
      installedVersion: 1.1.1n-0+deb11u4
      lastModifiedDate: '2023-10-03T15:48:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-3446
      publishedDate: '2023-07-19T12:15:00Z'
      resource: libssl1.1
      score: 5.3
      severity: MEDIUM
      target: ''
      title: 'openssl: Excessive time spent checking DH keys and parameters'
      vulnerabilityID: CVE-2023-3446
    - fixedVersion: 1.1.1v-0~deb11u1
      installedVersion: 1.1.1n-0+deb11u4
      lastModifiedDate: '2023-11-06T19:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-3817
      publishedDate: '2023-07-31T16:15:00Z'
      resource: libssl1.1
      score: 5.3
      severity: MEDIUM
      target: ''
      title: 'OpenSSL: Excessive time spent checking DH q parameter value'
      vulnerabilityID: CVE-2023-3817
    - fixedVersion: 6.2+20201114-2+deb11u2
      installedVersion: 6.2+20201114-2+deb11u1
      lastModifiedDate: '2023-11-07T04:11:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-29491
      publishedDate: '2023-04-14T01:15:00Z'
      resource: libtinfo6
      score: 7.8
      severity: HIGH
      target: ''
      title: >-
        Local users can trigger security-relevant memory corruption via
        malformed data
      vulnerabilityID: CVE-2023-29491
    - fixedVersion: 2.31-13+deb11u7
      installedVersion: 2.31-13+deb11u6
      lastModifiedDate: '2023-11-07T04:23:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-4911
      publishedDate: '2023-10-03T18:15:00Z'
      resource: locales
      score: 7.8
      severity: HIGH
      target: ''
      title: buffer overflow in ld.so leading to privilege escalation
      vulnerabilityID: CVE-2023-4911
    - fixedVersion: 6.2+20201114-2+deb11u2
      installedVersion: 6.2+20201114-2+deb11u1
      lastModifiedDate: '2023-11-07T04:11:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-29491
      publishedDate: '2023-04-14T01:15:00Z'
      resource: ncurses-base
      score: 7.8
      severity: HIGH
      target: ''
      title: >-
        Local users can trigger security-relevant memory corruption via
        malformed data
      vulnerabilityID: CVE-2023-29491
    - fixedVersion: 6.2+20201114-2+deb11u2
      installedVersion: 6.2+20201114-2+deb11u1
      lastModifiedDate: '2023-11-07T04:11:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-29491
      publishedDate: '2023-04-14T01:15:00Z'
      resource: ncurses-bin
      score: 7.8
      severity: HIGH
      target: ''
      title: >-
        Local users can trigger security-relevant memory corruption via
        malformed data
      vulnerabilityID: CVE-2023-29491
    - fixedVersion: 1.1.1v-0~deb11u1
      installedVersion: 1.1.1n-0+deb11u5
      lastModifiedDate: '2023-10-03T15:48:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-3446
      publishedDate: '2023-07-19T12:15:00Z'
      resource: openssl
      score: 5.3
      severity: MEDIUM
      target: ''
      title: 'openssl: Excessive time spent checking DH keys and parameters'
      vulnerabilityID: CVE-2023-3446
    - fixedVersion: 1.1.1v-0~deb11u1
      installedVersion: 1.1.1n-0+deb11u5
      lastModifiedDate: '2023-11-06T19:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-3817
      publishedDate: '2023-07-31T16:15:00Z'
      resource: openssl
      score: 5.3
      severity: MEDIUM
      target: ''
      title: 'OpenSSL: Excessive time spent checking DH q parameter value'
      vulnerabilityID: CVE-2023-3817
    - fixedVersion: 7.2.4, 6.11.4
      installedVersion: 7.2.3
      lastModifiedDate: '2023-09-07T22:15:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-36665
      publishedDate: '2023-07-05T14:15:00Z'
      resource: protobufjs
      score: 9.8
      severity: CRITICAL
      target: ''
      title: prototype pollution using user-controlled protobuf message
      vulnerabilityID: CVE-2023-36665
    - fixedVersion: 7.5.2, 6.3.1, 5.7.2
      installedVersion: 7.3.8
      lastModifiedDate: '2023-11-07T03:44:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2022-25883
      publishedDate: '2023-06-21T05:15:00Z'
      resource: semver
      score: 7.5
      severity: MEDIUM
      target: ''
      title: Regular expression denial of service
      vulnerabilityID: CVE-2022-25883
    - fixedVersion: 4.1.3
      installedVersion: 2.5.0
      lastModifiedDate: '2023-11-07T04:09:00Z'
      links: []
      primaryLink: https://avd.aquasec.com/nvd/cve-2023-26136
      publishedDate: '2023-07-01T05:15:00Z'
      resource: tough-cookie
      score: 9.8
      severity: MEDIUM
      target: ''
      title: prototype pollution in cookie memstore
      vulnerabilityID: CVE-2023-26136
```
