### ISSUE TITLE
Pods in CrashLoop from Still connecting to unix:///csi-data/csi.sock

### ISSUE THREAD

**Issue by sOblivionsCall** [democratic-csi/democratic-csi#343]
Linux Distro: CoreOS
Kubernetes Distro: k3s

Some background, i had a node failure in my cluster which caused etcd to completely tank. Rather than deal with that i am just building net new and went with the fancy route of k3s on CoreOS rather than just sticking with Ubuntu (Immediately regretting that decision). This config is pulled directly from the `application` resource on the cluster as this Helm Chart is deployed through ArgoCD. The chart deploys as expected but the node pods never come up. 

# Config
```
  Sync:
    Compared To:
      Destination:
        Namespace:  democratic-csi
        Server:     https://kubernetes.default.svc
      Source:
        Chart:  democratic-csi
        Helm:
          Parameters:
            Name:         driver.config.driver
            Value:        freenas-nfs
            Name:         driver.config.instance_id
            Value:        freenas
            Name:         driver.config.httpConnection.protocol
            Value:        http
            Name:         driver.config.httpConnection.host
            Value:        10.1.1.10
            Name:         driver.config.httpConnection.port
            Value:        80
            Name:         driver.config.httpConnection.username
            Value:        root
            Name:         driver.config.httpConnection.password
            Value:        <REDACTEED>
            Name:         driver.config.httpConnection.allowInsecure
            Value:        true
            Name:         driver.config.sshConnection.host
            Value:        10.1.1.10
            Name:         driver.config.sshConnection.port
            Value:        22
            Name:         driver.config.sshConnection.username
            Value:        root
            Name:         driver.config.sshConnection.password
            Value:        <REDACTEED>
            Name:         driver.config.zfs.datasetParentName
            Value:        Storage/kubernetes/k3s/vols
            Name:         driver.config.zfs.detachedSnapshotsDatasetParentName
            Value:        Storage/kubernetes/k3s/snaps
            Name:         driver.config.zfs.datasetEnableQuotas
            Value:        true
            Name:         driver.config.zfs.datasetEnableReservation
            Value:        false
            Name:         driver.config.zfs.datasetPermissionsMode
            Value:        0777
            Name:         driver.config.zfs.datasetPermissionsUser
            Value:        0
            Name:         driver.config.zfs.datasetPermissionsGroup
            Value:        0
            Name:         driver.config.nfs.shareHost
            Value:        10.1.1.10
            Name:         driver.config.nfs.shareAlldirs
            Value:        false
            Name:         driver.config.nfs.shareAllowedHosts[0]
            Name:         driver.config.nfs.shareAllowedNetworks[0]
            Value:        10.1.1.0/24
            Name:         driver.config.nfs.shareMaprootUser
            Value:        root
            Name:         driver.config.nfs.shareMaprootGroup
            Value:        wheel
            Name:         driver.config.nfs.shareMapallUser
            Name:         driver.config.nfs.shareMapallGroup
            Name:         csiDriver.name
            Value:        org.democratic-csi.nfs
            Name:         storageClasses[0].name
            Value:        freenas-nfs-csi
            Name:         storageClasses[0].defaultClass
            Value:        false
            Name:         storageClasses[0].reclaimPolicy
            Value:        Delete
            Name:         storageClasses[0].volumeBindingMode
            Value:        Immediate
            Name:         storageClasses[0].allowVolumeExpansion
            Value:        true
            Name:         storageClasses[0].parameters.fsType
            Value:        nfs
            Name:         storageClasses[0].mountOptions[0]
            Value:        noatime
            Name:         storageClasses[0].mountOptions[1]
            Value:        nfsvers=3
        Repo URL:         https://democratic-csi.github.io/charts/
        Target Revision:  0.14.2
    Revision:             0.14.2
    Status:               OutOfSync
Events:
  Type     Reason              Age    From                           Message
  ----     ------              ----   ----                           -------
  Normal   OperationStarted    20m    argocd-application-controller  Initiated automated sync to '0.12.0'
  Normal   ResourceUpdated     20m    argocd-application-controller  Updated sync status:  -> OutOfSync
  Normal   ResourceUpdated     20m    argocd-application-controller  Updated health status:  -> Progressing
  Normal   ResourceUpdated     20m    argocd-application-controller  Updated sync status:  -> OutOfSync
  Normal   ResourceUpdated     20m    argocd-application-controller  Updated health status:  -> Progressing
  Warning  OperationCompleted  14m    argocd-application-controller  Sync operation to 0.12.0 failed: one or more objects failed to apply, reason: DaemonSet.apps "zfs-nfs-democratic-csi-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/csi-role":"node", "app.kubernetes.io/instance":"zfs-nfs", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable,Deployment.apps "zfs-nfs-democratic-csi-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/csi-role":"controller", "app.kubernetes.io/instance":"zfs-nfs", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable (retried 5 times).
  Normal   OperationStarted    13m    argocd-server                  admin initiated sync to 0.12.0 (0.12.0)
  Warning  OperationCompleted  13m    argocd-application-controller  Sync operation to 0.12.0 failed: one or more objects failed to apply, reason: Deployment.apps "zfs-nfs-democratic-csi-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/csi-role":"controller", "app.kubernetes.io/instance":"zfs-nfs", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable,DaemonSet.apps "zfs-nfs-democratic-csi-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/csi-role":"node", "app.kubernetes.io/instance":"zfs-nfs", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
  Normal   OperationStarted    13m    argocd-application-controller  Initiated automated sync to '0.13.0'
  Warning  OperationCompleted  7m44s  argocd-application-controller  Sync operation to 0.13.0 failed: one or more objects failed to apply, reason: DaemonSet.apps "zfs-nfs-democratic-csi-node" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"node-linux", "app.kubernetes.io/csi-role":"node", "app.kubernetes.io/instance":"zfs-nfs", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable,Deployment.apps "zfs-nfs-democratic-csi-controller" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"controller-linux", "app.kubernetes.io/csi-role":"controller", "app.kubernetes.io/instance":"zfs-nfs", "app.kubernetes.io/managed-by":"Helm", "app.kubernetes.io/name":"democratic-csi"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable (retried 5 times).
  Normal   OperationStarted    3m59s  argocd-application-controller  Initiated automated sync to '0.14.2'
```
# State
```bash
kubectl get pods -n democratic-csi
NAME                                                 READY   STATUS             RESTARTS         AGE
zfs-nfs-democratic-csi-controller-64f89f5b84-dt828   5/5     Running            0                31m
zfs-nfs-democratic-csi-node-6csxr                    1/4     CrashLoopBackOff   32 (4m22s ago)   31m
zfs-nfs-democratic-csi-node-bhmdr                    1/4     CrashLoopBackOff   32 (4m12s ago)   31m
zfs-nfs-democratic-csi-node-sdcnp                    2/4     CrashLoopBackOff   32 (4m1s ago)    31m
```
# Logs
```bash
kubectl logs -f zfs-nfs-democratic-csi-node-6csxr -n democratic-csi -c csi-driver

```
```bash
kubectl logs -f zfs-nfs-democratic-csi-node-6csxr -n democratic-csi -c csi-proxy
listening on [unix:///csi-data/csi.sock], proxy to [unix:///csi-data/csi.sock.internal]
waiting for socket [/csi-data/csi.sock.internal] to appear, 60s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 59s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 58s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 57s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 56s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 55s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 54s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 53s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 52s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 51s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 50s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 49s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 48s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 47s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 46s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 45s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 44s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 43s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 42s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 41s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 40s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 39s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 38s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 37s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 36s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 35s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 34s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 33s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 32s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 31s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 30s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 29s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 28s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 27s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 26s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 25s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 24s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 23s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 22s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 21s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 20s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 19s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 18s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 17s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 16s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 15s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 14s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 13s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 12s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 11s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 10s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 9s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 8s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 7s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 6s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 5s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 4s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 3s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 2s remaining
waiting for socket [/csi-data/csi.sock.internal] to appear, 1s remaining
panic: timeout reached waiting for socket

goroutine 1 [running]:
main.main()
        /go/src/csi-grpc-proxy/main.go:95 +0x4d0
```
```bash
kubectl logs -f zfs-nfs-democratic-csi-node-6csxr -n democratic-csi -c driver-registrar
I1113 23:16:02.145504       1 main.go:166] Version: v2.5.0
I1113 23:16:02.145539       1 main.go:167] Running node-driver-registrar in mode=registration
I1113 23:16:02.146126       1 main.go:191] Attempting to open a gRPC connection with: "/csi-data/csi.sock"
I1113 23:16:02.146151       1 connection.go:154] Connecting to unix:///csi-data/csi.sock
W1113 23:16:12.146863       1 connection.go:173] Still connecting to unix:///csi-data/csi.sock
W1113 23:16:22.146517       1 connection.go:173] Still connecting to unix:///csi-data/csi.sock
```

The issue appears to be in `driver-registrar` in connecting to the unix socket but i am completely at a loss at this point. I did review #45 as it had the same or a very similar error as me but i couldn't really glean anything helpful from it.  I have tried versions 0.11.2, 0.12.0, 0.13.0, and 0.14.2 with the same error. My hunch that firewalld and/or selinix were causing problems did not remediate the issue when i turned them both off. Any insight and direction would be helpful.

**Comment by travisghansen** [comment]
The `csi-driver` container has 0 logs? That is the most important to get logs to..

**Comment by sOblivionsCall** [comment]
no logs whatsoever :(

**Comment by sOblivionsCall** [comment]
for context this exact config was working line for line in my previous cluster with chart version 0.11.2 so i'm sure it's something with the OS or kubernetes version. I have reviewing and make sure i am on an OS version that supports my version of k3s and that i am using the right chart for this version of k3s.

**Comment by travisghansen** [comment]
This feels like an selinux like situation. What does describe say about that container? Any system logs showing something relevant?

**Comment by sOblivionsCall** [comment]
```yaml 
kubectl describe pod zfs-nfs-democratic-csi-node-6csxr -n democratic-csi
Name:             zfs-nfs-democratic-csi-node-6csxr
Namespace:        democratic-csi
Priority:         0
Service Account:  zfs-nfs-democratic-csi-node-sa
Node:             k3snode3/10.1.1.20
Start Time:       Mon, 13 Nov 2023 16:43:51 -0600
Labels:           app.kubernetes.io/csi-role=node
                  app.kubernetes.io/instance=zfs-nfs
                  app.kubernetes.io/name=democratic-csi
                  controller-revision-hash=6475d5c86b
                  pod-template-generation=1
Annotations:      checksum/configmap: f44be1c61f01070186dd4b039175951a9d6e17c99ff3b59dd818d9e0167cf794
                  checksum/secret: c79a5ec12b9130559ee5adfecd748e421a0f32c62febb6b9dae7532caae7c9cc
Status:           Running
IP:               10.1.1.20
IPs:
  IP:           10.1.1.20
Controlled By:  DaemonSet/zfs-nfs-democratic-csi-node
Containers:
  csi-driver:
    Container ID:  containerd://faccdfb0ddc2569af9ec1d874d5c75789d62de21805104973f15732707534362
    Image:         docker.io/democraticcsi/democratic-csi:latest
    Image ID:      docker.io/democraticcsi/democratic-csi@sha256:1b526bb4e1634ce84534a7a51b038efa91335767c625dcec62cdc42a744e2bcd
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-version=1.5.0
      --csi-name=org.democratic-csi.nfs
      --driver-config-file=/config/driver-config-file.yaml
      --log-level=info
      --csi-mode=node
      --server-socket=/csi-data/csi.sock.internal
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/etc/localtime" to rootfs at "/etc/localtime": mount /etc/localtime:/etc/localtime (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown
      Exit Code:    128
      Started:      Wed, 31 Dec 1969 18:00:00 -0600
      Finished:     Mon, 13 Nov 2023 21:25:39 -0600
    Ready:          False
    Restart Count:  60
    Liveness:       exec [bin/liveness-probe --csi-version=1.5.0 --csi-address=/csi-data/csi.sock.internal] delay=10s timeout=15s period=60s #success=1 #failure=3
    Environment:
      CSI_NODE_ID:           (v1:spec.nodeName)
      NODE_EXTRA_CA_CERTS:  /tmp/certs/extra-ca-certs.crt
    Mounts:
      /config from config (rw)
      /csi-data from socket-dir (rw)
      /dev from dev-dir (rw)
      /etc/localtime from localtime (ro)
      /host from host-dir (rw)
      /lib/modules from modules-dir (ro)
      /run/udev from udev-data (rw)
      /sys from sys-dir (rw)
      /tmp/certs from extra-ca-certs (rw)
      /var/lib/kubelet from kubelet-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ms66 (ro)
  csi-proxy:
    Container ID:   containerd://a912b4d7f4c43c91d74e73ab3c8fa4cf95bfa66e151e99a488c33ff35213e209
    Image:          docker.io/democraticcsi/csi-grpc-proxy:v0.4.2
    Image ID:       docker.io/democraticcsi/csi-grpc-proxy@sha256:687c7d43b0f36bc95f4450768e4e4cc75c916c766c8eb31f401a0623a4463a80
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 13 Nov 2023 21:24:12 -0600
      Finished:     Mon, 13 Nov 2023 21:25:12 -0600
    Ready:          False
    Restart Count:  50
    Environment:
      BIND_TO:   unix:///csi-data/csi.sock
      PROXY_TO:  unix:///csi-data/csi.sock.internal
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ms66 (ro)
  driver-registrar:
    Container ID:  containerd://2fa783a450f1bf17959107887ec8f35433b8591b8407ac755d5a5fc17ef6615a
    Image:         k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
    Image ID:      k8s.gcr.io/sig-storage/csi-node-driver-registrar@sha256:4fd21f36075b44d1a423dfb262ad79202ce54e95f5cbc4622a6c1c38ab287ad6
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=/csi-data/csi.sock
      --kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.nfs/csi.sock
    State:          Running
      Started:      Mon, 13 Nov 2023 21:29:52 -0600
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 13 Nov 2023 21:24:12 -0600
      Finished:     Mon, 13 Nov 2023 21:24:41 -0600
    Ready:          True
    Restart Count:  98
    Liveness:       exec [/csi-node-driver-registrar --kubelet-registration-path=/var/lib/kubelet/plugins/org.democratic-csi.nfs/csi.sock --mode=kubelet-registration-probe] delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      KUBE_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /csi-data from socket-dir (rw)
      /registration from registration-dir (rw)
      /var/lib/kubelet from kubelet-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ms66 (ro)
  cleanup:
    Container ID:  containerd://3a2d4112df2a4377962e020786a7a10a5b3dfaa21eee1acb4f4dc7f842d35a4f
    Image:         docker.io/busybox:1.32.0
    Image ID:      docker.io/library/busybox@sha256:bde48e1751173b709090c2539fdf12d6ba64e88ec7a4301591227ce925f3c678
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      --
    Args:
      while true; do sleep 2; done;
    State:          Running
      Started:      Mon, 13 Nov 2023 16:43:52 -0600
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /plugins from plugins-dir (rw)
      /registration from registration-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ms66 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  socket-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins/org.democratic-csi.nfs
    HostPathType:  DirectoryOrCreate
  plugins-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins
    HostPathType:  Directory
  registration-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins_registry
    HostPathType:  Directory
  kubelet-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet
    HostPathType:  Directory
  dev-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  modules-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  localtime:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:  
  udev-data:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  
  sys-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  Directory
  host-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  Directory
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zfs-nfs-democratic-csi-driver-config
    Optional:    false
  extra-ca-certs:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      zfs-nfs-democratic-csi
    Optional:  false
  kube-api-access-7ms66:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                      From     Message
  ----     ------     ----                     ----     -------
  Warning  Unhealthy  5m59s (x281 over 4h44m)  kubelet  (combined from similar events): Liveness probe failed: F1114 03:24:01.958276      21 main.go:159] Kubelet plugin registration hasn't succeeded yet, file=/var/lib/kubelet/plugins/org.democratic-csi.nfs/registration doesn't exist.
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
  /workspace/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0xf86600, 0x3, 0x0, 0xc0001cb960, 0x0, {0xc47a41, 0x1}, 0xc000230a10, 0x0)
  /workspace/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/klog/v2.(*loggingT).printf(0xa63799, 0x4, 0x0, {0x0, 0x0}, {0xa8ac8d, 0x48}, {0xc000230a10, 0x1, 0x1})
  /workspace/vendor/k8s.io/klog/v2/klog.go:753 +0x1c5
k8s.io/klog/v2.Fatalf(...)
  /workspace/vendor/k8s.io/klog/v2/klog.go:1532
main.main()
  /workspace/cmd/csi-node-driver-registrar/main.go:159 +0x48e

goroutine 20 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0xc0000bf200)
  /workspace/vendor/k8s.io/klog/v2/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
           /workspace/vendor/k8s.io/klog/v2/klog.go:420 +0xfb
  Warning  BackOff  64s (x1656 over 4h46m)  kubelet  Back-off restarting failed container csi-driver in pod zfs-nfs-democratic-csi-node-6csxr_democratic-csi(9d3fd0c2-9456-4278-a56a-cba2dc6988a9)
```

```bash
sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```

Still trying to figure out where selinux logs anything at all on CoreOS. /var/log/audit and /var/log/messages just don't exist at all
