### ISSUE TITLE
Regular sync for share and dataset descriptions

### ISSUE THREAD

**Issue by jd-chapman** [democratic-csi/democratic-csi#352]
I use Velero to backup my data, stored on a Truenas box, which works great with democratic-csi using the Velero CSI plugin and data mover. The only small problem is that when Velero does a restore it creates PVCs temporarily, with names derived from the restore name. The PV assigned to that PVC is then reassigned to the *actual* PVC for the application after the data is restored. This means the descriptions on the share and dataset have the temporary Velero names after a restore, rather than the names of the actual PVC they're bound to.

Is it possible to perform a regular sync between the share and dataset descriptions and the actual PVCs they're associated with?

Happy to share configurations or any other information, just let me know.

Democratic CSI: freenas-api using nfs shares
Truenas: Scale 23.10.0.1
Velero: v1.12.2

**Comment by travisghansen** [comment]
Can you send over the config and an example of the current outcome vs the desired outcome?

**Comment by jd-chapman** [comment]
Sure thing - I'm using Terraform to deploy everything using the Helm chart, so I've translated the options I've changed in the democratic-csi Helm chart to yaml. I'll also put the Terraform config at the end of the reply for clarity. The snapshot controller is using all default values, so I won't include that.
```yaml
csiDriver.name: "org.democratic-csi.nfs"

storageClasses:
  - name: "truenas-nfs-csi"
    defaultClass: true
    reclaimPolicy: "delete"
    volumeBindingMode: "Immediate"
    allowVolumeExpansion: true
    fsType: "nfs"
    mountOptions:
      - "noatime"
      - "nfsvers=4.2"

volumeSnapshotClasses:
  - name: "truenas-nfs-csi"
    annotations:
      "snapshot.storage.kubernetes.io/is-default-class": true
      "velero.io/csi-volumesnapshot-class": true
    deletionPolicy: "Delete"

driver:
  config:
    driver: "freenas-api-nfs"
    httpConnection:
      protocol: "https"
      host: *local IP address*
      port: 443
      apiKey: *truenas API key*
      allowInsecure: true
    zfs:
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      datasetParentName: "vault/exclude/k3s/live"
      detachedSnapshotsDatasetParentName: "vault/exclude/k3s/snapshot"
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: *local IP address*
      shareAllowedNetworks:
        - "10.42.0.0/16"
        - "10.43.0.0/16"
        - "192.168.1.0/24"
      shareMaprootUser: "root"
      shareMaprootGroup: "root"
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
```

Desired outcome - the description and comments on the dataset and NFS share respectively match the PVC they relate to:
<img width="823" alt="Screenshot 2023-12-04 at 22 00 10" src="https://github.com/democratic-csi/democratic-csi/assets/57732106/31eb73eb-52ff-4c37-95ea-e5cf375c4a1a">
<img width="380" alt="Screenshot 2023-12-04 at 21 58 56" src="https://github.com/democratic-csi/democratic-csi/assets/57732106/5d1fcce5-af9d-4269-bd34-8500875e1ec2">
<img width="1473" alt="Screenshot 2023-12-04 at 21 59 27" src="https://github.com/democratic-csi/democratic-csi/assets/57732106/58afbf39-44bd-43bf-83e1-873136f52c2a">

Current outcome, after a Velero restore - the description and comments take the name of the temporary PVC that Velero uses to download the data:
<img width="775" alt="Screenshot 2023-12-04 at 22 06 58" src="https://github.com/democratic-csi/democratic-csi/assets/57732106/37c27f55-a5d5-4f19-bd81-0b264bdd12a5">
<img width="378" alt="Screenshot 2023-12-04 at 22 06 36" src="https://github.com/democratic-csi/democratic-csi/assets/57732106/d56aaea2-da36-46c5-8884-deaf6c08eb44">
<img width="1469" alt="Screenshot 2023-12-04 at 22 06 18" src="https://github.com/democratic-csi/democratic-csi/assets/57732106/bce168f5-1dd2-4ebd-ad0a-b47ec405d281">

I think this is happening because, although the Velero PVC is temporary, it keeps the PV and just binds it to the actual PVC that the application uses.

Terraform config for completeness:
```terraform
resource "helm_release" "democratic_csi" {
  name = "democratic-csi"

  repository = "https://democratic-csi.github.io/charts/"
  chart      = "democratic-csi"
  version    = "0.14.2"

  namespace = kubernetes_namespace.democratic_csi.metadata[0].name

  timeout = 300

  set {
    name  = "csiDriver.name"
    value = "org.democratic-csi.nfs"
  }

  set {
    name  = "storageClasses[0].name"
    value = "truenas-nfs-csi"
  }
  set {
    name  = "storageClasses[0].defaultClass"
    value = "true"
  }
  set {
    name  = "storageClasses[0].reclaimPolicy"
    value = "Delete"
  }
  set {
    name  = "storageClasses[0].volumeBindingMode"
    value = "Immediate"
  }
  set {
    name  = "storageClasses[0].allowVolumeExpansion"
    value = "true"
  }
  set {
    name  = "storageClasses[0].parameters.fsType"
    value = "nfs"
  }
  set {
    name  = "storageClasses[0].mountOptions[0]"
    value = "noatime"
  }
  set {
    name  = "storageClasses[0].mountOptions[1]"
    value = "nfsvers=4.2"
  }

  set {
    name  = "volumeSnapshotClasses[0].name"
    value = "truenas-nfs-csi"
  }
  set {
    name  = "volumeSnapshotClasses[0].annotations.snapshot\\.storage\\.kubernetes\\.io/is-default-class"
    value = "true"
    type  = "string"
  }
  set {
    name  = "volumeSnapshotClasses[0].annotations.velero\\.io/csi-volumesnapshot-class"
    value = "true"
    type  = "string"
  }
  set {
    name  = "volumeSnapshotClasses[0].labels.velero\\.io/csi-volumesnapshot-class"
    value = "true"
    type  = "string"
  }
  set {
    name  = "volumeSnapshotClasses[0].deletionPolicy"
    value = "Delete"
  }

  set {
    name  = "driver.config.driver"
    value = "freenas-api-nfs" # this name is important, can't be changed to truenas
  }
  set {
    name  = "driver.config.httpConnection.protocol"
    value = "https"
  }
  set_sensitive {
    name  = "driver.config.httpConnection.host"
    value = var.truenas_ip_address
  }
  set {
    name  = "driver.config.httpConnection.port"
    value = "443"
  }
  set_sensitive {
    name  = "driver.config.httpConnection.apiKey"
    value = var.truenas_api_key
  }
  set {
    name  = "driver.config.httpConnection.allowInsecure"
    value = "true"
  }
  set {
    name  = "driver.config.zfs.datasetProperties.org\\.freenas\\:description"
    value = "\"{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}\""
  }
  set {
    name  = "driver.config.zfs.datasetParentName"
    value = var.truenas_k3s_dataset
  }
  set {
    name  = "driver.config.zfs.detachedSnapshotsDatasetParentName"
    value = var.truenas_k3s_snapshot_dataset
  }
  set {
    name  = "driver.config.zfs.datasetEnableQuotas"
    value = "true"
  }
  set {
    name  = "driver.config.zfs.datasetEnableReservation"
    value = "false"
  }
  set {
    name  = "driver.config.zfs.datasetPermissionsMode"
    value = "0777"
  }
  set {
    name  = "driver.config.zfs.datasetPermissionsUser"
    value = "0"
  }
  set {
    name  = "driver.config.zfs.datasetPermissionsGroup"
    value = "0"
  }
  set_sensitive {
    name  = "driver.config.nfs.shareHost"
    value = var.truenas_ip_address
  }
  set {
    name  = "driver.config.nfs.shareAllowedNetworks[0]"
    value = "10.42.0.0/16"
  }
  set {
    name  = "driver.config.nfs.shareAllowedNetworks[1]"
    value = "10.43.0.0/16"
  }
  set {
    name  = "driver.config.nfs.shareAllowedNetworks[2]"
    value = "192.168.1.0/24"
  }
  set {
    name  = "driver.config.nfs.shareMaprootUser"
    value = "root"
  }
  set {
    name  = "driver.config.nfs.shareMaprootGroup"
    value = "root"
  }
  set {
    name  = "driver.config.nfs.shareCommentTemplate"
    value = "\"{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}\""
  }
}
```
