### ISSUE TITLE
nfs-client does not create PVs

### ISSUE THREAD

**Issue by EugenMayer** [democratic-csi/democratic-csi#358]
Deploying democratic-csi on 

- ubuntu jammy 22.01
- k3s 1.28.4

The NFS-server runs on debian:bookworm and exposes nfs 4.2 bases exports

My chart/driver is configured (tf template):

```yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs-client"

storageClasses:
- name: nfs
  defaultClass: ${defaultStorage}
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: false
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=4.2
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []

driver:
  config:
    driver: nfs-client
    instance_id:
    nfs:
      shareHost: ${nfsServer}
      shareBasePath: "${nfsMountBasePath}"
      # shareHost:shareBasePath should be mounted at this location in the controller container
      controllerBasePath: "/storage"
      dirPermissionsMode: "0777"
      dirPermissionsUser: ${nfsDirPermissionUser}
      dirPermissionsGroup: ${nfsDirPermissionGroup}


controller:
  enabled: true
  externalResizer:
    enabled: false
  strategy: deployment
  driver:
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
      privileged: true
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p /storage; mount ${nfsServer}:${nfsMountBasePath} /storage"]
      preStop:
        exec:
          command: ["/bin/sh","-c","umount /storage"]
```

And i can see that the controller has mount /storage and it is indeed the expected NFS share (touching a file is transparent).

Creating a workload with an pvc for the storageClass `nfs` does create the PVC, but does never create the PV.

Reading through the issues i'am no longer sure, if democratic-csi actually creates the folders on the share itself? so in my case it would be /$SHARE/v/<pvc-uid> - do i have to create it myself or did i misunderstand it somehow?

Side-Note: I can without an issue mount the share using native k8s csi `nfs` support, so generally the client/server setup is working without issues. But, then mentioned, i would have to create the folder also my self, if i mount "a sub folder". If would have expected democratic-csi taking care of creating the subfolders since it mounts the "share root" it could just create the folder?
