### ISSUE TITLE
[Openshift] Fix Deployment

### ISSUE THREAD

**Issue by alexanderniebuhr** [democratic-csi/democratic-csi#36]
I am installing the driver on OKD based on Openshift, but it does not deploy completely because it uses HostPath.   
I am very new to CSI, sadly I am not very safe to investigate the code myself, but am happy to help and learn

```
Error creating: pods "zfs-iscsi-democratic-csi-node-" is forbidden: unable to validate against any security context constraint [
provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used
provider restricted: .spec.securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used 
spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used
spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[4]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[5]: Invalid value: "hostPath": hostPath volumes are not allowed to be used
spec.volumes[6]: Invalid value: "hostPath": hostPath volumes are not allowed to be used
spec.volumes[7]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[8]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[9]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[10]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.volumes[11]: Invalid value: "hostPath": hostPath volumes are not allowed to be used 
spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added
spec.containers[0].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used 
spec.containers[0].securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used
spec.containers[1].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used 
spec.containers[1].securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used
spec.containers[2].securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used
spec.containers[2].securityContext.hostIPC: Invalid value: true: Host IPC is not allowed to be used]
```

**Comment by travisghansen** [comment]
I can look around but I’m not entirely sure how okd normally deals with this kind of thing. It requires very elevated permissions because it’s dealing with host level mounts and host level block devices doing formatting etc.

I’ll do some research but if you know generally what needs to be done let me know!

**Comment by alexanderniebuhr** [comment]
If HostPath is unavoidable then the containers in OKD / Openshift must run as privileged (see following)
However, the main reason to use OKD / Openshift is that container do not get elevated permissions. So another solution might be more future proof

- https://docs.okd.io/latest/storage/persistent_storage/persistent-storage-hostpath.html#persistent-storage-hostpath-pod_persistent-storage-hostpath
- https://docs.okd.io/latest/storage/persistent_storage/persistent-storage-hostpath.html#persistent-storage-hostpath-pod_persistent-storage-hostpath

**Comment by travisghansen** [comment]
Yeah it’s pretty much a requirement for csi drivers. I’m sure we’re simply missing some standard setup...I’m going to see how other csi drivers deploy (ie: trident from netapp etc) and if I can find what’s necessary to make it work.

**Comment by alexanderniebuhr** [comment]
Also `hostIPC` and `hostNetwork` might be a bigger problem here, as these are not allowed for containers by default SCCs (security context contraints). I also think others do not use them. I know that the `ebs.csi.aws.com` does work.

**Comment by travisghansen** [comment]
Those both are explicitly required actually to interact properly with host nfs and host iscsi daemons.

I’ll probably need you to try out variations with psp and scc to see what works (or view how other csi drivers you’re using are deploying those). To help me do you know which of those 2 is throwing the error? Scc or psp?

Forgive the ignorance with openshift :(

**Comment by alexanderniebuhr** [comment]
I have some more information for this. OKD / Openshift works with different SCCs. This said we could bind these to the service accounts as following example of `ebs.csi.aws.com` shows.

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-privileged-role
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged

```

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-controller-privileged-binding
subjects:
  - kind: ServiceAccount
    name: aws-ebs-csi-driver-controller-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebs-privileged-role
```

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebs-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: aws-ebs-csi-driver-node-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ebs-privileged-role
```

Does this help? And should I try to add these manually and let you know if they are fixing the issue?

**Comment by travisghansen** [comment]
Yeah if you could test that would be fantastic! I don’t have a openshift cluster to work with or I would gladly do the testing.

Can you send over the associated scc resource from the above examples?

**Comment by alexanderniebuhr** [comment]
Yeah, I am fine doing the testing. If I were knowing more about csi in general I would have made a PR right away.
Above did fix the permission issue, but we are not there yet (we have new errors).

1. css ressource

```yaml
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    kubernetes.io/description: restricted denies access to all host features and requires pods to be run with a UID, and SELinux context that are allocated to the namespace.  This is the most restrictive SCC and it is used by default for authenticated users.
    release.openshift.io/create-only: "true"
  creationTimestamp: "2020-12-14T09:47:06Z"
  generation: 1
  name: restricted
  resourceVersion: "1537"
  selfLink: /apis/security.openshift.io/v1/securitycontextconstraints/restricted
  uid: 4c7b1e57-80d5-45eb-8563-c490af7c2aeb
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```

2. the new error

```
Error: container create failed:
time="2020-12-20T17:18:31Z" level=warning msg="exit status 1"
time="2020-12-20T17:18:31Z" level=error msg="container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/etc/localtime\\\\\\\" to rootfs \\\\\\\"/var/lib/containers/storage/overlay/411107db5a425f6beb61d9bb669a667de3736055d6645afc3f7ca1d90769733a/merged\\\\\\\" at \\\\\\\"/var/lib/containers/storage/overlay/411107db5a425f6beb61d9bb669a667de3736055d6645afc3f7ca1d90769733a/merged/usr/share/zoneinfo/UCT\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"" container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/var/lib/containers/storage/overlay/411107db5a425f6beb61d9bb669a667de3736055d6645afc3f7ca1d90769733a/merged\\\" at \\\"/var/lib/containers/storage/overlay/411107db5a425f6beb61d9bb669a667de3736055d6645afc3f7ca1d90769733a/merged/usr/share/zoneinfo/UCT\\\" caused \\\"not a directory\\\"\""
```

**Comment by travisghansen** [comment]
Ah that can be disabled I think..lemme check real quick what was done to make that optional...

**Comment by travisghansen** [comment]
Here: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L120

set it to null or false should do the trick..

**Comment by alexanderniebuhr** [comment]
Sure. So the question is, could you implement the role and rolebindings conditionally in the helm chart. So it is just installed if on OKD / OpenShift and not breaking Kubernetes?

**Comment by travisghansen** [comment]
Yeah of course! From what I can tell the only difference is the addition to the cluster role and the scc itself?

Were you able to test an actual pvc now?

**Comment by alexanderniebuhr** [comment]
Yes. pvc with iscsi seems to work fine. It does state `bound` in okd and in truenas it generated iscsi targets and volumes. I don't have anything to test snapshots and expansion on right now. But I do not think it might be a problem. So yeah it looks like adding the cluster role and role binding is the difference. **NOTE the privileged scc is default with any OKD / OpenShift deployment, so no need to add it.**

**Comment by travisghansen** [comment]
Ah I see regarding the scc. So all you did was add the additional stuff to the clusterrole right?

Did you actually have a pod attach to the pvc? I want to make sure the node operations are functioning.

**Comment by alexanderniebuhr** [comment]
I did actually added them, might be wrong. But was easier to test for me. I used following steps

1. add role

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-privileged-role
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
```

2. add controller role binding

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-privileged-binding
subjects:
  - kind: ServiceAccount
    name: zfs-iscsi-democratic-csi-controller-sa
    namespace: democratic-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-privileged-role
```

3. add node role binding

```yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: zfs-iscsi-democratic-csi-node-sa
    namespace: democratic-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-privileged-role
```

4. changed localtimeHostPath to null (this might also be necessary as all OKD / OpenShift deployments are based on coreOS, or might add alternate path in readme)

**Comment by travisghansen** [comment]
I’ll just add the additional stuff to already created clusterrole so it should ‘just work’.

Did you actually attach from a pod? Once I know that fully worked I’ll adjust the chart and push a new version for you to test (it should only take a couple seconds honestly).

**Comment by alexanderniebuhr** [comment]
I just tried. Did not work. But this is an issue with the nodes. I have to find out how to start iscsi service on okd provisioned nodes

**Comment by travisghansen** [comment]
OK cool. I'll commit an update to the chart and have you deploy with the chart and we'll go from there.

**Comment by travisghansen** [comment]
Ok, make sure you remove any of the manual stuff that you created and try again with version `0.6.1` of the chart.

https://github.com/democratic-csi/charts/commit/bfdf4b174b76c191f8057fba40394122ac3ed72a

```
--set node.rbac.openshift.privileged=true
```

^ should do the trick.

**Comment by alexanderniebuhr** [comment]
Yes. Installation works. pvc too. Mounting currently not. But I do not think this is an error with the install..

**Comment by travisghansen** [comment]
@alexanderniebuhr awesome! We'll leave this open until we figure out the mounting situation just to be sure. If you're running iscsi you do need to make sure the iscsi tools are installed on the host and the daemon(s) running as part of node prep (outside the scope of the driver). If you want to use multipath make sure that's installed/configured/running as desired as well.

Let me know how I can help.

**Comment by alexanderniebuhr** [comment]
yeah. I did checked this. I enabled them in my cluster machine config pool. So they are working and throwing me some errors. Might be a setup issue with my truenas. I did installed it just today and am not very far with configuration .. but it should work. However here are some errors i gathered. Not quite right in this issue though

```
Dec 20 19:03:26 eleron iscsid[824]: iscsid: conn 0 login rejected: initiator error - target not found (02/03)
Dec 20 19:03:26 eleron iscsid[824]: iscsid: Connection9:0 to [target: iqn.2019-05.io.nbhr:storage:spifly:csi-pvc-0db8d5e3-23f7-4496-b62d-0d2fffc84d96-okd, portal: 172.20.62.51,3260] through [iface: default] is shutdown.
```

**Comment by travisghansen** [comment]
Can you send the full helm values you’re using (cleanse them of course)?

When I sit at my desk I’ll send a couple commands that can help us figure out what’s going on.

**Comment by alexanderniebuhr** [comment]
Here is my full helm values yaml. I think it might be good, but I am missing something. Also, it seems I cannot get any iscsi connection to truenas right now, so I must check this

```yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "iscsi.csi.****.io"

# add note here about volume expansion requirements
storageClasses:
  - name: truenas-iscsi-csi
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: ext4

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"

    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

node:
  driver:
    localtimeHostPath: null

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: truenas-iscsi
    instance_id:
    httpConnection:
      protocol: http
      host: 172.20.62.51
      port: 80
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      apiKey: "****"
      #username: root
      #password:
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    sshConnection:
      host: 172.20.62.51
      port: 22
      username: root
      # use either password or key
      password: "****"
      #privateKey: |
      #  -----BEGIN RSA PRIVATE KEY-----
      #  ...
      #  -----END RSA PRIVATE KEY-----
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      #cli:
      #  sudoEnabled: true
      #
      #  leave paths unset for auto-detection
      #  paths:
      #    zfs: /usr/local/sbin/zfs
      #    zpool: /usr/local/sbin/zpool
      #    sudo: /usr/local/bin/sudo
      #    chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      #datasetProperties:
      #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"

      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less
      datasetParentName: default/okd/vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      detachedSnapshotsDatasetParentName: default/okd/snaps
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression: ""
      # "" (inherit), on, off, verify
      zvolDedup: ""
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:
    iscsi:
      targetPortal: "172.20.62.51:3260"
      targetPortals: []
      # leave empty to omit usage of -I with iscsiadm
      interface:

      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      # default is "{{ name }}"
      #nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: csi-
      nameSuffix: "-okd"
      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
```
