### ISSUE TITLE
freenas-api-smb - Unable to mount smb PVC (Permission denied)

### ISSUE THREAD

**Issue by sherif-fanous** [democratic-csi/democratic-csi#362]
I've successfully deployed `democratic-csi` on my k0s cluster and got most of it working with my TrueNAS Scale.

1. I deployed 3 releases, 1 for each of iscsi, nfs, and smb.
2. Successfully tested the provisioning and mounting of iscsi and nfs volumes
3. Sccessfully tested the provisioning of smb volumes

But can't for the life of my figure out how to mount that volume into a pod. Basically I can't figure out how to pass the username and password options to the `mount -t cifs` command

**Things I tried**

1. In the Helm chart populate the `secrets` within the smb `storageclass` object

```yaml
storageClasses:
  - allowVolumeExpansion: true
    defaultClass: false
    name: smb-democratic-csi-truenas
    reclaimPolicy: Delete
    secrets:
      controller-expand-secret:
        user: admin
        password: <redacted>
      controller-publish-secret:
        user: admin
        password: <redacted>
      node-publish-secret:
        user: admin
        password: <redacted>
      node-stage-secret:
        user: admin
        password: <redacted>
      provisioner-secret:
        user: admin
        password: <redacted>
    volumeBindingMode: Immediate
```

2. Create a `secret` using kustomize and in the Helm chart set the `parameters` within the smb `storageclass` object

```yaml
storageClasses:
  - allowVolumeExpansion: true
    defaultClass: false
    name: smb-democratic-csi-truenas
    reclaimPolicy: Delete
    parameters:
      csi.storage.k8s.io/controller-expand-secret-name: smb-creds
      csi.storage.k8s.io/controller-expand-secret-namespace: democratic-csi
      csi.storage.k8s.io/controller-publish-secret-name: smb-creds
      csi.storage.k8s.io/controller-publish-secret-namespace: democratic-csi
      csi.storage.k8s.io/node-publish-secret-name: smb-creds
      csi.storage.k8s.io/node-publish-secret-namespace: democratic-csi
      csi.storage.k8s.io/node-stage-secret-name: smb-creds
      csi.storage.k8s.io/node-stage-secret-namespace: democratic-csi
      csi.storage.k8s.io/provisioner-secret-name: smb-creds
      csi.storage.k8s.io/provisioner-secret-namespace: democratic-csi
    volumeBindingMode: Immediate
```

Both approaches work while provisioning the volume but fail to mount the volume into the pod

**Logs from csi-driver**

```console
executing mount command: findmnt --source //192.168.4.59/pvc-04a1ba28-b2c1-439b-bd1c-a82b95f5db14 --mountpoint /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/smb-democratic-csi-truenas/dbb8e72a87fc74a1d5d48b3ada96a6a0e7eeace0a3697b822a999febe09679ed/globalmount --output source,target,fstype,label,options -b -J --nofsroot
executing mount command: mount -t cifs -o defaults,guest //192.168.4.59/pvc-04a1ba28-b2c1-439b-bd1c-a82b95f5db14 /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/smb-democratic-csi-truenas/dbb8e72a87fc74a1d5d48b3ada96a6a0e7eeace0a3697b822a999febe09679ed/globalmount
{"host":"k0s","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":32,\"stdout\":\"\",\"stderr\":\"/usr/local/bin/mount: illegal option -- o\\nmount error(13): Permission denied\\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:35:02.698Z"}
{"host":"k0s","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.9.9\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:35:33.598Z"}
{"host":"k0s","level":"info","message":"new response - driver: FreeNASApiDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi","timestamp":"2024-01-11T14:35:33.598Z"}
{"host":"k0s","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-node-js/1.9.9\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:36:33.600Z"}
{"host":"k0s","level":"info","message":"new response - driver: FreeNASApiDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi","timestamp":"2024-01-11T14:36:33.600Z"}
{"host":"k0s","level":"info","message":"new request - driver: FreeNASApiDriver method: NodeGetCapabilities call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.56.3\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.794Z"}
{"host":"k0s","level":"info","message":"new response - driver: FreeNASApiDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.794Z"}
{"host":"k0s","level":"info","message":"new request - driver: FreeNASApiDriver method: NodeGetCapabilities call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.56.3\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.798Z"}
{"host":"k0s","level":"info","message":"new response - driver: FreeNASApiDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.798Z"}
{"host":"k0s","level":"info","message":"new request - driver: FreeNASApiDriver method: NodeGetCapabilities call: {\"metadata\":{\"x-forwarded-host\":[\"localhost\"],\"user-agent\":[\"grpc-go/1.56.3\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.799Z"}
{"host":"k0s","level":"info","message":"new response - driver: FreeNASApiDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.799Z"}
{"host":"k0s","level":"info","message":"new request - driver: FreeNASApiDriver method: NodeStageVolume call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.56.3\"],\"x-forwarded-host\":[\"localhost\"]},\"request\":{\"publish_context\":{},\"secrets\":\"redacted\",\"volume_context\":{\"server\":\"192.168.4.59\",\"share\":\"pvc-04a1ba28-b2c1-439b-bd1c-a82b95f5db14\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1704983334475-4567-smb-democratic-csi-truenas\",\"node_attach_driver\":\"smb\",\"provisioner_driver\":\"freenas-api-smb\"},\"volume_id\":\"pvc-04a1ba28-b2c1-439b-bd1c-a82b95f5db14\",\"staging_target_path\":\"/var/lib/k0s/kubelet/plugins/kubernetes.io/csi/smb-democratic-csi-truenas/dbb8e72a87fc74a1d5d48b3ada96a6a0e7eeace0a3697b822a999febe09679ed/globalmount\",\"volume_capability\":{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}},\"cancelled\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.800Z"}
executing mount command: findmnt --source //192.168.4.59/pvc-04a1ba28-b2c1-439b-bd1c-a82b95f5db14 --mountpoint /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/smb-democratic-csi-truenas/dbb8e72a87fc74a1d5d48b3ada96a6a0e7eeace0a3697b822a999febe09679ed/globalmount --output source,target,fstype,label,options -b -J --nofsroot
executing mount command: mount -t cifs -o defaults,guest //192.168.4.59/pvc-04a1ba28-b2c1-439b-bd1c-a82b95f5db14 /var/lib/k0s/kubelet/plugins/kubernetes.io/csi/smb-democratic-csi-truenas/dbb8e72a87fc74a1d5d48b3ada96a6a0e7eeace0a3697b822a999febe09679ed/globalmount
{"host":"k0s","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":32,\"stdout\":\"\",\"stderr\":\"/usr/local/bin/mount: illegal option -- o\\nmount error(13): Permission denied\\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2024-01-11T14:37:04.862Z"}
```

Now I clearly know that the problem is that the `mount -t cifs` command is missing the `username` and `password` options but I can't figure out how to make sure they are passed to the mount command.

Thanks

**Comment by sherif-fanous** [comment]
Finally figured it out by reading through the source code and educating myself on how CSI works.

For anyone that gets stuck with this in the future here's what you need to do

1. Ensure you define the `node-stage-secret-name` and `node-stage-secret-namespace` parameters within the StorageClass

```yaml
parameters:
  csi.storage.k8s.io/node-stage-secret-name: smb-creds
  csi.storage.k8s.io/node-stage-secret-namespace: democratic-csi
```

2. The `smb-creds` secret referenced by `node-stage-secret-name` must include a `mount_flags` key that passes the additional mount flags (Specifically for SMB `username=<username>,password=<password>`) Make sure to replace the `<username>` and `<password>` placeholders with your actual values

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: smb-creds
stringData:
  mount_flags: username=<username>,password=<password>
```
