### ISSUE TITLE
Synology iSCSI docker plugin installation: invalid argument

### ISSUE THREAD

**Issue by sethicis** [democratic-csi/democratic-csi#368]
## The issue

I wanted to try out the Synology iSCSI driver with a docker swarm setup, but when I try to build and install the logs say:
```
Handler for POST /v1.44/plugins/sethicis/swarm-csi-synology-iscsi:v1.8.4/enable returned error: dial unix /run/docker/plugins/483d665bf410ce519ceb7f5efa3b52ad8bd4afa07fbc25d553ea2c0e6fb60800/csi-synology-iscsi.sock: connect: invalid argument
```

I'm kind of stumped as to what is happening, but it seems like something is going wrong during the grpc startup.

## How I'm building

I'm using a modified version of the [script written by olljanat](https://github.com/olljanat/csi-plugins-for-docker-swarm/blob/master/democratic-csi/local-hostpath/config.json).

my `config.json`
```json
{
    "description": "democratic-csi storage driver for synology iscsi",
    "interface": {
      "types": ["docker.csinode/1.0", "docker.csicontroller/1.0"],
      "socket": "csi-synology-iscsi.sock"
    },
    "network": {
      "type": "host"
    },
    "mounts": [
      {
        "description": "Used to access the dynamically attached block devices",
        "name": "dev",
        "source": "/dev/",
        "destination": "/dev",
        "type": "bind",
        "options": [
          "rbind",
          "rshared"
        ]  
      }
    ],
    "env": [
      {
        "name": "CSI_ENDPOINT",
        "description": "the CSI endpoint to listen to internally",
        "value": "unix:///run/docker/plugins/csi-synology-iscsi.sock"
      }
    ],
    "entrypoint": [
      "/home/csi/app/entrypoint.sh"
    ],
    "workdir": "/home/csi/app",
    "linux": {
      "capabilities": [
        "CAP_SYS_ADMIN",
        "CAP_CHOWN"
      ],
      "AllowAllDevices": true,
      "devices": null
    },
    "PropagatedMount": "/data/published"
  }

```

My `build.sh`
```bash
#!/bin/bash

USAGE="Usage: ./build.sh <Docker Hub Organization> <Democratic CSI version>"

if [ "$1" == "--help" ] || [ "$#" -lt "2" ]; then
	echo $USAGE
	exit 0
fi

ORG=$1
VERSION=$2

set -x

rm -rf rootfs
docker plugin disable csi-synology-iscsi:latest
docker plugin rm csi-synology-iscsi:latest
docker plugin disable $ORG/swarm-csi-synology-iscsi:v$VERSION
docker plugin rm $ORG/swarm-csi-synology-iscsi:v$VERSION
docker rm -vf iscsifsimage

docker create --name iscsifsimage docker.io/democraticcsi/democratic-csi:v$VERSION
mkdir -p rootfs
docker export iscsifsimage | tar -x -C rootfs
docker rm -vf iscsifsimage
mkdir -p rootfs/home/csi/app/config
cp entrypoint.sh rootfs/home/csi/app/
cp synology-iscsi.yaml rootfs/home/csi/app/config/

docker plugin create $ORG/swarm-csi-synology-iscsi:v$VERSION .
docker plugin enable $ORG/swarm-csi-synology-iscsi:v$VERSION
docker plugin push $ORG/swarm-csi-synology-iscsi:v$VERSION
docker plugin disable $ORG/swarm-csi-synology-iscsi:v$VERSION
docker plugin rm $ORG/swarm-csi-synology-iscsi:v$VERSION
docker plugin install --alias csi-synology-iscsi --grant-all-permissions $ORG/swarm-csi-synology-iscsi:v$VERSION
```

My `entrypoint.sh`
```bash
#!/bin/sh

bin/democratic-csi \
  --driver-config-file=config/synology-iscsi.yaml \
  --log-level=debug \
  --server-socket=/run/docker/plugins/csi-synology-iscsi.sock \
  --csi-version=1.5.0 \
  --csi-name=csi-synology-iscsi \
  --server-socket-permissions-mode=0755
```

My driver config yaml
```yaml
driver: synology-iscsi
httpConnection:
  protocol: http
  host: 192.168.1.3 // changed for security
  port: 5000
  username: sethicis
  password: '<redacted>'
  allowInsecure: true
  # should be uniqe across all installs to the same nas
  session: "democratic-csi"
  serialize: true

# Choose the DSM volume this driver operates on. The default value is /volume1.
synology:
  volume: /volume2

iscsi:
  targetPortal: "192.168.1.3" // changed for security
  # for multipath
  targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
  # leave empty to omit usage of -I with iscsiadm
  interface: ""
  # can be whatever you would like
  baseiqn: "iqn.2000-01.com.synology:csi."

  # MUST ensure uniqueness
  # full iqn limit is 223 bytes, plan accordingly
  namePrefix: "swarm-cluster"
  nameSuffix: ""

  # documented below are several blocks
  # pick the option appropriate for you based on what your backing fs is and desired features
  # you do not need to alter dev_attribs under normal circumstances but they may be altered in advanced use-cases
  # These options can also be configured per storage-class:
  # See https://github.com/democratic-csi/democratic-csi/blob/master/docs/storage-class-parameters.md
  lunTemplate:
    # can be static value or handlebars template
    #description: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
    
    # btrfs thin provisioning
    type: "THIN"
    # tpws = Hardware-assisted zeroing
    # caw = Hardware-assisted locking
    # 3pc = Hardware-assisted data transfer
    # tpu = Space reclamation
    # can_snapshot = Snapshot
    #dev_attribs:
    #- dev_attrib: emulate_tpws
    #  enable: 1
    #- dev_attrib: emulate_caw
    #  enable: 1
    #- dev_attrib: emulate_3pc
    #  enable: 1
    #- dev_attrib: emulate_tpu
    #  enable: 0
    #- dev_attrib: can_snapshot
    #  enable: 1

    # btfs thick provisioning
    # only zeroing and locking supported
    #type: "BLUN_THICK"
    # tpws = Hardware-assisted zeroing
    # caw = Hardware-assisted locking
    #dev_attribs:
    #- dev_attrib: emulate_tpws
    #  enable: 1
    #- dev_attrib: emulate_caw
    #  enable: 1

    # ext4 thinn provisioning UI sends everything with enabled=0
    #type: "THIN"

    # ext4 thin with advanced legacy features set
    # can only alter tpu (all others are set as enabled=1)
    #type: "ADV"
    #dev_attribs:
    #- dev_attrib: emulate_tpu
    #  enable: 1

    # ext4 thick
    # can only alter caw
    #type: "FILE"
    #dev_attribs:
    #- dev_attrib: emulate_caw
    #  enable: 1

  lunSnapshotTemplate:
    is_locked: true
    # https://kb.synology.com/en-me/DSM/tutorial/What_is_file_system_consistent_snapshot
    is_app_consistent: true

  targetTemplate:
    auth_type: 0
    max_sessions: 0

```
