### ISSUE TITLE
PVC in pending status. 

### ISSUE THREAD

**Issue by vacquah** [democratic-csi/democratic-csi#388]
I installed the democratic csi  with helm via ArgoCD, where the app is health and synced. The storage backend is a truenas scale system (iscsi).  Volumes are created ok. But:

1. when i delete the PersistentVolumeClaim on the cluster, the PersistentVolume is not deleted on the truenas backend.  my reclaimpolicy is delete.
2. When i create a new pvc, it stays in pending status, though the volume is created. Never goes to Bound status.

my values file:

```
# special for talos
node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""

csiDriver:
  name: org.democratic-csi.iscsi

# add note here about volume expansion requirements
storageClasses:
  - name: truenas-iscsi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      # detachedVolumesFromSnapshots: false
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses:
- name: truenas-iscsi
  parameters:
    detachedSnapshots: true

driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: http
      host: 10.1.5.27
      port: 80
      apiKey: xxxxxxx
      allowInsecure: true
    zfs:
      "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      datasetParentName: fast-horses-01/k8s/iscsi/vols
      detachedSnapshotsDatasetParentName: fast-horses-01/k8s/iscsi/snaps
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "10.1.5.27:3260"
      targetPortals: [] 
      interface:
      nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: csi-
      # nameSuffix: "-cluster"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 8
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
```
