### ISSUE TITLE
Migrating parent dataset to a different pool in TrueNAS

### ISSUE THREAD

**Issue by shikharbhardwaj** [democratic-csi/democratic-csi#391]
Hello!

I am using democratic-csi to manage TrueNAS-backed PVs for my k8s cluster. Running 3 variants of the helm chart, one each for NFS, iSCSI and manual PVs. Everything has been pretty smooth so far, thanks for this excellent piece of software!

I now have the need to migrate the PVs onto a different pool, to expand available storage. I have begun the migration with the iSCSI PVs first. I replicated the existing datasets into the new pool and then updated the helm chart to point to the new parent dataset.

Attaching the helm chart values here (fields that I changed are marked as `UPDATED`:

<details>
<summary>Helm values.yaml</summary>

```
csiDriver:
  name: "org.democratic-csi.iscsi"

storageClasses:
- name: freenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4

volumeSnapshotClasses: []

driver:
  config:
    driver: freenas-api-iscsi
    instance_id: truenas
    httpConnection:
      protocol: https
      host: "{{ truenas_ip }}"
      port: 443
      apiKey: "{{ truenas_api_key }}"
      allowInsecure: true
    zfs:
      datasetParentName: main-pool/live/winnipeg/a/vols # --- UPDATED ---
      detachedSnapshotsDatasetParentName: main-pool/live/winnipeg/a/snaps # --- UPDATED ---
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 1000
      datasetPermissionsGroup: 1000
    iscsi:
      targetPortal: "{{ truenas_ip }}"

      namePrefix: csi-winnipeg-live- # --- UPDATED ---
      nameSuffix: "-clustera"

      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "7200"
      extentAvailThreshold: 0
```
</details>

After this, I restarted all democratic-csi pods and then restarted all statefulsets which mount these PVs. The pods came up successfully, but when I looked at the iSCSI shares in the TrueNAS GUI, I did not find new shares getting created for the new pool. It looks like the PVs are still using the old datasets. How can I get these PVs to use the new pool?

Thank you
