### ISSUE TITLE
[iscsi] setting targetPortal to be a bare IPv6 address no longer seems to work ENOTFOUND

### ISSUE THREAD

**Issue by growse** [democratic-csi/democratic-csi#393]
I've had democratic-csi running for ages against TrueNAS and have loved it. However, with the latest version of Kubernetes (1.30.0), it seems something is broken when setting the iscsi targetPortal to be a bare IPv6 address (e.g. `[2001:8b0:c8f:e8b0::2]:3260`)

The kubelets fail to mount PVs with the error:

``` 
 MountVolume.MountDevice failed for volume "pvc-1d25cdb0-ce2b-4b0e-b7c8-63a5add6de79" : rpc error: code = Internal desc = Error: getaddrinfo ENOTFOUND [2001:8b0:c8f:e8b0::2] Error: getaddrinfo ENOTFOUND [2001:8b0:c8f: │
│ 8b0::2[]
```

Looks like it's trying to treat the IP ad a DNS name, and failing. The big problem here is that it seems that the targetPortal attribute on the PV is immutable, so there doesn't seem to be any way to recover from this, as switching the portal address / name would involve a destroy  / recreate of PVs.

I'm installing democratic-csi via the helm chart, v0.14.6.

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/issues/353

Can you send over your configuration cleansed of any secrets?

**Comment by travisghansen** [comment]
Also send the logs from the node pod (csi-driver container) from the relevant cluster node.

**Comment by growse** [comment]
Sure!

Config:
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zfs-iscsi
  namespace: kube-util
spec:
  releaseName: zfs-iscsi
  targetNamespace: kube-util
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: kube-util
      version: "v0.14.6"
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    csiDriver:
      name: org.democratic-csi.iscsi
      # add note here about volume expansion requirements
    storageClasses:
      - name: freenas-iscsi-retain
        labels:
          com.growse.k8s.nut/scale-on-battery: "true"
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        parameters:
          fsType: ext4
      - name: freenas-iscsi-android-build
        labels:
          com.growse.k8s.nut/scale-on-battery: "true"
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        parameters:
          fsType: ext4
      - name: freenas-iscsi-android-build-gradle-home
        labels:
          com.growse.k8s.nut/scale-on-battery: "true"
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        parameters:
          fsType: ext4
      - name: freenas-iscsi
        labels:
          com.growse.k8s.nut/scale-on-battery: "true"
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        parameters:
          fsType: ext4
          # if true, volumes created from other snapshots will be
          # zfs send/received instead of zfs cloned
          # detachedVolumesFromSnapshots: "false"
          # if true, volumes created from other volumes will be
          # zfs send/received instead of zfs cloned
          # detachedVolumesFromVolumes: "false"
        mountOptions: [ ]
        secrets:
          provisioner-secret: null
          controller-publish-secret: null
          node-stage-secret: null
          node-publish-secret: null
          # if your cluster supports snapshots you may enable below
          controller-expand-secret: null
      - name: freenas-iscsi-xfs
        labels:
          com.growse.k8s.nut/scale-on-battery: "true"
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        # for block-based storage can be ext3, ext4, xfs
        # for nfs should be nfs
        parameters:
          fsType: xfs
          # if true, volumes created from other snapshots will be
          # zfs send/received instead of zfs cloned
          # detachedVolumesFromSnapshots: "false"
          # if true, volumes created from other volumes will be
          # zfs send/received instead of zfs cloned
          # detachedVolumesFromVolumes: "false"
        mountOptions: [ ]
    volumeSnapshotClasses: [ ]
    #- name: freenas-iscsi-csi
    #  parameters:
    #  # if true, snapshots will be created with zfs send/receive
    #  # detachedSnapshots: "false"
    #  secrets:
    #    snapshotter-secret:
    controller:
      driver:
        logLevel: info
      rbac:
        enabled: true
      replicaCount: 1
      enabled: true
      externalProvisioner:
        enabled: true
      externalResizer:
        enabled: true
      externalSnapshotter:
        enabled: false
    driver:
      config:
        driver: freenas-iscsi
        instance_id: null
        httpConnection:
          protocol: http
          host: storebot.mill.growse.com
          port: 80
          username: root
          allowInsecure: true
        sshConnection:
          host: storebot.mill.growse.com
          port: 22
          username: root
        zfs:
          datasetParentName: newtank/k8s
          detachedSnapshotsDatasetParentName: newtank/k8s-snaps
          datasetEnableQuotas: true
          datasetProperties:
            org.freenas:description: "{{ parameters.[csi.storage.k8s.io/pvc/namespace]}}/{{parameters.[csi.storage.k8s.io/pvc/name]}}"
            # "" (inherit), lz4, gzip-9, etc
            # "" (inherit), on, off, verify
          zvolCompression: null
          zvolDedup: null
          zvolEnableReservation: false
          # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
          zvolBlocksize: null
        iscsi:
          targetPortal: "[2001:8b0:c8f:e8b0::2]:3260"
          targetPortals: [ ]
          # leave empty to omit usage of -I with iscsiadm
          interface: null
          nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          namePrefix: ""
          nameSuffix: ""
          # add as many as needed
          # get the correct ID from the "portal" section in the UI
          targetGroups:
            - targetGroupPortalGroup: 1
              # get the correct ID from the "initiators" section in the UI
              targetGroupInitiatorGroup: 1
              # None, CHAP, or CHAP Mutual
              targetGroupAuthType: None
              # get the correct ID from the "Authorized Access" section of the UI
              # only required if using Chap
              targetGroupAuthGroup: null
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 512
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: SSD
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0
  valuesFrom:
    - kind: Secret
      name: democratic-csi-secrets
      targetPath: driver.config.httpConnection.apiKey
      valuesKey: apiKey
    - kind: Secret
      name: democratic-csi-secrets
      targetPath: driver.config.sshConnection.privateKey
      valuesKey: privateKey
```

csi-driver logs (this is repeated:

```

2024-5-06T21:35:09.334324644Z {"host":"dodgybot","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"path\":\"/csi.v1.Node/NodeGetCapabilities\",\"metadata\":{},\"request\":{},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.333Z"}                                                                                                                                                                       
2024-5-06T21:35:09.334409463Z {"host":"dodgybot","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.334Z"}                                                                                                                                         
2024-5-06T21:35:09.342592714Z {"host":"dodgybot","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"path\":\"/csi.v1.Node/NodeGetCapabilities\",\"metadata\":{},\"request\":{},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.342Z"}                                                                                                                                                                       
2024-5-06T21:35:09.342676656Z {"host":"dodgybot","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.342Z"}                                                                                                                                         
2024-5-06T21:35:09.344262136Z {"host":"dodgybot","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeGetCapabilities call: {\"path\":\"/csi.v1.Node/NodeGetCapabilities\",\"metadata\":{},\"request\":{},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.344Z"}                                                                                                                                                                       
2024-5-06T21:35:09.344347152Z {"host":"dodgybot","level":"info","message":"new response - driver: FreeNASSshDriver method: NodeGetCapabilities response: {\"capabilities\":[{\"rpc\":{\"type\":\"STAGE_UNSTAGE_VOLUME\"}},{\"rpc\":{\"type\":\"GET_VOLUME_STATS\"}},{\"rpc\":{\"type\":\"EXPAND_VOLUME\"}},{\"rpc\":{\"type\":\"SINGLE_NODE_MULTI_WRITER\"}}]}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.344Z"}                                                                                                                                         
2024-5-06T21:35:09.346017164Z {"host":"dodgybot","level":"info","message":"new request - driver: FreeNASSshDriver method: NodeStageVolume call: {\"path\":\"/csi.v1.Node/NodeStageVolume\",\"metadata\":{},\"request\":{\"publish_context\":{},\"secrets\":\"redacted\",\"volume_context\":{\"interface\":\"\",\"iqn\":\"iqn.2005-10.org.freenas.ctl:default-lockup-data\",\"lun\":\"0\",\"node_attach_driver\":\"iscsi\",\"portal\":\"[2001:8b0:c8f:e8b0::2]:3260\",\"portals\":\"\",\"provisioner_driver\":\"freenas-iscsi\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1698388361470-8081-org.democratic-csi.iscsi\"},\"volume_id\":\"pvc-96b70c55-2e21-4fb0-9a5a-0ffce72b4903\",\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.iscsi/f75b787cbad0eef9e4d7e4e7f678faadf4feca408884cbbf0664ee08d7d3d2c7/globalmount\",\"volume_capability\":{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"ext4\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.345Z"}                                                                                                                                                                                                       
2024-5-06T21:35:09.346303560Z executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:default-lockup-data -p [2001:8b0:c8f:e8b0::2]:3260 -o new                                                                                                                     
2024-5-06T21:35:09.355733788Z executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:default-lockup-data -p [2001:8b0:c8f:e8b0::2]:3260 -o update --name node.startup --value manual                                                                               
2024-5-06T21:35:09.374937360Z executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:default-lockup-data -p [2001:8b0:c8f:e8b0::2]:3260 -l                                                                                                                         
2024-5-06T21:35:09.395157121Z executing iscsi command: iscsiadm -m session                                                                                                                                                                                                           
2024-5-06T21:35:09.406494637Z {"host":"dodgybot","level":"error","message":"handler error - driver: FreeNASSshDriver method: NodeStageVolume error: Error: getaddrinfo ENOTFOUND [2001:8b0:c8f:e8b0::2] Error: getaddrinfo ENOTFOUND [2001:8b0:c8f:e8b0::2]\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.406Z"}                                                                                                                                                                      
2024-5-06T21:35:09.560682709Z {"host":"dodgybot","level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"path\":\"/csi.v1.Identity/Probe\",\"metadata\":{},\"request\":{},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.560Z"}                                                                                                                                                                                               
2024-5-06T21:35:09.560721105Z {"host":"dodgybot","level":"info","message":"new response - driver: FreeNASSshDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi","timestamp":"2024-5-06T21:35:09.560Z"}
```

Nodes are debian stable with open-iscsi 2.1.8-1. Log seems to indicate that it's `iscsiadm` that's not parsing the portal address properly, but running that command manually doesn't generate an "ENOTFOUND". if I list the current sessions, I can see some that are a mix of the DNS name (presumably mounted since I updated the config to change `targetPortal` to the DNS name), and some still on the IP address. open-iscsi doesn't seem to have a problem with the bare IP address?

```
$ iscsiadm -m session
...
tcp: [3] [2001:8b0:c8f:e8b0::2]:3260,1 iqn.2005-10.org.freenas.ctl:monitoring-restic-cache-iscsi-claim (non-flash)
tcp: [4] storebot.mill.growse.com:3260,1 iqn.2005-10.org.freenas.ctl:default-aptcacher-iscsi-claim (non-flash)
```
