### ISSUE TITLE
[freenas-iscsi] Square brackets around port preventing session creation.

### ISSUE THREAD

**Issue by gaigelama** [democratic-csi/democratic-csi#398]
I'm using Ubuntu 22.04 LTS with iscsi and iscsid installed. Running the latest version of TrueNAS.

Kubernetes v1.28.6, with the latest democratic-csi and snapshot-controller helm charts.

The democratic-csi cannot create a session running the following the command.

`iscsiadmin -m -T iqn.***:csi-pvc-*** -p 10.99.101.253[:3260] -l`

I also try running it on the k8s node directly as a test and it still doesn't work.

However, when I remove the square brackets around the port it works just fine.
`iscsiadmin -m -T iqn.***:csi-pvc-*** -p 10.99.101.253:3260 -l`

It also works if I omit the port and it let it choose the default port itself.

I tried removing the square brackets in the helm chart and I see the change reflect in the k8s secret but it seems democratic-csi forces it to use square brackets regardless.

I can't find anything on how to fix this at any level.

**Comment by gaigelama** [comment]
I also don't see ip[:port] used at all with open-iscsi. https://github.com/open-iscsi/open-iscsi

**Comment by travisghansen** [comment]
Can you share your config? Those brackets in the examples are not meant to be literal but rather indicate the port is optional.

**Comment by gaigelama** [comment]
Here's the `driver-config-file.yaml` stored in the k8s secret `democratic-csi-iscsi-driver-config`

```
driver: freenas-iscsi
httpConnection:
  allowInsecure: true
  host: 10.31.4.5
  password: ****
  port: 443
  protocol: https
  username: root
iscsi:
  extentAvailThreshold: 0
  extentBlocksize: 512
  extentDisablePhysicalBlocksize: true
  extentInsecureTpc: true
  extentRpm: SSD
  extentXenCompat: false
  namePrefix: csi-
  nameSuffix: -tst-cluster-01
  targetGroups:
  - targetGroupAuthType: None
    targetGroupInitiatorGroup: 4
    targetGroupPortalGroup: 1
  targetPortal: 10.99.101.253
sshConnection:
  host: 10.31.4.5
  password: ****
  port: 22
  username: root
zfs:
  datasetParentName: tank/k8s/tst-cluster-01/tst-cluster-01-iscsi
  detachedSnapshotsDatasetParentName: tank/k8s/tst-cluster-01/tst-cluster-01-iscsi-snapshots
  zvolBlocksize: 16k
  zvolCompression: lz4
  zvolDedup: false
  zvolEnableReservation: false
```

And here's some lines from one of the democratic-csi-iscsi-node pods (csi-driver container).

```
retry - waiting 2000ms before trying again
executing iscsi command: iscsiadm -m node -T iqn.2024-03.org.truenas.ctl:csi-pvc-3a257791-67b5-4216-b97c-0ffd41370b11-tst-cluster-01 -p 10.99.101.253[:3260] -l
retry - waiting 2000ms before trying again
executing iscsi command: iscsiadm -m node -T iqn.2024-03.org.truenas.ctl:csi-pvc-3a257791-67b5-4216-b97c-0ffd41370b11-tst-cluster-01 -p 10.99.101.253[:3260] -l
{"host":"worker-node-03","level":"error","message":"handler error - driver: FreeNASSshDriver method: NodeStageVolume error: {\"code\":4,\"stdout\":\"Logging in to [iface: default, target: iqn.2024-03.org.truenas.ctl:csi-pvc-3a257791-67b5-4216-b97c-0ffd41370b11-tst-cluster-01, portal: 10.99.101.253[,3260]\\n\",\"stderr\":\"iscsiadm: Could not login to [iface: default, target: iqn.2024-03.org.truenas.ctl:csi-pvc-3a257791-67b5-4216-b97c-0ffd41370b11-tst-cluster-01, portal: 10.99.101.253[,3260].\\niscsiadm: initiator reported error (4 - encountered connection failure)\\niscsiadm: Could not log into all portals\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2024-05-10T18:28:13.201Z"}
```

**Comment by gaigelama** [comment]
I found that target portal is also stored in the PVC. It included the original mistake of me using square brackets. So any changes to the config afterwards weren't picked up because it gets that info from the PVC instead.

Thanks for responding though!

My only thought would be is to revert the example back to

`ip:port` instead of `ip[:port]` but it seems like I'm only one who has made that mistake lol.

Maybe add a comment above

```
...
iscsi:
  # port is optional
  targetPortal: "server:port"
  # for multipath
  targetPortals: [] # [ "server:port", "server:port", ... ]
...
```
