### ISSUE TITLE
Allow injecting environment variables into the driver config

### ISSUE THREAD

**Issue by LiquidPL** [democratic-csi/democratic-csi#400]
I'm trying to deploy democratic-csi using ArgoCD and sealed-secrets, and I'd like to avoid having to seal the entire driver config as a secret. I was wondering if it could be possible to somehow inject values from the environment variables into the config, for example:

```
driver:
  config:
    driver: freenas-api-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 10.0.0.1
      port: 80
      apiKey: '{{ env "TRUENAS_API_KEY" }}' # or any other sort of marker that would be picked up by the driver
```

The value of the `apiKey` field would then be replaced with the api key pulled from the env vars.
