### ISSUE TITLE
Understanding the node-manual

### ISSUE THREAD

**Issue by colegatron** [democratic-csi/democratic-csi#409]
Sorry, but maybe I am missing something with the node-manual for pre existing nfs shares.
There should be some reason and I would like to know.

What is the reason for it to exist if it is natively supported by kubernetes like in the example below?
Thanks
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-images
spec:
  storageClassName: manual-no-need-to-exist
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 110.0.10.44
    path: /mnt/image-properties
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-images-claim
spec:
  storageClassName: manual-no-need-to-exist
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-images
```
