### ISSUE TITLE
TrueNAS Scale 24.10 - Controller Errors on Startup

### ISSUE THREAD

**Issue by Shackelford-Arden** [democratic-csi/democratic-csi#427]
Just upgrade to TrueNAS Scale 24.10 and noticed that the CSI controller is failing.

Looks like it is making calls to `api/v1.0/system/version/`, which appears to have been removed, though I haven't been able to find (yet) where they've documented the removal of the v1.0 API.

Wanted to report this now, I may try and take a peek at what might need to be done to fix this.

Here are the logs from the controller:

```
grpc implementation: @grpc/grpc-js
{"host":"5eb41d085111","level":"info","message":"initializing csi driver: freenas-api-nfs","service":"democratic-csi","timestamp":"2024-11-04T04:01:49.999Z"}
{"host":"5eb41d085111","level":"debug","message":"setting default identity service caps","service":"democratic-csi","timestamp":"2024-11-04T04:01:50.379Z"}
{"host":"5eb41d085111","level":"debug","message":"setting default identity volume_expansion caps","service":"democratic-csi","timestamp":"2024-11-04T04:01:50.379Z"}
{"host":"5eb41d085111","level":"debug","message":"setting default controller caps","service":"democratic-csi","timestamp":"2024-11-04T04:01:50.380Z"}
{"host":"5eb41d085111","level":"debug","message":"setting default node caps","service":"democratic-csi","timestamp":"2024-11-04T04:01:50.382Z"}
{"host":"5eb41d085111","level":"info","message":"starting csi server - node version: v20.11.1, package version: 1.9.0, config file: /local/driver-config-file.yaml, csi-name: org.democratic-csi.nfs, csi-driver: freenas-api-nfs, csi-mode: controller, csi-version: 1.9.0, address: , socket: unix:///csi/csi.sock","service":"democratic-csi","timestamp":"2024-11-04T04:01:50.383Z"}
{"host":"5eb41d085111","level":"info","message":"new request - driver: FreeNASApiDriver method: Probe call: {\"path\":\"/csi.v1.Identity/Probe\",\"metadata\":{},\"request\":{},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.782Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP REQUEST DETAILS: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":5000,\"method\":\"GET\",\"url\":\"https://<redacted>/api/v2.0/system/version/\",\"params\":null}","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.860Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP REQUEST DURATION: 0.06s","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.860Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.860Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP RESPONSE STATUS CODE: 401","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.860Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP RESPONSE HEADERS: {\"server\":\"nginx\",\"date\":\"Mon, 04 Nov 2024 04:01:59 GMT\",\"content-type\":\"text/plain; charset=utf-8\",\"content-length\":\"15\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=63072000; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.860Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP RESPONSE BODY: \"Invalid API key\"","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.860Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP REQUEST DETAILS: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":5000,\"method\":\"GET\",\"url\":\"https://<redacted>/api/v1.0/system/version/\",\"params\":null}","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.873Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP REQUEST DURATION: 0.01s","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.873Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.873Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP RESPONSE STATUS CODE: 200","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.873Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP RESPONSE HEADERS: {\"server\":\"nginx\",\"date\":\"Mon, 04 Nov 2024 04:01:59 GMT\",\"content-type\":\"text/html\",\"last-modified\":\"Mon, 28 Oct 2024 20:29:36 GMT\",\"transfer-encoding\":\"chunked\",\"connection\":\"keep-alive\",\"etag\":\"W/\\\"671ff430-127b5\\\"\",\"cache-control\":\"no-store, no-cache, must-revalidate, max-age=0\",\"expires\":\"0\",\"strict-transport-security\":\"max-age=63072000; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.873Z"}
{"host":"5eb41d085111","level":"debug","message":"FREENAS HTTP RESPONSE BODY: \"<!doctype html>\\n<html> ...redacted for brevity... </html>\\\\n\\\"}}}\"}","service":"democratic-csi","timestamp":"2024-11-04T04:01:59.876Z"}
...
<duplicate entries>
...
running server shutdown, exit code: 15 (SIGTERM)
grpc server gracefully closed all connections
server fully shutdown, exiting

```

Calling the V2 endpoint with the same token works, just seems to be the call to V1 that fails and breaks the startup.

**Comment by Shackelford-Arden** [comment]
Oh, and in my config, I've been specifying V2, so I'm not entirely sure why v1 is still being called?

I don't believe it to be applicable in this case, but I am using this in Nomad.

```
driver: freenas-api-nfs
instance_id:
httpConnection:
  apiVersion: 2
  protocol: https
{{ with nomadVar "nomad/jobs/csi-controller" }}
  host: "{{ .HOST }}"
  port: 443
  apiKey: "{{ .CSI_API_KEY }}"
zfs:
  datasetParentName: virtual-storage/nomad-apps/vols
  detachedSnapshotsDatasetParentName: virtual-storage/nomad-apps/snapshots
  datasetEnableQuotas: false
  datasetEnableReservation: false
  datasetPermissionsMode: "0770"
  datasetPermissionsUser: 0
  datasetPermissionsGroup: 0
nfs:
  shareHost: "{{ .HOST }}"
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks: []
  shareMaprootUser: root
  shareMaprootGroup: root
  shareMapallUser: ""
  shareMapallGroup: ""
{{ end }}
```
