### ISSUE TITLE
[BUG] NFS Volume Creation from Snapshot fails with "Disk quota exceeded" error

### ISSUE THREAD

**Issue by thekoma** [democratic-csi/democratic-csi#441]
# [BUG] NFS Volume Creation from Snapshot fails with "Disk quota exceeded" error

## Environment
- Kubernetes version: v1.30.6+k3s1 (K3s)
- democratic-csi version: 0.14.7 (Chart version)
- Storage backend: ZFS (NFS)
- Snapshot Controller version: 0.2.4 (Chart version 6.2.2)

## Description
When attempting to create a new volume from a snapshot using democratic-csi NFS provider, the operation fails with a "Disk quota exceeded" error while setting permissions on the dataset. This is unexpected as no quotas are explicitly set on the ZFS backend, and all volumes are managed exclusively through democratic-csi.

The issue occurs specifically with NFS volumes, while the iSCSI configuration works correctly with the same setup.

### democratic-csi Installation (Helmfile)
```yaml
releases:
- name: democratic-csi-snapshot-controller
  namespace: democratic-csi
  chart: democratic-csi/snapshot-controller
  values:
    - controller:
        enabled: true
        rbac:
          enabled: true
        replicaCount: 1

- name: democratic-csi-nfs
  namespace: democratic-csi
  chart: democratic-csi/democratic-csi
  values:
  - csi-nfs-values.yaml
  needs:
    - democratic-csi-snapshot-controller
```

### NFS Provider Configuration
```yaml
csiDriver:
  fsGroupPolicy: File
  name: org.democratic-csi.nfs
driver:
  config:
    driver: zfs-generic-nfs
    sshConnection:
      host: <REDACTED_IP>
      port: 22
      username: csi
      privateKey: |
        <REDACTED_PRIVATE_KEY>
    zfs:
      cli:
        sudoEnabled: true
        paths:
          zfs: /usr/bin/zfs
          zpool: /usr/bin/zpool
          sudo: /usr/bin/sudo
          chroot: /usr/bin/chroot

      datasetParentName: data/csi-test/nfs
      detachedSnapshotsDatasetParentName: data/csi-test/nfs-snapshots

      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareStrategy: "setDatasetProperties"
      shareStrategySetDatasetProperties:
        properties:
          sharenfs: "on"
      shareHost: <REDACTED_IP>

storageClasses:
- allowVolumeExpansion: true
  defaultClass: false
  mountOptions:
  - noatime
  - nfsvers=3
  name: zfs-generic-nfs-csi-delete
  parameters:
    fsType: nfs
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
- allowVolumeExpansion: true
  defaultClass: false
  mountOptions:
  - noatime
  - nfsvers=3
  name: zfs-generic-nfs-csi-retain
  parameters:
    fsType: nfs
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
volumeSnapshotClasses:
- name: zfs-generic-nfs-csi
```

### Test Application
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-test
  annotations:
    k8up.io/backup-volume: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: zfs-generic-nfs-csi-delete
```

### VolSync Configuration
```yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: test-pvc-nfs-test
  namespace: test
spec:
  sourcePVC: test-pvc-nfs-test
  trigger:
    schedule: "*/5 * * * *"
  restic:
    repository: restic-config-nfs
    retain:
      hourly: 24
      daily: 7
      weekly: 4
      monthly: 2
    pruneIntervalDays: 7
    copyMethod: Snapshot
    volumeSnapshotClassName: zfs-generic-nfs-csi
```

## Error Log
```json
{
  "host": "democratic-csi-nfs-controller-6fbb9cc786-pthnk",
  "level": "error",
  "message": "handler error - driver: ControllerZfsGenericDriver method: CreateVolume error: {\"name\":\"GrpcError\",\"code\":2,\"message\":\"error setting permissions on dataset: {\\\"stderr\\\":\\\"chmod: changing permissions of '/data/csi-test/nfs/pvc-b639d1b5-a253-475e-a1b5-9a27f00024fd': Disk quota exceeded\\\\n\\\",\\\"code\\\":1}\"}",
  "service": "democratic-csi",
  "timestamp": "2024-12-27T00:02:32.524Z"
}
```

## Expected Behavior
The volume should be created successfully from the snapshot, as it works with the iSCSI configuration.

## Actual Behavior
The volume creation fails with a "Disk quota exceeded" error during the permission setting phase, despite no quotas being explicitly configured on the ZFS backend.

## Additional Context
- Both NFS and iSCSI configurations are deployed in the same cluster
- iSCSI volumes work correctly with snapshots
- The error occurs specifically during the chmod operation after volume creation
- All volumes are managed exclusively through democratic-csi
- No explicit ZFS quotas are configured on the backend

## Steps to Reproduce
1. Deploy democratic-csi with the provided configuration
2. Create a PVC using the NFS storage class
3. Create a snapshot using VolSync
4. Attempt to restore/create a new volume from the snapshot

## Questions
1. Is this a known issue with NFS volumes and snapshots?
2. Are there any specific ZFS dataset properties that need to be set for NFS volumes when working with snapshots?
3. Why does the chmod operation fail with a quota error when no quotas are explicitly set?

## Current State
```bash
$ kubectl get pvc
NAME                                STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                   AGE
test-pvc-nfs-test                   Bound     pvc-c667ec92-5b10-4fa6-8119-2d9f81099537   2Gi        RWO            zfs-generic-nfs-csi-delete     9d
volsync-test-pvc-nfs-test-src       Pending                                                                        zfs-generic-nfs-csi-delete     24m

$ kubectl get volumesnapshotcontent.snapshot.storage.k8s.io
NAME                                               READYTOUSE   RESTORESIZE   DELETIONPOLICY   DRIVER                   VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                  AGE
snapcontent-5f54eb28-7cb1-4d16-9a04-3b9773e548b4   true         142848        Delete           org.democratic-csi.nfs   zfs-generic-nfs-csi   volsync-test-pvc-nfs-test-src   24m

$ kubectl get volumesnapshot
NAME                            READYTOUSE   SOURCEPVC           RESTORESIZE   SNAPSHOTCLASS         SNAPSHOTCONTENT                                    AGE
volsync-test-pvc-nfs-test-src   true         test-pvc-nfs-test   142848        zfs-generic-nfs-csi   snapcontent-5f54eb28-7cb1-4d16-9a04-3b9773e548b4   24m
```
