### ISSUE TITLE
TrueNAS API Key passing as "Object" instead of String

### ISSUE THREAD

**Issue by ndrwstn** [democratic-csi/democratic-csi#442]
Good afternoon,

I am having a perplexing problem with `democratic-csi-iscsi` where the `-controller`'s `csi-driver` is not sending the API key as a string but instead as an object (`"Authorization\\\":\\\"Bearer [object Object]\\\"`). This is causing the service to fail.

I am using external-secrets (via onepassword-connect), but have also tried to create a Secret directly without success. I also attempted to have the HelmRelease create environmental variables and reference those, but again no joy. 

However, if I hardcode the API key, the Helm Release comes up successfully. That said, with the API hardcoded, the driver still isn't able to create or mount any storage for me, whether I hardcode CHAP or use a secret, so it may still be a local problem. 

Finally, I did verify that my credentials and networking is good. First, the API works inside the container (both hardcoded and if I install `curl` and passing the credential manually).

My (santized) HelmRelease is below. The commented lines are both the main alternate config I've tried---and what I believe should be corrrect.
```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csiDriver:
      name: org.democratic-csi.iscsi
    driver:
      config:
        driver: freenas-api-iscsi
        instance_id: democratic-csi-truenas-iscsi
        httpConnection:
          protocol: https
          host: nietzsche.impetuo.us
          port: 443
          apiKey: <key>
            # valueFrom:
            #   secretKeyRef:
            #     name: democratic-csi
            #     key: truenas_api_key
          allowInsecure: true
          allowRedirects: true
          apiVersion: 2
        zfs:
          datasetParentName: <tank>/<set>/dynamic/iscsi
          detachedSnapshotsDatasetParentName: <tank>/<set>/snapshots/iscsi
          zvolBlocksize: "16K"
          zvolCompression: "lz4"
          zvolDedup: "off"
          zvolEnableReservation: true
        iscsi:
          targetPortal: "<fqdn>:3260"
          interface: defaultroute
          namePrefix: "dcsi-"
          nameSuffix: "-vol"
          extentInsecure: false
          extentBlocksize: 512
          extentDisablePhysicalBlocksize: false
          extentRpm: "5400"
          chapUsername: '<user>'
            # valueFrom:
            #   secretKeyRef:
            #     name: democratic-csi
            #     key: iscsi_username
          chapPassword: '<pass>'
            # valueFrom:
            #   secretKeyRef:
            #     name: democratic-csi
            #     key: iscsi_password
          chapUsernameIn: '<peer_user>'
            # valueFrom:
            #   secretKeyRef:
            #     name: democratic-csi
            #     key: iscsi_username_in
          chapPasswordIn: '<peer_pass>'
            # valueFrom:
            #   secretKeyRef:
            #     name: democratic-csi
            #     key: iscsi_password_in
          targetGroups:
            - targetGroupPortalGroup: 1
              targetGroupInitiatorGroup: 3
              targetGroupAuthType: CHAP
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
    storageClasses:
        - name: democratic-iscsi
          defaultClass: false
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
          parameters:
            fstype: ext4
            readwriteonce: "true"
          mountOptions:
            - discard
            - _netdev
          labels:
            storage.k8s.io/type: block
        - name: democratic-iscsi-retain
          defaultClass: false
          reclaimPolicy: Retain
          volumeBindingMode: WaitForFirstConsumer
          allowVolumeExpansion: true
          parameters:
            fstype: ext4
            readwriteonce: "true"
          mountOptions:
            - discard
            - _netdev
          labels:
            storage.k8s.io/type: block
```

I've attached the relevant [log](https://github.com/user-attachments/files/18308120/sanitized.log) line with the error. I'm self-hosting Talos 1.9.1 on top of Proxmox 8.1.3 with TrueNAS SCALE 24.10.01. Let me know what other information might be helpful? Thanks.
