### ISSUE TITLE
TrueNAS iSCSi Naming

### ISSUE THREAD

**Issue by ssyounger** [democratic-csi/democratic-csi#447]
Is there a way to not use the generic UUID generation and instead use a custom naming convention?

Current example. 
`NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                          STORAGECLASS           VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-33363756-e07a-414e-83ce-f066b8987150   1Gi        RWO            Retain           Bound    recipes/test-pvc                               truenas-iscsi-retain   <unset>                          10m`

I see there is a configuration section within the values file that possibly addresses this but after making a change it still uses the UUID. 

values.yaml
`    zfs:
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"`

With the above I'm trying to get the naming convention to be something like:
`<namePrefix>-{namespace}-{pv-name}-<nameSuffix>`

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-iscsi.yaml#L73

**Comment by lrybak** [comment]
Found that thread while trying to figure out how to template the names.
I'm using that configuration:
```
    iscsi:
      targetPortal: [trunas:3260]
      targetPortals: []
      interface:
      nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      namePrefix: myprefix-
      nameSuffix: "-mysuffix"
```
but still UUID is used instead of provided template. The behaviour is the same for both freenas-iscsi and freenas-api-iscsi.
Any hints?
