### ISSUE TITLE
Stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by Julusian** [democratic-csi/democratic-csi#45]
I found that democratic-csi is stuck in CrashLoopBackOff in my cluster (1.18.12), with no obvious error.
I don't know when it stopped working, I noticed the error today when a pod using an isci volume got stuck terminating

I tried upgrading the helm chart, with no change.

Is there a way I can downgrade? It looks like the helm chart will always pull the latest tag (and there arent any version tags on dockerhub), so I don't see how I can pin to an old version without already knowing an image hash.
As a side note, is using the latest tag in helm charts a good idea? I would prefer democratic-csi to not update to a newer whenever it gets restarted/crashes. Any required changes in config or environment will cause random breakages like I am seeing

The relevant snippet from `kubectl describe pod`
```
  csi-driver:
    Container ID:  docker://eac1fe001cf9926504516c3da64ee13fb68c979e8012330b1b29378bd95189c8
    Image:         democraticcsi/democratic-csi:latest
    Image ID:      docker-pullable://democraticcsi/democratic-csi@sha256:c3644a41532f73cf14b4d5d0bb6ef5cb59b059245d10a8060bcd8a1220548f0c
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-version=1.2.0
      --csi-name=uk.julus.iscsi-beta
      --driver-config-file=/config/driver-config-file.yaml
      --log-level=info
      --csi-mode=controller
      --server-socket=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    139
      Started:      Mon, 04 Jan 2021 10:20:08 +0000
      Finished:     Mon, 04 Jan 2021 10:20:09 +0000
    Ready:          False
    Restart Count:  4
    Liveness:       exec [bin/liveness-probe --csi-version=1.2.0 --csi-address=/csi-data/csi.sock] delay=10s timeout=3s period=60s #success=1 #failure=5
    Environment:    <none>
    Mounts:
      /config from config (rw)
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from freenas-iscsi-democratic-csi-controller-sa-token-vfp2t (ro)
```

If I look at the logs on that container, I don't get presented with anything.

My config:
```
csiDriver:
  # should be globally unique for a given cluster
  name: "uk.julus.iscsi-beta"

# add note here about volume expansion requirements
storageClasses:
- name: iscsi-beta
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
      
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"
    
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-iscsi-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: http
      host: "10.42.5.5"
      port: 80
      username: root
      password: 
      allowInsecure: true
    sshConnection:
      host: "10.42.5.5"
      port: 22
      username: root
      # use either password or key
      # password: 
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        
        -----END OPENSSH PRIVATE KEY-----

    zfs:

      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less
      datasetParentName: beta/k8s/iscsi
      detachedSnapshotsDatasetParentName: beta/k8s/iscsi-snaps
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression:
      # "" (inherit), on, off, verify
      zvolDedup:
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:
    iscsi:
      targetPortal: "10.42.5.5:3260"
      targetPortals: []
      # leave empty to omit usage of -I with iscsiadm
      interface:
      namePrefix: csi-
      nameSuffix: "-k8s"
      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 512
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
```
