### ISSUE TITLE
democratic-csi synology scsi chap not working as expected

### ISSUE THREAD

**Issue by akrauze** [democratic-csi/democratic-csi#457]
First of all I want to state I really appreciate all the work done here by the Author and all Contributors. On my use case it is clearly a huge improvement on the shameful csi that Synology is delivering. 

This might very well be user error, but seems things are not working as documented.

After finding out the limitations of synology-csi I dediced to give a try to democratic-csi and I have been trying to setup it up for the last few days.
My requirement is  PVC provisioning with some sort fo security and a filesystem that supports linux permissions. The later excluder smb and the NFS support synology-csi provides is laughable. 
So, I ended up with democratic-csi trying to setup iscsi with chap authnetication (I know chap is no longer considered secure, but it does fullfil the requreiment). 

Once I setup democratic-csi it was setting up iscsi targets without chap authentication. I did some tinkering (probably wrong) and got the provisioning part working, but still cant mount the volumes.

Here is my original ``values yaml``:
```yaml
csiDriver:
  name: org.democratic-csi.iscsi-synology

controller:
  externalResizer:
    enabled: true

  externalSnapshotter:
    enabled: true

driver:
  config:
    driver: synology-iscsi
    httpConnection:
      protocol: https
      host: ********************
      port: 5001
      username: **********
      password: **********
      allowInsecure: false
      session: "democratic-csi"
      serialize: true

    iscsi:
      targetPortal: "********************:3260"
      targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
      baseiqn: "iqn.2000-01.com.synology:csi."
      targetGroups:

      namePrefix: "dk8s-"
      nameSuffix: ""
      lunTemplate:
        type: "BLUN"
      lunSnapshotTemplate:
        is_locked: true
        is_app_consistent: true

      targetTemplate:
        auth_type: 0
        max_sessions: 0

    synology:
      volume: /volume1

controller:
  externalResizer:
    enabled: true

  externalSnapshotter:
    enabled: true

storageClasses:
- name: democratic-iscsi-retain-chap
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
    lunTemplate: |
      type: BLUN
      description: LUN for k8s
  secrets:
    provisioner-secret:
      user: **********
      password: **********
      mutualUser: **********
      mutualPassword: **********
- name: democratic-iscsi-delete-chap
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
    lunTemplate: |
      type: BLUN
      description: LUN for k8s
  secrets:
    provisioner-secret:
      user: **********
      password: **********
      mutualUser: **********
      mutualPassword: **********

volumeSnapshotClasses:
- name: democratic-iscsi
  parameters:
  secrets:
    snapshotter-secret:
      user: **********
      password: **********
      mutualUser: **********
      mutualPassword: **********
```

The above just didn't work as expected. It did created the LUNs and Targets, but there was no CHAP. The ``democratic-csi-controller`` clearly showed the ``auth_type`` as ``0`` (well kind of what the config says to use, but same as the docs) and no CHAP/MutualCHAP secrets were sent to the NAS (``chap`` and ``mutual_chap``) were set to true.

```
SYNOLOGY HTTP REQUEST: {"method":"GET","url":"https://********************:5001/webapi/entry.cgi","headers":{"Accept":"application/json","User-Agent":"democratic-csi","Content-Type":"application/json"},"responseType":"json","timeout":60000,"params":{"auth_type":0,"chap":"true","max_sessions":0,"mutual_chap":"true","name":"dk8s-pvc-6f524c89-a18d-4347-af16-6dc50a80981a","iqn":"iqn.2000-01.com.synology:csi.dk8s-pvc-6f524c89-a18d-4347-af16-6dc50a80981a","api":"SYNO.Core.ISCSI.Target","version":"1","method":"create","_sid":"redacted"}}
```
I did try with different values for ``auth_type`` based on what I was seeing the Synology UI doing, but had only failures.

After some tinkering aby addind the lines below I got LUNs and Targets created with CHAP and Mutual CHAP, but volumes cannot be mounted.

```yaml
      targetTemplate:
        auth_type: 2
        max_sessions: 0
        chap: true
        mutual_chap: true
        user: **********
        password: **********
        mutual_user: **********
        mutual_password: **********
```

With his the ``csi-driver`` can successifully provision the LUN adn Target and on my NAS I can see CHAp and Mutual CHAP are enabled. But the volume cannot by mounted on the pod. 
The ``ds`` longs on the node where that pod is runnigns shows:
```
executing iscsi command: iscsiadm -m node -T iqn.2000-01.com.synology:csi.dk8s-pvc-8b40b08f-c946-401a-820d-c9115ee4d8e0 -p ********************:3260 -l
{"host":"ser7b","level":"error","message":"handler error - driver: ControllerSynologyDriver method: NodeStageVolume error: {\"code\":24,\"stdout\":\"Logging in to [iface: default, target: iqn.2000-01.com.synology:csi.dk8s-pvc-8b40b08f-c946-401a-820d-c9115ee4d8e0, portal: ********************,3260]\\n\",\"stderr\":\"iscsiadm: Could not login to [iface: default, target: iqn.2000-01.com.synology:csi.dk8s-pvc-8b40b08f-c946-401a-820d-c9115ee4d8e0, portal: ********************,3260].\\niscsiadm: initiator reported error (24 - iSCSI login failed due to authorization failure)\\niscsiadm: Could not log into all portals\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2025-02-28T23:00:54.414Z"}
executing iscsi command: iscsiadm -m node -T iqn.2000-01.com.synology:csi.dk8s-pvc-f628be82-5182-43bd-ad63-e8b18121f413 -p ********************:3260 -l
```

This i how my StorageClass looks like
```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    meta.helm.sh/release-name: synology-isci
    meta.helm.sh/release-namespace: democratic-csi
  creationTimestamp: "2025-02-27T21:43:24Z"
  labels:
    app.kubernetes.io/instance: synology-isci
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.14.7
  name: democratic-iscsi-delete-chap
  resourceVersion: "677998869"
  uid: d451f6ec-e909-42ec-bf37-d2f017827711
parameters:
  csi.storage.k8s.io/provisioner-secret-name: provisioner-secret-democratic-iscsi-delete-chap-synology-isci-d
  csi.storage.k8s.io/provisioner-secret-namespace: democratic-csi
  fsType: ext4
  lunTemplate: |
    type: BLUN
    description: LUN for ${pvc.name}
provisioner: org.democratic-csi.iscsi-synology
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

and hre is the Secret 
```yaml
apiVersion: v1
data:
  mutualPassword: **************
  mutualUser: **************
  password: **************
  user: **************
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: synology-isci
    meta.helm.sh/release-namespace: democratic-csi
  creationTimestamp: "2025-02-27T21:43:24Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: provisioner-secret-democratic-iscsi-delete-chap-synology-isci-d
  namespace: democratic-csi
  resourceVersion: "677998861"
  uid: 4eb309c3-35ec-4efa-bdd9-3b529125b005
typ
e: Opaque
```

Am I missing something or is it really not working as it should?

**Comment by akrauze** [comment]
So I just realized CHAP and Mutual CHAP requires some of the config to be duplicated.
Once I added the following to my ``values.yaml`` everything started working (keeping my tinkering in place)
```yaml
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: **************
      node-db.node.session.auth.password: **************
      node-db.node.session.auth.username_in: **************
      node-db.node.session.auth.password_in: **************
```

I wouldn't discard some additional user error, but from what I can tell the ``provisioner-secret```on the ``storageClasses.parameters`` does nothing and the only thing making the provisioning work are the additional stuff I added to the ``targetTemplate``.

My new ``values.yaml`` looks like this now:

```yaml
csiDriver:
  name: org.democratic-csi.iscsi-synology

controller:
  externalResizer:
    enabled: true

  externalSnapshotter:
    enabled: true

driver: 
  config: 
    driver: synology-iscsi 
    httpConnection:
      protocol: https
      host: ****************************
      port: 5001
      username: **************
      password: **************
      allowInsecure: false
      # should be uniqe across all installs to the same nas
      session: "democratic-csi"
      serialize: true

    iscsi:
      targetPortal: "****************************:3260"
      # for multipath
      targetPortals: [] # [ "server[:port]", "server[:port]", ... ]
      # leave empty to omit usage of -I with iscsiadm
      interface: ""
      # can be whatever you would like
      baseiqn: "iqn.2000-01.com.synology:csi."
      targetGroups:

      # MUST ensure uniqueness
      # full iqn limit is 223 bytes, plan accordingly
      namePrefix: "dk8s-"
      nameSuffix: ""
      lunTemplate:
        type: "BLUN"
        # tpws = Hardware-assisted zeroing
        # caw = Hardware-assisted locking
        # 3pc = Hardware-assisted data transfer
        # tpu = Space reclamation
        # can_snapshot = Snapshot
        #dev_attribs:
        #- dev_attrib: emulate_tpws
        #  enable: 1
        #- dev_attrib: emulate_caw
        #  enable: 1
        #- dev_attrib: emulate_3pc
        #  enable: 1
        #- dev_attrib: emulate_tpu
        #  enable: 0
        #- dev_attrib: can_snapshot
        #  enable: 1
      lunSnapshotTemplate:
        is_locked: true
        is_app_consistent: true

      targetTemplate:
        auth_type: 2
        max_sessions: 0
        chap: true
        mutual_chap: true
        user: **************
        password: **************
        mutual_user: **************
        mutual_password: **************

    synology:
      volume: /volume1

controller:
  externalResizer:
    enabled: true

  externalSnapshotter:
    enabled: true

storageClasses: 
- name: democratic-iscsi-retain-chap
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
    lunTemplate: |
      type: BLUN
      description: LUN for ${pvc.name}
  secrets:
    provisioner-secret:
      user: **************
      password: **************
      mutualUser: **************
      mutualPassword: **************

- name: democratic-iscsi-delete-chap
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
    lunTemplate: |
      type: BLUN
      description: LUN for ${pvc.name}
  secrets:
    provisioner-secret:
      user: **************
      password: **************
      mutualUser: **************
      mutualPassword: **************
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: **************
      node-db.node.session.auth.password: **************
      node-db.node.session.auth.username_in: **************
      node-db.node.session.auth.password_in: **************
volumeSnapshotClasses:
- name: democratic-iscsi
  parameters:
  secrets:
    snapshotter-secret: 
      user: **************
      password: **************
      mutualUser: **************
      mutualPassword: **************
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: **************
      node-db.node.session.auth.password: **************
      node-db.node.session.auth.username_in: **************
      node-db.node.session.auth.password_in: **************
````

**Comment by travisghansen** [comment]
Welcome! Yes the 2 sections correspond to both the server side (synology/synology api) and client side (iscsiadm on linux).

Is everything working at this point? Or is there still some breakdown somewhere?

I considered adding a synology nfs/smb driver at some point but last I recalled there wasn’t really a way to limit the size of those volumes on a per-share basis to functionality it would be the same as the nfs-client provisioner essentially.

**Comment by akrauze** [comment]
Well, it is sort of working. I mean works for me....

What I had missing was the node secret.
However, it seems the csidriver ignores the provisioner secret and that only works for me after tinkering with the target template. It could be the way it was intended to be, in which case the docs could use an update.

Regarding smb and nfs. It seems they implemented some sort of quota (the synology-csi sets it). But I can't tell how well it works. My biggest complain on the synology-csi integration is that is grants access from ``*`` rather than node addresses (I wish NFS was a bit more secure).

**Comment by travisghansen** [comment]
Oh I see. I didn't write that doc which could explain why it's off a little. Try this:

```yaml
storageClasses: 
- name: democratic-iscsi-retain-chap
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: ext4
    lunTemplate: |
      type: BLUN
      description: LUN for ${pvc.name}
  secrets:
    provisioner-secret:
      lunTemplate: |
        user: **************
        password: **************
        mutualUser: **************
        mutualPassword: **************
      targetTemplate: |
        ...
      lunSnapshotTemplate: |
        ...
```

Essentially follow the same syntax as the `parameters.fooTemplate`.

**Comment by travisghansen** [comment]
And it looks like this is actually the syntax/field names, not what is in the example:

```yaml
  targetTemplate:
    # 0 = no auth
    # 1 = chap
    # 2 = mutual chap
    auth_type: 0
    # if auth_type is 1 or 2
    #chap: true
    # if auth_type = 2
    #mutual_chap: true
    # if auth_type is 1 or 2
    #user: foo
    #password: bar
    # if auth_type = 2
    #mutual_user:
    #mutual_password:
    max_sessions: 0
```

On the `target` not the `lun`. The values in the storage class `parameters` and the `secret` are literally parsed and merged using js `Object.assign()`. So the field naming should match exactly what the api is expecting.
