### ISSUE TITLE
Multipath direct-attached storage issues

### ISSUE THREAD

**Issue by Microcarft** [democratic-csi/democratic-csi#460]
Thank you very much for your work!
I encountered some minor bugs when using it, I wonder if I can solve it.
My configuration is as follows:
```
# charts/stable/democratic-csi/examples/truenas-nfs.yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"
  fsGroupPolicy: File

# add note here about volume expansion requirements
storageClasses:
  - name: truenas-nfs-csi
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      # for block-based storage can be ext3, ext4, xfs
      # for nfs should be nfs
      fsType: nfs

      # if true, volumes created from other snapshots will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromSnapshots: "false"

      # if true, volumes created from other volumes will be
      # zfs send/received instead of zfs cloned
      # detachedVolumesFromVolumes: "false"

    mountOptions:
      - noatime
      - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses:
- name: truenas-nfs-snap
  parameters:
#  # if true, snapshots will be created with zfs send/receive
   detachedSnapshots: "true"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: truenas-nfs
    instance_id: R730XD02
    httpConnection:
      protocol: http
      host: 192.168.100.4
      port: 80
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      apiKey: my apiKey
      username: rootest
      password:
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    sshConnection:
      host: 192.168.100.4
      port: 2233
      username: rootest
      # use either password or key
      password: ""
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        ...
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      # can be used to override defaults if necessary
      # the example below is useful for TrueNAS 12
      cli:
        sudoEnabled: true
      #
      #  leave paths unset for auto-detection
        paths:
          zfs: /sbin/zfs
          zpool: /sbin/zpool
          sudo: /usr/bin/sudo
      #    chroot: /usr/sbin/chroot

      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      #datasetProperties:
      #  "org.truenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.truenas:test": "{{ parameters.foo }}"
      #  "org.truenas:test2": "some value"

      datasetParentName: MatrixPool/Kubernetes/nfs/vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      # do NOT comment this option out even if you don't plan to use snapshots, just leave it with dummy value
      detachedSnapshotsDatasetParentName: MatrixPool/Kubernetes/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
      #datasetPermissionsAcls:
      #- "-m everyone@:full_set:allow"
      #- "-m u:kube:full_set:allow"

    nfs:
      #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: "{{ node.labels['democratic-csi-nfs-host'] }}"
      sharePathTemplate: "/mnt/MatrixPool/Kubernetes/nfs/vols/{{ pvc.name }}"
      shareAlldirs: false
      shareAllowedHosts:
      - 172.0.1.1
      - 172.0.2.1
      - 172.0.3.1
      - 172.0.4.1
      - 172.0.5.1
      - 172.0.6.1
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: root
      shareMapallUser: ""
      shareMapallGroup: ""
```

As you are, in the "shareHost" line, I did not use the IP or domain name, because the current environment is multi-path direct-connected storage. Each client is directly connected to the TrueNAS server and they access the TrueNAS with different IPs.

I tried to label each node, the key corresponding to the value of their access to the TrueNAS IP, and then reference these keys in "shareHost". I hope these changes can achieve my needs, but unfortunately the result I got is:
`/usr/local/bin/mount: illegal option -- o\nmount.nfs: Failed to resolve server {{ node.labels['democratic-csi-nfs-host'] }}: Name or service not known\n`

This is very interesting hhh
