### ISSUE TITLE
mkdir /usr/local/etc/iscsi: read-only file system

### ISSUE THREAD

**Issue by BaldFabi** [democratic-csi/democratic-csi#461]
First of all thank you for the project. I'm currently trying in a test setup talos, TrueNAS and this project.
I provisioned everything using Terraform but now I encounter unfortunately the following error.

```
Error: failed to generate container "34eb1f603f768636d2950828b3043bd19d01429124172f039bfb1f6d18d3b101" spec: failed to apply OCI options: failed to mkdir "/usr/local/etc/iscsi": mkdir /usr/local/etc/iscsi: read-only file system
```

But I actually don't understand why because I think I configured everything what has to be done.
The iscsi tools are deployed as an extension

```
NODE          NAMESPACE   TYPE              ID                                          VERSION   NAME          VERSION
10.50.0.101   runtime     ExtensionStatus   000.ghcr.io-siderolabs-iscsi-tools-v0.2.0   1         iscsi-tools   v0.2.0
```

My `values.yml` for the chart looks like this (the api key was replaced)

```yaml
---
driver:
  config:
    driver: freenas-api-iscsi
    httpConnection:
      protocol: https
      apiKey: XXX
      host: 10.50.0.11
      port: 443
      allowInsecure: true
    zfs:
      datasetParentName: pool0/k8s-test/volumes
      detachedSnapshotsDatasetParentName: pool0/k8s-test/snapshots
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlockSize:
    iscsi:
      targetPortal: "10.50.0.11:3260"
      targetPortals: []
      interface:
      namePrefix: csi-
      nameSuffix: "-talos"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 5
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0

csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.freenas-api-iscsi"

storageClasses:
  - name: truenas-iscsi
    defaultClass: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses:
  - name: truenas-iscsi
    parameters:
      detachedSnapshots: "true"

node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /usr/local/etc/iscsi
    iscsiDirHostPathType: ""
```

Can someone point me in the direction to fix this? That would be great, thank you!

**Comment by BaldFabi** [comment]
I just fought I should lower the version of the iscsi tools on the talos side because (and I actually don't know why) 0.2.0 looks odd.
With 0.1.6 for whatever reason the error vanishes

**Comment by BaldFabi** [comment]
Unfortunately a testdeployment with a PVC of 1 GiB and RWO mode results in the following error.

```
Warning  ProvisioningFailed  68s (x9 over 5m25s)  org.democratic-csi.freenas-api-iscsi_zfs-iscsi-democratic-csi-controller-5cbb69d464-mqv cp_992ae16f-b59e-4006-bba5-f139e5e6f734  failed to provision volume with StorageClass "truenas-iscsi": rpc error: code = Internal desc = Error: {"path":[{"message":"null not allowed","errno":22}]} Error: {"path":[{"message":"null not allowed","errno":22}]}
    at Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:395:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.CreateVolume (/home/csi/app/src/driver/freenas/api.js:2790:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
```

I can't figure out, what could be the problem. The `csi-driver` container doesn't provide much more

**Comment by travisghansen** [comment]
Did you get this sorted? What is the name of your pool?

**Comment by BaldFabi** [comment]
It still doesn't work. The name of the pool is pool0 but I just had an idea.
The values of the options `datasetParentName` and `detachedSnapshotsDatasetParentName` point to something that don't exist yet.
I only created `pool0/k8s-test` as a zvol. I saw that configuration in the examples but now I'm wondering if that's correct.

**Comment by travisghansen** [comment]
Ok, so as an FYI the error has nothing to do with the iscsi tools version etc. it’s blowing up well before that comes into play.

You should enable debug logging on the controller and then gather they logs from the `csi-driver` container. That will show the full http requests/responses to TrueNAS and we can better see what value isn’t being properly set in the payload.

**Comment by BaldFabi** [comment]
Had to move temporarily to my prod setup. Thus the TrueNAS host is anonymized and the pool is named `data0`.
`null not allowed` seems like odd.

```
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"info","message":"new request - driver: FreeNASApiDriver method: CreateVolume call: {\"path\":\"/csi.v1.Controller/CreateVolume\",\"metadata\":{},\"request\":{\"volume_capabilities\":[{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"ext4\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}],\"parameters\":{\"detachedVolumesFromSnapshots\":\"false\",\"fsType\":\"ext4\",\"csi.storage.k8s.io/pvc/name\":\"data\",\"csi.storage.k8s.io/pvc/namespace\":\"flame\",\"csi.storage.k8s.io/pv/name\":\"pvc-054c168c-15db-43a0-bf1c-30a15dd4c669\"},\"secrets\":\"redacted\",\"name\":\"pvc-054c168c-15db-43a0-bf1c-30a15dd4c669\",\"capacity_range\":{\"required_bytes\":\"1073741824\",\"limit_bytes\":\"0\"},\"volume_content_source\":null,\"accessibility_requirements\":null},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.897Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"operation lock keys: [\"create_volume_name_pvc-054c168c-15db-43a0-bf1c-30a15dd4c669\"]","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.897Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"verbose","message":"validating capabilities: [{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"ext4\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}]","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.899Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP REQUEST DETAILS: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":60000,\"method\":\"GET\",\"url\":\"https://XXX/api/v2.0/pool/dataset/id/data0%2Fk8s-test%2Fvolumes%2Fpvc-054c168c-15db-43a0-bf1c-30a15dd4c669\"}","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.949Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP REQUEST DURATION: 0.05s","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.949Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.950Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP RESPONSE STATUS CODE: 404","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.950Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP RESPONSE HEADERS: {\"server\":\"nginx\",\"date\":\"Tue, 08 Apr 2025 19:50:43 GMT\",\"content-type\":\"application/json; charset=utf-8\",\"content-length\":\"18\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=63072000; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.950Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP RESPONSE BODY: {\"message\":\"\"}","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.950Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"max zvol name length: 255","service":"democratic-csi","timestamp":"2025-04-08T19:50:43.950Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP REQUEST DETAILS: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":60000,\"method\":\"POST\",\"url\":\"https://XXX/api/v2.0/pool/dataset\",\"data\":{\"refreservation\":0,\"volblocksize\":\"16K\",\"type\":\"VOLUME\",\"volsize\":1073741824,\"sparse\":true,\"create_ancestors\":true,\"share_type\":\"GENERIC\",\"user_properties\":[{\"key\":\"democratic-csi:csi_volume_name\",\"value\":\"pvc-054c168c-15db-43a0-bf1c-30a15dd4c669\"},{\"key\":\"democratic-csi:managed_resource\",\"value\":\"true\"},{\"key\":\"democratic-csi:volume_context_provisioner_driver\",\"value\":\"freenas-api-iscsi\"}],\"name\":\"data0/k8s-test/volumes/pvc-054c168c-15db-43a0-bf1c-30a15dd4c669\"}}","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.032Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP REQUEST DURATION: 0.08s","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.032Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.032Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP RESPONSE STATUS CODE: 422","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.032Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP RESPONSE HEADERS: {\"server\":\"nginx\",\"date\":\"Tue, 08 Apr 2025 19:50:44 GMT\",\"content-type\":\"application/json; charset=utf-8\",\"content-length\":\"74\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=63072000; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.033Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"debug","message":"FREENAS HTTP RESPONSE BODY: {\"path\":[{\"message\":\"null not allowed\",\"errno\":22}]}","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.033Z"}
{"host":"democratic-csi-controller-68cbf4cc5d-4j4xk","level":"error","message":"handler error - driver: FreeNASApiDriver method: CreateVolume error: Error: {\"path\":[{\"message\":\"null not allowed\",\"errno\":22}]} Error: {\"path\":[{\"message\":\"null not allowed\",\"errno\":22}]}\n    at Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:395:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async FreeNASApiDriver.CreateVolume (/home/csi/app/src/driver/freenas/api.js:2790:7)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)","service":"democratic-csi","timestamp":"2025-04-08T19:50:44.033Z"}

```

**Comment by travisghansen** [comment]
Yeah this is helpful. On the surface I do not see anything there that appears to be blatantly wrong. I will need to dig into the tn code I guess to see what scenarios could result in that error code.

**Comment by travisghansen** [comment]
Can you run `zpool history` and see if the relevant entry is in there?

- https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/zfs_/dataset.py#L107
- https://github.com/truenas/py-libzfs/blob/master/libzfs.pyx#L3226

**Comment by BaldFabi** [comment]
There is only one log line for the zvol and that was the creation which I did via the webui

```
2025-04-08.20:42:10 py-libzfs: zfs create -o org.freenas:description= -o org.truenas:managedby=10.100.1.235 -o volblocksize16384 -o volsize107374198784 data0/k8s-test
```

**Comment by travisghansen** [comment]
Ah, every part of the `datasetParentName` must be a dataset. Zvols don’t allow for nested volumes so you must delete `pool0/k8s-test` zvol or change the path for the parent.

**Comment by BaldFabi** [comment]
So I delete the zvol k8s-test and create a dataset instead? I thought it has to be a zvol due to the other config options or maybe I read it somewhere? (I'm not sure tho)

**Comment by BaldFabi** [comment]
Ok I see. That's unusual for me. I will try it and give you feedback. Thank you

**Comment by BaldFabi** [comment]
I can't get it working. If I delete the zvol which gets automatically created using the wizard in TrueNAS a part of the iscsi configuration gets also deleted.
This on the other hand results presumably in a non working csi driver.
I followed the guide from [fenio](https://github.com/fenio/k8s-truenas?tab=readme-ov-file) to the point he's using the wizard but TrueNAS doesn't allow a configuration like this anymore.

Tbh it's a little bit weird that the driver creates the path on TrueNAS itself instead of using whats defined in the config.

**Comment by BaldFabi** [comment]
Thank you, will try that too

**Comment by mpeterson** [comment]
> [@BaldFabi](https://github.com/BaldFabi) could you try suggested solution? [siderolabs/extensions#688 (comment)](https://github.com/siderolabs/extensions/issues/688#issuecomment-2850824503)

that indeed fixest he issue. Thanks for the reference @Eyeless77

**Comment by waza-ari** [comment]
Hey @Eyeless77 and @mpeterson, with these new configs, are you able to create new PVCs?

For me, the ZVol and target get created just fine, however actually mounting the PVC to the pod fails:

```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Warning  FailedScheduling        2m8s                 default-scheduler        0/6 nodes are available: pod has unbound immediate PersistentVolumeClaims. not found
  Warning  FailedScheduling        115s (x2 over 115s)  default-scheduler        0/6 nodes are available: pod has unbound immediate PersistentVolumeClaims. not found
  Normal   Scheduled               115s                 default-scheduler        Successfully assigned storage/storage-test-pod to talos-worker1
  Normal   SuccessfulAttachVolume  115s                 attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-180149f1-c13c-4a7f-9f97-db12fc2546a9"
  Warning  FailedMount             20s (x7 over 100s)   kubelet                  MountVolume.MountDevice failed for volume "pvc-180149f1-c13c-4a7f-9f97-db12fc2546a9" : rpc error: code = Internal desc = {"code":1,"stdout":"","stderr":"failed to find iscsid pid for nsenter\n","timeout":false}
```

My config:

```yaml
controller:
  driver:
    image:
      tag: next
node:
  hostPID: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /var/iscsi
    iscsiDirHostPathType: ""
csiDriver:
  name: "iscsi"
storageClasses:
- name: iscsi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
    detachedVolumesFromSnapshots: "false"
volumeSnapshotClasses:
- name: iscsi
  parameters:
    detachedSnapshots: "true"
driver:
  existingConfigSecret: "truenas-iscsi-driver-config"
  config:
    driver: freenas-api-iscsi
    httpConnection:
      allowInsecure: true
      apiKey: <redacted>
      host: <redacted>
      port: 80
      protocol: http
    instance_id: null
    iscsi:
      targetPortal: "<redacted>:3260"
      targetPortals: [] 
      interface:
      namePrefix: csi-
      nameSuffix: "-cluster"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      extentInsecureTpc: true
      extentXenCompat: false
      extentRpm: "SSD"
      extentBlocksize: 512
      extentAvailThreshold: 0
    zfs:
      datasetParentName: prod/iscsi/kubernetes/volumes
      detachedSnapshotsDatasetParentName: prod/iscsi/kubernetes/snapshots
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
```
