### ISSUE TITLE
staging path is not mounted when using zfs dataset

### ISSUE THREAD

**Issue by manju-rn** [democratic-csi/democratic-csi#463]
Here is my setup:
1. Ubuntu - 24.04  install with zfs
2. Datasets created - the last one was dynamically provisioned

```
NAME                                                     USED  AVAIL  REFER  MOUNTPOINT
mypool                                                   288K  18.9G    24K  /mypool
mypool/csi-ds                                             48K  18.9G    24K  /home/manju/zfs-data
mypool/csi-ds-snap                                        24K  18.9G    24K  /home/manju/zfs-snap
mypool/csi-ds/pvc-fdf13f7a-2611-4c9d-8401-96607ae5b3dd    24K  1024M    24K  legacy
```
3. values file update with zfs dataset
```
driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: zfs-local-dataset
    #...
    zfs:
      datasetParentName: mypool/csi-ds
      detachedSnapshotsDatasetParentName: mypool/csi-ds-snap

      datasetProperties:
      # key: value

      datasetEnableQuotas: true
      datasetEnableReservation: false
```

When i run my workload - a postgres container in this case, there is this error and the postgres container is in `containercreating` mode

```
executing mount command: findmnt --mountpoint /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.zfs-local-dataset/a77710e8430024ddf6f4d464843ba8c14febace2097eedcd74f6ff8148d7df2e/globalmount --output source,target,fstype,label,options -b -J --nofsroot
{"host":"localhost","level":"error","message":"handler error - driver: ControllerZfsLocalDriver method: NodePublishVolume error: {\"name\":\"GrpcError\",\"code\":9,\"message\":\"staging path is not mounted: /var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.zfs-local-dataset/a77710e8430024ddf6f4d464843ba8c14febace2097eedcd74f6ff8148d7df2e/globalmount\"}","service":"democratic-csi","timestamp":"2025-03-19T13:08:39.642Z"}
```

Is there a documentation about what is staging path mean and what could be  potential fixes?
