### ISSUE TITLE
NFS Disks for Virtual Machines

### ISSUE THREAD

**Issue by abonillabeeche** [democratic-csi/democratic-csi#472]
Hello -

I'm using kube-Virt to deploy VMs using a TrueNAS and the democratic-csi. Unfortunately, when using NFS, the virtual machine disk size is allocated as the same size of the original disk. The requested disk size is 42GB.

![Image](https://github.com/user-attachments/assets/d0731cb7-7dd8-4901-8511-1d87e0783ce9)

but the disk size really is shown as

```
root@ubuntu-nfs:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           1.6G  1.3M  1.6G   1% /run
efivarfs        256K  4.3K  252K   2% /sys/firmware/efi/efivars
/dev/vda1       2.4G  1.9G  467M  81% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/vda16      891M   58M  771M   7% /boot
/dev/vda15       98M  6.4M   92M   7% /boot/efi
tmpfs           1.6G   12K  1.6G   1% /run/user/1000

root@ubuntu-nfs:~# fdisk -l
Disk /dev/vda: 3.5 GiB, 3758096384 bytes, 7340032 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: FAF46872-F1AC-414B-8C46-D3722098FE76

Device       Start     End Sectors  Size Type
/dev/vda1  2099200 7339998 5240799  2.5G Linux filesystem
/dev/vda15    2048  204800  202753   99M EFI System
/dev/vda16  206848 2097152 1890305  923M Linux extended boot

Partition table entries are not in disk order.


Disk /dev/vdb: 1 MiB, 1048576 bytes, 2048 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

The StorageProfile is configured as

```
spec:
  claimPropertySets:
  - accessModes:
    - ReadWriteMany
    volumeMode: Filesystem
  cloneStrategy: copy
```

and the CSI is using

```
csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
- name: truenas-nfs
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs
  mountOptions:
    - noatime
    - nfsvers=4
                            
driver:                     
  config:
    driver: freenas-api-nfs
```

Any recommendations of what else I may need?

Thanks!
