### ISSUE TITLE
TrueNAS 25.04 incompatible

### ISSUE THREAD

**Issue by bbieberle** [democratic-csi/democratic-csi#479]
I just upgraded to TrueNAS 25.04. Now democratic csi refuses to start, because of the renaming of TrueNAS. As there is now no difference between Core and Scale, democratic refuses to work because (I think) the truenas API tells the driver, that it is simply named "truenas" instead of "truenas scale".

**Comment by travisghansen** [comment]
This has already been fixed in `next` images but I have not snapped a release yet.

**Comment by amprince01** [comment]
Do you know when this will be released?

**Comment by travisghansen** [comment]
I don’t have a date yet but seems enough pressure I should probably release something :)

**Comment by amprince01** [comment]
Definitely! <poke, poke>

**Comment by 1ARdotNO** [comment]
> I don’t have a date yet but seems enough pressure I should probably release something :)

It would be fantastic :-)

**Comment by anodos325** [comment]
FYI, starting in 25.04 API consumers can get the unauthenticated endpoint `api/versions` to retrieve the versions of the TrueNAS API that are supported.

e.g.
```
>>> requests.get('http://127.0.0.1/api/versions').json()
['v24.10', 'v25.04.0', 'v25.04.1', 'v25.10.0']
```

This will make it easier to support going forwards without having to parse version strings from the server. If you develop against v25.04.1 of the API and it's not in the versions output of TrueNAS, you can then present users with an error that the version of TrueNAS is not supported. Once a version of the TrueNAS API is in a published release, then it is stable for its lifetime. This over time should reduce maintenance burden.

**Comment by turok01** [comment]
**Title**: GET /api/v2.0/system/version/ no longer includes “scale” in version string, breaking detection logic

**Description**: In TrueNAS SCALE Fangtooth 25.04, the API endpoint GET /api/v2.0/system/version/ returns: 
"TrueNAS-25.04.0"
Previously, this version string included "scale" (e.g., "TrueNAS-SCALE-24.10.2.1"), which was used by external tools like democratic-csi driver to detect whether the instance is running TrueNAS SCALE.

This change breaks the getIsScale() method in democratic-csi code:

```
if (!(await httpApiClient.getIsScale())) {
        throw new GrpcError(
          grpc.status.FAILED_PRECONDITION,
          driver is only availalbe with TrueNAS SCALE
        );
      }
...
async getIsScale() { 
  const systemVersion = await this.getSystemVersion();
  if (systemVersion.v2 && systemVersion.v2.toLowerCase().includes("scale")) {
    return true;
  }
  return false;
}
```
As a result, errors like this are thrown:
GrpcError: driver is only availalbe with TrueNAS SCALE.

I've compared also response from 25 and 24 version for product_type:

GET https://25.04.server.version:443/api/v2.0/system/product_type/                 "COMMUNITY_EDITION"

GET https://24.10.2.1.server.version:443/api/v2.0/system/product_type/            "SCALE"

Perhaps this field can be used for comparison

**Comment by turok01** [comment]
Thank you, linuxmaniac, it's working well: 
```
controller:
  driver:
    enabled: true
    image:
      registry: docker.io/democraticcsi/democratic-csi
      tag: next
```
(for some reason image: docker.io/democraticcsi/democratic-csi:next give an error on my configuration)

**Comment by amprince01** [comment]
Have you posted the Next image to Helm or is it only available as a docker pull ATM?

**Comment by anodos325** [comment]
@travisghansen there is now a truenas website documenting the versioned API. https://api.truenas.com/
The current development version (as of this post 25.10.0) will be updated weekly with any changes.

**Comment by zackman0010** [comment]
> I don’t have a date yet but seems enough pressure I should probably release something :)

@travisghansen Any updates on when a release can be made? I just ran into this issue myself.

**Comment by fossum** [comment]
@zackman0010 use turok01's solution for now.

**Comment by mredrivera** [comment]
I am trying the next tag but somehow helm is not picking it up.  It is defaulting to latest and I feel like I have tried every single possible combination to force the next tag.  Any ideas?

**Comment by djjudas21** [comment]
The great thing about Helm is that it only takes one missed space in the yaml to silently skip a block of config 😅 

Here's my entire `value.yaml` (less the secrets). Note there are several places to set `tag: next`. Hope this helps!

```yaml
driver:
  image:
    tag: next
  config:
    driver: freenas-api-nfs
    instance_id: truenas
    httpConnection:
      protocol: http
      host: 192.168.0.2
      port: 80
      allowInsecure: true
    zfs:
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      datasetParentName: ssd/k8s/vols
      detachedSnapshotsDatasetParentName: ssd/k8s/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: 192.168.0.2
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: ''
      shareMaprootGroup: ''
      shareMapallUser: root
      shareMapallGroup: root


# https://kubernetes-csi.github.io/docs/csi-driver-object.html
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"
  storageCapacity: true

controller:
  enabled: true
  rbac:
    enabled: true
  replicaCount: 1
  hostNetwork: false
  priorityClassName: ""

  # https://github.com/kubernetes-csi/external-health-monitor
  externalHealthMonitorController:
    enabled: false
    resources:

  livenessProbe:
    enabled: true

  # democratic-csi controller
  driver:
    enabled: true
    image:
      tag: next
    logLevel: info
    resources:

node:
  rbac:
    enabled: true
  enabled: true
  hostNetwork: true

  livenessProbe:
    enabled: true

  # democratic-csi node
  driver:
    enabled: true
    logLevel: info
    resources:
      requests:
        memory: 100Mi
        cpu: 25m

  # https://kubernetes-csi.github.io/docs/node-driver-registrar.html
  driverRegistrar:
    resources:

# add note here about volume expansion requirements
storageClasses:
- name: truenas
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs
    mountOptions:
    - noatime
    - nfsvers=4

volumeSnapshotClasses:
  - name: truenas
    annotations: {}
    labels:
      velero.io/csi-volumesnapshot-class: "true"
    defaultClass: false
    deletionPolicy: Delete
```

**Comment by 93imagine** [comment]
At first I thought things broke because of `For increased security, HTTPS with SSL/TLS transport security is required for TrueNAS API authentication using API keys. TrueNAS automatically revokes any user-linked API keys passed as part of an authentication attempt via insecure (HTTP) transport. A revoked API key cannot be used until it is reset. Resetting generates a new key-string.` from the [TrueNAS 25.04 Version Notes](https://www.truenas.com/docs/scale/25.04/gettingstarted/scalereleasenotes/).

However the example above also has the insecure flag set. Can anyone confirm is not a problem using the _next_ tag in combination with 25.04 over HTTP?

**Comment by kyuuk** [comment]
> At first I thought things broke because of `For increased security, HTTPS with SSL/TLS transport security is required for TrueNAS API authentication using API keys. TrueNAS automatically revokes any user-linked API keys passed as part of an authentication attempt via insecure (HTTP) transport. A revoked API key cannot be used until it is reset. Resetting generates a new key-string.` from the [TrueNAS 25.04 Version Notes](https://www.truenas.com/docs/scale/25.04/gettingstarted/scalereleasenotes/).
> 
> However the example above also has the insecure flag set. Can anyone confirm is not a problem using the _next_ tag in combination with 25.04 over HTTP?


the insecure flag is set to true when you are using an https endpoint with a certificate that is not publicly trusted (selfsigned certificate for example) the protocol used (http or https) depends only on the `protocol` parameter like in the example [here ](https://github.com/democratic-csi/democratic-csi/blob/8193b689ed9864a0ab1d71c87cfbed29f7ff2d86/examples/freenas-api-nfs.yaml#L4)

**Comment by marktuk** [comment]
I managed to get it working, I have no idea why it didn't work before as I tried the `next` release, the only thing I did differently is I did it in 3 places as I saw someone else doing that in another issue

```
node:
  driver:
    image:
      tag: next

controller:
  driver:
    image:
      tag: next

driver:
  image:
    tag: next
```

> ssh-based variants

Are there any docs or examples of this approach? It sounds like it's probably the better way to go.
