### ISSUE TITLE
Providing httpConnection.apiKey and sshConnection.privateKey as Secret

### ISSUE THREAD

**Issue by Ramblurr** [democratic-csi/democratic-csi#48]
Is it possible to pass Secret names for the  `httpConection.apiKey` and sshConnection.privateKey` values instead of the raw values?

Pardon if this is already supported and documented, but after browsing the examples and doing some searches of the repo I couldn't uncover anything.

**Comment by travisghansen** [comment]
You can't do individual values like that, however you can create the whole config as a secret 'out of band' of the chart and just tell the chart where it is.

- https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L10

I would suggest to review the existing secret for syntax help to ensure you're setting the proper keys/values etc.

**Comment by Ramblurr** [comment]
Thanks once again @travisghansen 

I think there's a bug. I removed the `driver.config` object from my values yaml, replaced it with `existingConfigSecret` referencing an existing secret in the same namespaced.

But this error is thrown by helm:


```
Helm upgrade failed: template: democratic-csi/templates/node.yaml:3:19:
executing "democratic-csi/templates/node.yaml" at <include "democratic-csi.mount-iscsi" .>: 
error calling include: template: democratic-csi/templates/_helpers.tpl:36:31:
executing "democratic-csi.mount-iscsi" at <.Values.driver.config.driver>:
wrong type for value; expected string; got interface {}
```

Looking at [this line](https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/templates/_helpers.tpl#L36) in the _helpers.tpl, is this a possible bug? That template assumes the `driver.config` object exists which in the case of an external config it doesn't.

Entire values.yml:
```yaml
  values:
    csiDriver:
      name: org.democratic-csi.nfs
    node:
      kubeletHostPath: /var/snap/microk8s/common/var/lib/kubelet
    controller:
      driver:
        logLevel: debug
      node:
        logLevel: debug
    storageClasses:
      - name: freenas-nfs
        defaultClass: true
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - noatime
          - async
    driver:
      existingConfigSecret: driver-config

```

**Comment by travisghansen** [comment]
Oh yeah, that’s gonna be interesting to fix :(

**Comment by Ramblurr** [comment]
So I tried to workaround the problem with [this change](https://github.com/Ramblurr/democratic-csi-charts/commit/6fb9a3be4402fb2f30c12188b6d583ec8b494a57#diff-1a4bdb03236677bc8afb44eacf0b7ce61c3bee5aca146365d71c3cacd7965a38)

But now the controller pod's `csi-driver` is throwing the error

```
info: new request - driver: FreeNASDriver method: Probe call: {"_events":{},"_eventsCount":1,"call":{},"cancelled":false,"metadata":{"_internal_repr":{"user-agent":["grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)"]},"flags":0},"request":{}}
error: handler error - driver: FreeNASDriver method: Probe error: TypeError: Cannot read property 'replace' of undefined
{
  code: 13,
  message: "TypeError: Cannot read property 'replace' of undefined"
}
```

(debug mode is enabled)

**Comment by travisghansen** [comment]
Yeah I think I’ll need to add a manual parameter for the pre existing secret scenarios. I’ll get something fixed up when back from a little trip and have a proper solution for ya.

**Comment by travisghansen** [comment]
An alternative for the time being is to just replicate the value from the secret in the config block for just that property...not ideal but probably less ugly than the hacked chart. It won’t hurt anything have the data in the config block as I recall.

**Comment by travisghansen** [comment]
OK, I've thought about this one a bit more and have decided to continue requiring the value as suggested previously. I will make a note in the `values.yaml` to clarify. In short, do something like this:

```
driver:
  existingConfigSecret: "somesecret"
  config:
    driver: <place the corresponding value that you used in the secret here>
```

That should work already with the existing chart. If you don't mind trying it out and letting me know how it goes that would be great. Thanks!
