### ISSUE TITLE
fsGroup not applied to volumeMounts using zfs-generic-nfs

### ISSUE THREAD

**Issue by an-ky** [democratic-csi/democratic-csi#482]
Hi. First big thanks for this CSI provider. It is quite easy to configure and works very well. 

We got it running with ISCSI and NFS on zfs-generic but with the latter I'm stuck with the following problem that fsGroup does not get properly applied to the mounted volume when mounted as RWX into an unprivileged container.

Storage node runs debian 12 (bookworm).

Deployment was done with the following helm chart values.yaml and tested with the below manifest. `csiDriver.fsGroupPolicy: File` is applied like suggested in #274 but this does not help.

Currently I work around this by setting `driver.config.datasetPermissionsMode: '0777'` which allows the user in the pod to access files in the directory but this does not feel proper.

values.yaml
```
nameOverride: ''
fullnameOverride: ''
extraCaCerts: null
csiDriver:
  name: org.democratic-csi.nfs
  fsGroupPolicy: File
  version: 1.5.0
  enabled: true
  attachRequired: true
  podInfoOnMount: true
controller:
  enabled: true
  rbac:
    enabled: true
    openshift:
      privileged: false
  replicaCount: 1
  hostNetwork: false
  hostAliases: []
  hostIPC: false
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ''
  strategy: deployment
  externalAttacher:
    enabled: true
    image:
      registry: registry.k8s.io/sig-storage/csi-attacher
      tag: v4.4.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources: null
  externalProvisioner:
    enabled: true
    image:
      registry: registry.k8s.io/sig-storage/csi-provisioner
      tag: v3.6.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --extra-create-metadata
      - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources: null
  externalResizer:
    enabled: true
    image:
      registry: registry.k8s.io/sig-storage/csi-resizer
      tag: v1.9.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --workers=10
      - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources: null
  externalSnapshotter:
    enabled: true
    image:
      registry: registry.k8s.io/sig-storage/csi-snapshotter
      tag: v6.3.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources: null
  externalHealthMonitorController:
    enabled: false
    image:
      registry: registry.k8s.io/sig-storage/csi-external-health-monitor-controller
      tag: v0.11.0
    args:
      - --v=5
      - --leader-election
      - --leader-election-namespace={{ .Release.Namespace }}
      - --timeout=90s
      - --worker-threads=10
      - --csi-address={{ .csiSocketAddress }}
    extraArgs: []
    resources: null
  clusterDriverRegistrar:
    enabled: false
  livenessProbe:
    enabled: true
  driver:
    enabled: true
    image:
      registry: docker.io/democraticcsi/democratic-csi
      tag: latest
    logLevel: info
    lifecycle: null
    securityContext: null
    resources: null
    extraEnv: []
    extraVolumeMounts: []
  extraVolumes: []
  nodeSelector: {}
  tolerations: []
  topologySpreadConstraints: []
  affinity: {}
node:
  windows:
    enabled: false
  rbac:
    enabled: true
    openshift:
      privileged: false
  enabled: true
  hostNetwork: true
  hostAliases: []
  hostIPC: true
  hostPID: false
  annotations: {}
  labels: {}
  podAnnotations: {}
  podLabels: {}
  priorityClassName: ''
  livenessProbe:
    enabled: true
  cleanup:
    image:
      registry: docker.io/busybox
      tag: 1.37.0
    resources: null
  driver:
    enabled: true
    image:
      registry: docker.io/democraticcsi/democratic-csi
      tag: latest
    logLevel: info
    localtimeHostPath: /etc/localtime
    lifecycle: null
    resources: null
    extraEnv: []
    extraVolumeMounts: []
  driverRegistrar:
    enabled: true
    image:
      registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.9.0
    args:
      - --v=5
      - --csi-address={{ .csiSocketAddress }}
      - --kubelet-registration-path={{ .Values.node.kubeletHostPath }}/plugins/{{
        .Values.csiDriver.name }}/csi.sock
    extraArgs: []
    resources: null
  extraVolumes: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
csiProxy:
  enabled: true
  image:
    registry: docker.io/democraticcsi/csi-grpc-proxy
    tag: v0.5.6
  resources: null
enablePSP: false
storageClasses:
  - name: odin-nfsv3
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=3
      - hard
    secrets:
      provisioner-secret: null
      controller-publish-secret: null
      node-stage-secret: null
      node-publish-secret: null
      controller-expand-secret: null
  - name: odin-nfsv4
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4
      - hard
    secrets:
      provisioner-secret: null
      controller-publish-secret: null
      node-stage-secret: null
      node-publish-secret: null
      controller-expand-secret: null
volumeSnapshotClasses: []
driver:
  config:
    driver: zfs-generic-nfs
    zfs:
      datasetParentName: ClusterPool/zfs-generic-nfs
      detachedSnapshotsDatasetParentName: ClusterPool/zfs-generic-nfs-snapshots
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: '0775'
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareStrategy: setDatasetProperties
      shareStrategySetDatasetProperties:
        properties:
          sharenfs: 'on'
      shareHost: 10.16.6.2
    sshConnection:
      host: 10.16.6.2
      port: 22
      username: root
      privateKey: '-----BEGIN OPENSSH PRIVATE KEY-----
        -----END OPENSSH PRIVATE KEY-----
        '
```

test deployment manifest
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "9898"
    prometheus.io/scrape: "true"
  name: pod-info-deployment-c843ec4f
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: pod-info-Deployment-c8fa6694
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        cdk8s.io/metadata.addr: pod-info-Deployment-c8fa6694
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - ./podinfo
            - --port=9898
            - --level=info
          env:
            - name: PODINFO_UI_MESSAGE
              value: this is my podinfo message
          image: stefanprodan/podinfo:3.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/healthz
            failureThreshold: 3
            initialDelaySeconds: 1
            timeoutSeconds: 5
          name: main
          ports:
            - containerPort: 9898
          readinessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/readyz
            failureThreshold: 3
            initialDelaySeconds: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1500m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          startupProbe:
            failureThreshold: 3
            tcpSocket:
              port: 9898
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /test
              name: pvc-pod-info-claim-c8ec3cff
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: Always
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      setHostnameAsFQDN: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: data
        - name: pvc-pod-info-claim-c8ec3cff
          persistentVolumeClaim:
            claimName: pod-info-claim-c8ec3cff
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: pod-info-deployment-service-c8f0ebf8
spec:
  externalIPs: []
  ports:
    - port: 9898
      targetPort: 9898
  selector:
    cdk8s.io/metadata.addr: pod-info-Deployment-c8fa6694
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pod-info-deployment-service-ingress-c8658a6f
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: pod-info-deployment-service-c8f0ebf8
                port:
                  number: 9898
            path: /*
            pathType: Prefix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-info-claim-c8ec3cff
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: odin-nfsv3
  volumeMode: Filesystem
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pod-info-hpa-c8321a1a
spec:
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 300
          type: Pods
          value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 4
        - periodSeconds: 60
          type: Percent
          value: 200
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 100
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pod-info-deployment-c843ec4f
```

I already set `csiDriver.fsGroupPolicy: File` as it is described in #274 but the PV is mounted as root:root in the pods

```
$ k exec -ti pod-info-deployment-c843ec4f-f4bb5dbb8-c564q -- ls -lah /
total 69K    
drwxr-xr-x    1 root     root        4.0K Apr 21 19:31 .
drwxr-xr-x    1 root     root        4.0K Apr 21 19:31 ..
drwxr-xr-x    2 root     root        4.0K Aug 20  2019 bin
drwxrwsrwx    2 root     1000        4.0K Apr 21 19:31 data
drwxr-xr-x    5 root     root         360 Apr 21 19:31 dev
drwxr-xr-x    1 root     root        4.0K Apr 21 19:31 etc
drwxr-xr-x    1 root     root        4.0K Sep  5  2019 home
drwxr-xr-x    1 root     root        4.0K Sep  5  2019 lib
drwxr-xr-x    5 root     root        4.0K Aug 20  2019 media
drwxr-xr-x    2 root     root        4.0K Aug 20  2019 mnt
drwxr-xr-x    2 root     root        4.0K Aug 20  2019 opt
dr-xr-xr-x  500 root     root           0 Apr 21 19:31 proc
drwx------    2 root     root        4.0K Aug 20  2019 root
drwxr-xr-x    2 root     root        4.0K Aug 20  2019 run
drwxr-xr-x    2 root     root        4.0K Aug 20  2019 sbin
drwxr-xr-x    2 root     root        4.0K Aug 20  2019 srv
dr-xr-xr-x   13 root     root           0 Apr 21 19:31 sys
drwxrwxr-x    2 root     root           2 Apr 21 19:31 test    <--- This I'd expect to be drwxrwsr-x root:1000 
drwxrwxrwt    2 root     root        4.0K Aug 20  2019 tmp
drwxr-xr-x    1 root     root        4.0K Sep  5  2019 usr
drwxr-xr-x    1 root     root        4.0K Sep  5  2019 var
```
