### ISSUE TITLE
Question: external snapshotter with manually provisioned volumes?

### ISSUE THREAD

**Issue by dsw9742** [democratic-csi/democratic-csi#486]
Is it possible to use the external snapshotter with manually (pre-) provisioned persistent volumes?

I'm deploying cloudnative-pg in a homelab environment, with TrueNAS Core as the underlying storage platform. While I've managed to figure out how to deploy it using manually-provisioned iSCSI PV, cloudnative-pg's backup system depends on volume snapshots, and I am struggling to crack how to get that to work.

It appears there is more to this than just setting `externalSnapshotter.enabled: true`.

helm chart values for the driver:
```yaml
          controller: 
            externalAttacher:
              enabled: true
              resources:
                limits:
                  cpu: 50m
                  memory: 50Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
            externalProvisioner:
              enabled: false
            externalResizer:
              enabled: false
            externalSnapshotter:
              enabled: false
            driver:
              image: ghcr.io/democratic-csi/democratic-csi:latest
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 200m
                  memory: 200Mi
          node:
            driver:
              image: ghcr.io/democratic-csi/democratic-csi:latest
              resources:
                limits:
                  cpu: 200m
                  memory: 128Mi
                requests:
                  cpu: 200m
                  memory: 128Mi
            kubeletHostPath: /var/lib/kubelet
            # so we can mount PVCs to pods on control-plane nodes, since we aren't using worker nodes in this env
            tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
          csiDriver:
            name: org.democratic-csi.node-manual
            version: 1.5.0
          driver:
            config:
              driver: node-manual
```

yaml for pv:
```yaml
          kind: PersistentVolume
          apiVersion: v1
          metadata:
            name: clustername-1
            namespace: demo
          spec:
            capacity:
              storage: 1Gi
            accessModes: 
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Retain
            claimRef:
              name: clustername-1
              namespace: demo
            mountOptions:
              - discard
            storageClassName: ""
            csi:
              driver: org.democratic-csi.node-manual
              readOnly: false
              # can be ext4 or xfs
              fsType: xfs
              volumeHandle: pvc-clustername-1  # make sure it's a unique id in the cluster
              nodeStageSecretRef:
                name: node-manual-iscsi-secret
                namespace: demo
              volumeAttributes:
                portals: "192.168.106.127:3260,192.168.107.127:3260"
                iqn: "iqn.2005-10.org.freenas.ctl:clustername-1"
                lun: 0
                node_attach_driver: iscsi
                provisioner_driver: node-manual
```

cloudnative-pg creates the pvc using a pvcTemplate:
```yaml
...
              pvcTemplate:
                accessModes: 
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: ""
...
```
