### ISSUE TITLE
TrueNAS 25.04.0 - zfs and zpool commands not found

### ISSUE THREAD

**Issue by wbarnard81** [democratic-csi/democratic-csi#487]
Since upgrading my TrueNAS to version 25.04.0, it seems like I am unable to create a PVC:
This is the error I am getting.
`
failed to provision volume with StorageClass "freenas-nfs-fast": rpc error: code = Internal desc = Error: bash: line 1: /usr/local/sbin/zfs: No such file or directory Error: bash: line 1: /usr/local/sbin/zfs: No such file or directory at Object.zfsError (/home/csi/app/src/utils/zfs.js:78:16) at /home/csi/app/src/utils/zfs.js:1432:51 at EventEmitter.<anonymous> (/home/csi/app/src/utils/zfs.js:1611:11) at EventEmitter.emit (node:events:518:28) at Channel.<anonymous> (/home/csi/app/src/utils/zfs_ssh_exec_client.js:144:32) at Channel.emit (node:events:530:35) at Channel.doClose (/home/csi/app/node_modules/ssh2/lib/utils.js:101:21) at Object.onceWrapper (node:events:632:28) at Channel.emit (node:events:530:35) at endReadableNT (node:internal/streams/readable:1696:12)
`

On the TrueNAS server, if I run whereis zfs and zpool
`
zfs: /usr/sbin/zfs
zpool: /usr/sbin/zpool
`
and you cannot create symlinks on the TrueNAS server, as you will get these errors:
`
ln: failed to create symbolic link '/usr/local/sbin/zfs': Read-only file system
ln: failed to create symbolic link '/usr/local/sbin/zpool': Read-only file system
`

Now, I have tried various things with no success, even adding this to my values.yaml file.
`
      zfs:
        cli:
          paths:
          zfs: /usr/sbin/zfs
          zpool: /usr/sbin/zpool
`
Give me a new error:
`
failed to provision volume with StorageClass "freenas-nfs-fast": rpc error: code = Unknown desc = received error creating nfs share - code: 422 body: {"data.path":[{"message":"Field required","errno":22}],"data.paths":[{"message":"Extra inputs are not permitted","errno":22}],"data.alldirs":[{"message":"Extra inputs are not permitted","errno":22}],"data.quiet":[{"message":"Extra inputs are not permitted","errno":22}]}
`

I have tried to use the assistance of ChatGPT as well, but I am just not getting this to work. I know I might be doing something wrong, regarding specifying the correct path to use for those commands, but I just can't figure it out.

This is my current values.yaml file, before I started trying everything:
```yaml
democratic-csi:
  csiDriver:
    name: "org.democratic-csi.nfs-fast"

  storageClasses:
  - name: freenas-nfs-fast
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
        
    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    config:
      driver: freenas-nfs
      httpConnection:
        protocol: http
        host: 102.xxx.xxx.46
        port: 80
        apiKey: 1-randomstringgoeshere
        username: k3s-fast
        allowInsecure: true
        apiVersion: 2
      sshConnection:
        host: 102.xxx.xxx.46
        port: 22
        username: root
        privateKey: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          -----END OPENSSH PRIVATE KEY-----
      zfs:
        datasetParentName: RAIDZ2/rke2-nfs/vols
        detachedSnapshotsDatasetParentName: RAIDZ2/rke2-nfs/snaps
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        datasetPermissionsUser: 0
        datasetPermissionsGroup: 0
      nfs:
        shareHost: 102.xxx.xxx.46
        shareAlldirs: false
        shareAllowedHosts: []
        shareAllowedNetworks: []
        shareMaprootUser: root
        shareMaprootGroup: root
        shareMapallUser: ""
        shareMapallGroup: ""
```

**Comment by wbarnard81** [comment]
This is what I see looking at the code in the [democratic-csi repo](https://github.com/democratic-csi/democratic-csi/blob/master/examples/freenas-api-nfs.yaml):

![Image](https://github.com/user-attachments/assets/b9236968-e403-44a3-a336-950dcb134d0b)

And then I add that to my values file:

![Image](https://github.com/user-attachments/assets/27d8c8ee-238e-4b0b-9f00-cd9ef5d5997a)

But then I get this error:

![Image](https://github.com/user-attachments/assets/e7831eaa-2e87-4b1d-bdda-43a69e6fe823)

**Comment by travisghansen** [comment]
Can you try launching with the `next` image tag and set the `pullPolicy` to `Always` (it’s a mutable tag). There are a few 25.04 fixes in there.

**Comment by wbarnard81** [comment]
@perfectra1n Here you go.
`democratic-csi:
  csiDriver:
    name: "org.democratic-csi.nfs-fast"

  controller:
    # democratic-csi controller
    driver:
      image:
        registry: docker.io/democraticcsi/democratic-csi
        tag: next
        pullPolicy: Always
      logLevel: info
  node:
    # democratic-csi node
    driver:
      enabled: true
      image:
        registry: docker.io/democraticcsi/democratic-csi
        tag: next
        pullPolicy: Always
      logLevel: info

  storageClasses:
  - name: freenas-nfs-fast
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
        
    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    config:
      driver: freenas-nfs
      httpConnection:
        protocol: http
        host: xxx.xxx.xxx.xxx
        port: 80
        apiKey: 1-sometexthere
        username: k3s-fast
        allowInsecure: true
        apiVersion: 2
      sshConnection:
        host: xxx.xxx.xxx.xxx
        port: 22
        username: root
        privateKey: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          -----END OPENSSH PRIVATE KEY-----
      zfs:
        cli:
          sudoEnabled: true
          paths:
            zfs: /usr/sbin/zfs
            zpool: /usr/sbin/zpool
            sudo: /usr/bin/sudo
            chroot: /usr/sbin/chroot
        datasetParentName: RAIDZ2/rke2-nfs/vols
        detachedSnapshotsDatasetParentName: RAIDZ2/rke2-nfs/snaps
        datasetEnableQuotas: true
        datasetEnableReservation: false
        datasetPermissionsMode: "0777"
        datasetPermissionsUser: 0
        datasetPermissionsGroup: 0
      nfs:
        shareHost: xxx.xxx.xxx.xxx
        shareAlldirs: false
        shareAllowedHosts: []
        shareAllowedNetworks: []
        shareMaprootUser: root
        shareMaprootGroup: root
        shareMapallUser: ""
        shareMapallGroup: ""`

**Comment by perfectra1n** [comment]
It's all good, if you do triple ` above and below the last line of the code block, it should work. Single ` is for wrapping words in code formatting :)

**Comment by perfectra1n** [comment]
Ahhh, I figured it out. Thanks for posting the entire config - when you said:
> added the csi part back

You meant that you added the `cli` key back. It works after adding these sections:
```yaml
        driver:
          image:
            tag: next
            pullPolicy: Always

        controller:
          driver:
            image:
              registry: docker.io/democraticcsi/democratic-csi
              tag: next
              pullPolicy: Always
          replicaCount: 1

        node:
          driver:
            image:
              registry: docker.io/democraticcsi/democratic-csi
              tag: next
              pullPolicy: Always
```

Then under the `driver.config.zfs.cli` key (as your config above), the following values:
```yaml
    zfs:
      cli:
        sudoEnabled: true
        paths:
          zfs: /usr/sbin/zfs
          zpool: /usr/sbin/zpool
          sudo: /usr/bin/sudo
          chroot: /usr/sbin/chroot
```

Thanks again for sharing it and responding so quickly! That was driving me nuts :)
