### ISSUE TITLE
Upgrading to Talos 1.10 breaks iscsi

### ISSUE THREAD

**Issue by varet80** [democratic-csi/democratic-csi#488]
I have ugpraded to Talos 1.10 and I am running TrueNas 25.04

I am currently using the next images from democratic-csi.

the error I receive is on my node:
```
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-594966a1-50ce-44fd-8c57-16aa9eeb81c9-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver retry - waiting 2000ms before trying again
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-7b4dda46-000c-42ee-b47f-afb013b34ad3-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-32c509e9-cc09-452f-95e1-6acf25e2ce87-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver retry - waiting 2000ms before trying again
csi-driver retry - waiting 2000ms before trying again
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-551aaa44-18e1-4431-80e4-35fea33ca7a7-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver retry - waiting 2000ms before trying again
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-e2d3296c-37d2-4bae-ba55-e834f3ac2c63-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver retry - waiting 2000ms before trying again
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-594966a1-50ce-44fd-8c57-16aa9eeb81c9-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver retry - waiting 2000ms before trying again
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-7b4dda46-000c-42ee-b47f-afb013b34ad3-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-32c509e9-cc09-452f-95e1-6acf25e2ce87-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver {"host":"pluton","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":1,\"stdout\":\"\",\"stderr\":\"failed to find iscsid pid for nsenter\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2025-05-18T20:05:10.859Z"}
csi-driver {"host":"pluton","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":1,\"stdout\":\"\",\"stderr\":\"failed to find iscsid pid for nsenter\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2025-05-18T20:05:10.897Z"}
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-551aaa44-18e1-4431-80e4-35fea33ca7a7-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver {"host":"pluton","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":1,\"stdout\":\"\",\"stderr\":\"failed to find iscsid pid for nsenter\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2025-05-18T20:05:11.018Z"}
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-e2d3296c-37d2-4bae-ba55-e834f3ac2c63-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver {"host":"pluton","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":1,\"stdout\":\"\",\"stderr\":\"failed to find iscsid pid for nsenter\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2025-05-18T20:05:11.242Z"}
csi-driver executing iscsi command: iscsiadm -m node -T iqn.2005-10.org.freenas.ctl:csi-pvc-594966a1-50ce-44fd-8c57-16aa9eeb81c9-k8scluster -p 10.10.0.xxx:3260 -o new
csi-driver {"host":"pluton","level":"error","message":"handler error - driver: FreeNASApiDriver method: NodeStageVolume error: {\"code\":1,\"stdout\":\"\",\"stderr\":\"failed to find iscsid pid for nsenter\\n\",\"timeout\":false}","service":"democratic-csi","timestamp":"2025-05-18T20:05:12.339Z"}
```

My helmchart config is:

```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"
  storageCapacity: true
node:
  tolerations:
    - effect: NoSchedule
      operator: Exists
  hostPID: true
  hostIPC: true
  driver:
    extraEnv:
      - name: ISCSIADM_HOST_STRATEGY
        value: nsenter
      - name: ISCSIADM_HOST_PATH
        value: /usr/local/sbin/iscsiadm
    iscsiDirHostPath: /var/lib/iscsi
    iscsiDirHostPathType: ""
    image:
      tag: next
controller:
  hostPID: true
  hostIPC: true
  tolerations:
    - effect: NoSchedule
      operator: Exists
  driver:
    image:
      tag: next
storageClasses:
- name: freenas-iscsi-csi
  defaultClass: true
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
  parameters:

    fsType: ext4


    detachedVolumesFromSnapshots: "true"


    detachedVolumesFromVolumes: "true"

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
      node-db.node.session.auth.authmethod: CHAP
      node-db.node.session.auth.username: cxxxxxxxxxxxx
      node-db.node.session.auth.password: wxxxxxxxxxxxxxxxxxx
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses:
- name: freenas-iscsi-csi
  parameters:
    # if true, snapshots will be created with zfs send/receive
    detachedSnapshots: "true"

driver:
  config:
    driver: freenas-api-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: 10.10.0.xxx
      port: 443
      apiKey: xxxxxxxxxxxxxxxxxN0
      allowInsecure: true
    zfs:
      datasetParentName: data/pv/vols
      detachedSnapshotsDatasetParentName: Main/democraticCsi/
      zvolCompression: lz4
      zvolDedup: off
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "10.10.0.xxx:3260"
      interface:

      namePrefix: csi-
      nameSuffix: "-k8scluster"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: CHAP
          targetGroupAuthGroup: 1

      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
```

I am not able to mount anymore volumes and I cannot find the reason for
