### ISSUE TITLE
Permission denied to resize PVC iSCSI

### ISSUE THREAD

**Issue by Tuurkevg** [democratic-csi/democratic-csi#491]
```
Hi, I'm trying to expand a PVC, but I'm getting a "permission denied" error. It seems the democratic-csi-node does not have sufficient permissions to perform the operation.

Does anyone know what I did wrong or how to fix this?
descibe pods:
│ Events:                                                                                                                                                                                                                                                                    ││   Type     Reason       Age   From               Message                                                                                                                                                                                                                   ││   ----     ------       ----  ----               -------                                                                                                                                                                                                                   ││   Normal   Scheduled    6s    default-scheduler  Successfully assigned elastic-system/elasticsearch-es-hot-0 to excgenk8s003                                                                                                                                               ││   Warning  FailedMount  2s    kubelet            MountVolume.MountDevice failed for volume "pvc-bb39aa6a-4bf4-42d9-a386-0aad9e0b484a" : rpc error: code = Internal desc = {"code":1,"stdout":"Filesystem at /dev/sdi is mounted on /var/lib/kubelet/plugins/kubernetes.io/ ││ csi/iscsi-csi/8f2d3c13bec10fc0a7df5d3ead849995090507ae6947bcd76c37c46599fc8af6/globalmount; on-line resizing required\nold_desc_blocks = 128, new_desc_blocks = 256\n","stderr":"resize2fs 1.47.0 (5-Feb-2023)\nresize2fs: Permission denied to resize filesystem\n","time ││ out":false}     



```
My helm release:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  chart:
    spec:
      chart: democratic-csi
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      version: 0.15.0 # Adjust the version as necessary
  install:
    createNamespace: true
  interval: 120m
  releaseName: democratic-csi
  targetNamespace: democratic-csi
  upgrade:
    crds: CreateReplace
  values:
    csiDriver:
      # should be globally unique for a given cluster
      name: "iscsi-csi"
    node:
      mount:
        # predominantly used to facilitate testing
        # mount_flags should generally be defined in storage classes, etc
        mount_flags: ""
        # should fsck be executed before mounting the fs
        checkFilesystem:
          xfs:
            enabled: true
            customOptions: []
          ext4:
            enabled: true
            customOptions: []
            customFilesystemOptions: []
          btrfs:
            enabled: true
            customOptions: []
            customFilesystemOptions: []    
    storageClasses:
      - name: freenas-iscsi-csi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          # for block-based storage can be ext3, ext4, xfs
          # for nfs should be nfs
          fsType: ext4
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
            node-db.node.session.auth.authmethod: "CHAP"
            node-db.node.session.auth.username: "xxx"
            node-db.node.session.auth.password: "xxx!"
        #
        # Additional secrets or options can be added as needed.

    driver:
      config:
        driver: freenas-iscsi
        instance_id:
        httpConnection:
          protocol: https
          host: 10.1.2.199
          port: 443
          username: xxx
          password: xxx
          allowInsecure: true    
        sshConnection:
          host: "10.1.2.199"
          port: 22
          username: "xxx"
          password: "xxxx"
        zfs:
          cli:
            sudoEnabled: true
          datasetParentName: NewPool/k8sdata/v
          detachedSnapshotsDatasetParentName: NewPool/k8sdata/s
          zvolCompression: ""
          zvolDedup: ""
          zvolEnableReservation: false
          zvolBlocksize: 16K
        iscsi:
          targetPortal: "10.1.2.199:3260"
          interface:
            namePrefix: csi-
            nameSuffix: "-cluster"
          targetGroups:
            - targetGroupPortalGroup: 3
              targetGroupInitiatorGroup: 12
              targetGroupAuthType: CHAP
              targetGroupAuthGroup: 2
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          extentBlocksize: 4096
          extentRpm: "7200"
          extentAvailThreshold: 0
    volumeSnapshotClasses: []


    controller:
      enabled: true
      driver:
        enabled: true      
        securityContext:
             allowPrivilegeEscalation: true
             capabilities:
               add:
               - SYS_ADMIN
             privileged: true
```
