### ISSUE TITLE
Problems with iSCSI/Truenas 25.04.1

### ISSUE THREAD

**Issue by Venthe** [democratic-csi/democratic-csi#495]
Hey;
I'm trying to connect to iSCSI. NFS works fine. Could you please take a look what might be a problem?

Logs from democratic-csi/democratic-csi-iscsi-controller-7677f558b-5l7qd:csi-driver
```jsonc
{"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"debug","message":"FREENAS HTTP REQUEST DETAILS: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi  -driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":60000,\"method\":\"POST\",\"url\":\"https://172.22.2.1/api/v2.0/pool/dataset\",\"data\":{\"refreservation\":0,\"volblocksize\":\"16K\",\"type\":\"VOLUME\",\"volsize\":1073741824,\"sparse\":true,\"create_ancestors\":true,\"share_type\":\"GENERIC\",\"user_properties\":[{\"key\":\"democratic-csi:csi_volume_name\",\"value\":\"pvc-5f52b4af-6b1a-475f-b52e-03dce7bd11d8\"},{\"key\":\"democratic-csi:managed_resource\",\"value\":\"true\"},{\"key\":\"democratic-csi :volume_context_provisioner_driver\",\"value\":\"freenas-api-iscsi\"},{\"key\":\"democratic-csi:volume_context_provisioner_instance_id\",\"value\":\"abcd-efgh2\"}],\"name\":\"main/k8s/iscsi/backup/pvc-5f52b4af-6b1a-475f-b52e-03dce7bd11d8\"}}","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}
 {"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"debug","message":"FREENAS HTTP REQUEST DURATION: 0.42s","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}

{"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"debug","message":"FREENAS HTTP ERROR: null","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}

{"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"debug","message":"FREENAS HTTP RESPONSE STATUS CODE: 422","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}

{"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"debug","message":"FREENAS HTTP RESPONSE HEADERS: {\"server\":\"nginx\",\"date\":\"Wed, 25 Jun 2025 23:59:11 GMT\",\"content-type\":\"application/json; charset=utf-8\",\"content-length\":\"124\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=63072000; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}

{"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"debug","message":"FREENAS HTTP RESPONSE BODY: {\"pool_dataset_create.name\":[{\"message\":\"main/k8s/iscsi: parent may not be a ZFS volume\",\"errno\":22}]}","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}

{"host":"democratic-csi-iscsi-controller-7677f558b-5l7qd","level":"error","message":"handler error - driver: FreeNASApiDriver method: CreateVolume error: Error: {\"pool_dataset_create.name\":[{\"message\":\"main/k8s/iscsi: parent may not be a ZFS volume\",\"errno\":22}]} Error: {\"pool_dataset_create.name\":[{\"message\":\"main/k8s/iscsi: parent may not be a ZFS volume\",\"errno\":22}]}\n    at Api.DatasetCreate (/home/csi/app/src/driver/freenas/http/api.js:341:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async FreeNASApiDriver.CreateVolume (/home/csi/app/src/driver/freenas/api.js:2797:7)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:248:18)","service":"democratic-csi","timestamp":"2025-06-25T23:59:11.414Z"}                                                                                         
```

Helm values:
```yaml
csiDriver:
  name: "org.democratic-csi.iscsi"
controller:
  driver:
    logLevel: debug
    image:
      tag: next
node:
  driver:
    logLevel: debug
    iscsiDirHostPath: /var/iscsi
storageClasses:
- name: iscsi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: ext4
    detachedVolumesFromSnapshots: "false"
  mountOptions: []
driver:
  image:
    tag: next
  config:
    driver: freenas-api-iscsi
    instance_id: abcd-efgh2
    httpConnection:
      protocol: "{{ driver_connection_http_protocol }}"
      host: "{{ driver_connection_host }}"
      port: {{ driver_connection_http_port }}
      apiKey: "{{ driver_connection_http_api_key }}"
      allowInsecure: true
    zfs:
      datasetParentName: main/k8s/iscsi/backup
      detachedSnapshotsDatasetParentName: main/k8s/iscsi/snapshots
    iscsi:
      targetPortal: "{{ driver_connection_host }}:3260"
      targetPortals: [] 
      # interface:
      namePrefix: csi-
      nameSuffix: "-clustera"
      targetGroups:
        - targetGroupPortalGroup: 1
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "7200"
      extentAvailThreshold: 0
```

And the Truenas:

![Image](https://github.com/user-attachments/assets/91b87443-c0a3-41a3-b44e-c1db16cf4acc)

![Image](https://github.com/user-attachments/assets/c412445f-eaad-4cee-97ab-29a7b0e2e708)

I've tried following https://github.com/fenio/k8s-truenas guide; but you no longer cannot share dataset as iSCSI, and you cannot nest ZVOL's.

I've tried to set `driver.config.zfs.datasetParentName: main/k8s/iscsi` to no avail

Additionally; before I've upgraded to next (and the newest truenas) the error was a non-descriptive `null not allowed`
