### ISSUE TITLE
[Bug] Truenas shutdown breaks zfs-generic-nvmeof pvc remounts

### ISSUE THREAD

**Issue by jitteryjuice** [democratic-csi/democratic-csi#496]
Hello,

I am running Talos 1.10.4, with kubernetes 1.33.2 on a 3 node cluster (1 control plane, 2 workers).

I am currently using zfs-generic-nvmeof against Truenas 25.04.1. During a rack reorder, i accidentally shutdown my Truenas box (the power button shouldnt be that easy to press...).

I immediately started it back up, but volumes were failing to reattach, even with a pod recreate. I jumped onto my truenas box, and looked at the subsystems available by nvmetcli, and there was none. I verified connectivity from my node to Truenas via SSH and it was working as expected. The PVC's in Kubernetes remained bound, and persisted on truenas as expected.

I have tried restarting the democratic-csi node controllers, and the controller itself to no avail. I also tried deleting and recreating the storage class and redeploying which also didnt work.

Finally, i used the detached volume snapshot functionality on the existing PVC which worked as expected. From there, i was able to delete my existing PVC (which deleted in truenas), and restore a new PVC from the snapshot. This was created, bound and mounted as expected.

Typically i wouldn't expect to shutdown truenas while volumes are mounted, however i would hope it could restore state once the transport/truenas node is back up.

My initial gut feeling is democratic-csi lost a mapping, and was failing to create the subsystems.

This is the current state of my nvmetcli ls on truenas (with the volumes that were deleted and recreated via snapshot:
```
o- / ......................................................................................................................... [...]
  o- hosts ................................................................................................................... [...]
  o- ports ................................................................................................................... [...]
  | o- 1 ........................................................ [trtype=tcp, traddr=0.0.0.0, trsvcid=4420, inline_data_size=16384]
  |   o- ana_groups .......................................................................................................... [...]
  |   | o- 1 ..................................................................................................... [state=optimized]
  |   o- referrals ........................................................................................................... [...]
  |   o- subsystems .......................................................................................................... [...]
  |     o- nqn.truenas-micro.my.domain:pvc-97c008e3-714b-438f-b7d7-be6432da7cfd ........................................... [...]
  |     o- nqn.truenas-micro.my.domain:pvc-b1eecc85-b99a-4bbb-af65-f7b8bbb73d5b ........................................... [...]
  |     o- nqn.truenas-micro.my.domain:pvc-c5033428-a218-4b4a-b134-b468d3bc8205 ........................................... [...]
  |     o- nqn.truenas-micro.my.domain:pvc-f81f11fc-491b-495d-a399-12dc7dc77bc4 ........................................... [...]
  o- subsystems .............................................................................................................. [...]
    o- nqn.truenas-micro.my.domain:pvc-97c008e3-714b-438f-b7d7-be6432da7cfd  [version=1.3, allow_any=1, serial=722dc02207b555fcef6f]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 1  [path=/dev/zvol/nvme/k8s/volumes/pvc-97c008e3-714b-438f-b7d7-be6432da7cfd, uuid=a33afd0e-ba07-44ed-a5c3-29e4c469678a, grpid=1, enabled]
    o- nqn.truenas-micro.my.domain:pvc-b1eecc85-b99a-4bbb-af65-f7b8bbb73d5b  [version=1.3, allow_any=1, serial=f83a9ff9d33b6a077ea1]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 1  [path=/dev/zvol/nvme/k8s/volumes/pvc-b1eecc85-b99a-4bbb-af65-f7b8bbb73d5b, uuid=2e982ed2-3614-413a-a126-85aa47653597, grpid=1, enabled]
    o- nqn.truenas-micro.my.domain:pvc-c5033428-a218-4b4a-b134-b468d3bc8205  [version=1.3, allow_any=1, serial=88d971839c1bba8ddb66]
    | o- allowed_hosts ....................................................................................................... [...]
    | o- namespaces .......................................................................................................... [...]
    |   o- 1  [path=/dev/zvol/nvme/k8s/volumes/pvc-c5033428-a218-4b4a-b134-b468d3bc8205, uuid=9e422d31-1cfc-4293-8baf-927d79ff63bd, grpid=1, enabled]
    o- nqn.truenas-micro.my.domain:pvc-f81f11fc-491b-495d-a399-12dc7dc77bc4  [version=1.3, allow_any=1, serial=950b13c325372507e45a]
      o- allowed_hosts ....................................................................................................... [...]
      o- namespaces .......................................................................................................... [...]
        o- 1  [path=/dev/zvol/nvme/k8s/volumes/pvc-f81f11fc-491b-495d-a399-12dc7dc77bc4, uuid=5994793d-547c-4b52-b409-a2186ca771a0, grpid=1, enabled]
```

The following are my values:

```
csiDriver:
# should be globally unique for a given cluster
name: "org.democratic-csi.zfs-nvmeof"
# controller:
#   driver:
#     logLevel: debug
# node:
#   driver:
#     logLevel: debug
driver:
  config:
    driver: zfs-generic-nvmeof
    sshConnection:
      host: x.x.x.x
      port: 22
      username: root
      password: mysupadupasecretpassword
    zfs:
      # can be used to set arbitrary values on the dataset/zvol
      # can use handlebars templates with the parameters from the storage class/CO
      datasetProperties:
        "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

      datasetParentName: nvme/k8s/volumes
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      detachedSnapshotsDatasetParentName: nvme/k8s/snapshots

      # "" (inherit), lz4, gzip-9, etc
      zvolCompression:
      # "" (inherit), on, off, verify
      zvolDedup:
      zvolEnableReservation: true
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:

    nvmeof:
      # these are for the node/client aspect
      transports:
        - tcp://x.x.x.x:4420
      shareStrategy: "nvmetCli"
      shareStrategyNvmetCli:
        #sudoEnabled: true
        nvmetcliPath: /root/.local/bin/nvmetcli
        # prevent startup race conditions by ensuring the config on disk has been imported
        # before we start messing with things
        configIsImportedFilePath: /var/run/nvmet-config-loaded
        configPath: /mnt/nvme/nvmet-config.json
        basename: "nqn.truenas-micro.my.domain"
        # add more ports here as appropriate if you have multipath
        ports:
          - "1"
        subsystem:
          attributes:
            allow_any_host: 1

storageClasses:
  - name: truenas-nvme
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: xfs
      # this uses inline zfs snapshots
      detachedVolumesFromSnapshots: "false"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:
  - name: truenas-nvme-detached
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: xfs
      # detached volumes are created with zfs send/receive
      detachedVolumesFromSnapshots: "true"
    mountOptions: []
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

volumeSnapshotClasses:
  - name: truenas-nvme
    parameters:
      detachedSnapshots: "false"
  - name: truenas-nvme-detached
    parameters:
      detachedSnapshots: "true"
```

And the relevant csi-node controller logs:
```
csi-driver {"host":"tk8sn01","level":"info","message":"new request - driver: ControllerZfsGenericDriver method: NodeStageVolume call: {\"path\":\"/csi.v1.Node/NodeStageVolume\",\"metadata\":{},\"request\":{\"publish_context\":{},\"secrets\":\"redacted\",\"volume_context\":{\"node_attach_driver\":\"nvmeof\",\"nqn\":\"nqn.truenas-micro.my.domain:pvc-a806b355-e8b6-4f09-beba-8e77c1f581f2\",\"nsid\":\"1\",\"provisioner_driver\"
:\"zfs-generic-nvmeof\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1747455391627-5816-org.democratic-csi.zfs-nvmeof\",\"transport\":\"\",\"transports\":\"tcp://x.x.x.x:4420\"},\"volume_id\":\"pvc-a806b355-e8b6-4f09-beba-8e77c1f581f2\",\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/org.democratic-csi.zfs-nvmeof/e75c7cd109749d6df2b5401637fd3d068a33ff9e0b708181825d0f36c60b66d9/globalmount\",\"v
olume_capability\":{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[],\"fs_type\":\"xfs\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2025-06-29T03:36:20.710Z"}
csi-driver retry - waiting 2000ms before trying again
csi-driver {"host":"tk8sn01","level":"warn","message":"error: {\"code\":1,\"stdout\":\"\",\"stderr\":\"Failed to write to /dev/nvme-fabrics: Input/output error\\ncould not add new controller: failed to write to nvme-fabrics device\\n\",\"timeout\":false} connecting to transport: tcp://x.x.x.x:4420","service":"democratic-csi","timestamp":"2025-06-29T03:36:49.371Z"}
csi-driver {"host":"tk8sn01","level":"info","message":"new request - driver: ControllerZfsGenericDriver method: Probe call: {\"path\":\"/csi.v1.Identity/Probe\",\"metadata\":{},\"request\":{},\"pendingStatus\":{\"code\":0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2025-06-29T03:36:50.230Z"}
csi-driver {"host":"tk8sn01","level":"info","message":"new response - driver: ControllerZfsGenericDriver method: Probe response: {\"ready\":{\"value\":true}}","service":"democratic-csi","timestamp":"2025-06-29T03:36:50.231Z"}
csi-driver {"host":"tk8sn01","level":"error","message":"handler error - driver: ControllerZfsGenericDriver method: NodeStageVolume error: {\"name\":\"GrpcError\",\"code\":2,\"message\":\"unable to attach any nvme devices\"}","service":"democratic-csi","timestamp":"2025-06-29T03:36:51.373Z"}

```

If you need more information, please let me know and im happy to provide further logs.

![Image](https://github.com/user-attachments/assets/80976aa4-55c2-4bf1-aa96-5f37806fff6f)
![Image](https://github.com/user-attachments/assets/e226a83a-e000-49ce-af87-bdb6cccfd9db)
![Image](https://github.com/user-attachments/assets/269ff307-cda1-4f92-97e4-d549484d709f)
