### ISSUE TITLE
error loading shared libraries: libatomic.so.1

### ISSUE THREAD

**Issue by eamonryan** [democratic-csi/democratic-csi#51]
Hi there!

I'm trying to get this going on a RPi4 k3s cluster running Raspbian / RPi OS.

So far I've gotten over a few hurdles including swapping some of the container images for arm64 compatible ones and it seems only the democraticcsi/democratic-csi images are now having trouble running, this one is already arm64 compatible so I haven't changed its reference.

Each of them (one on each node plus the controller instance), is crashing with the same error:

`│ node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory       │`

The underlying OS does have libatomic1 installed already, at wherever Raspbian/RPi OS installs it, though I'm not sure that's relevant since maybe it tries to reference the container filesystem for it.

Happy to provide any other info that can help, I suppose it's possible it's just a bad error message and the problem lies elsewhere!

**Comment by travisghansen** [comment]
Interesting! I’d be interested in knowing what you needed to modify as I have updated the chart etc where arm should work out the box (indeed I’m running it on a pi4 with ubuntu arm64).

You’re for sure running the 64 bit raspbian? I’ll have to fire it up I suppose and see what I get.

**Comment by eamonryan** [comment]
Sure, I ended up adding this to my values.yaml:

```
controller:
  externalProvisioner:
    image: raspbernetes/csi-external-provisioner
  externalResizer:
    image: raspbernetes/csi-external-resizer
  externalSnapshotter:
    image: raspbernetes/csi-external-snapshotter
node:
  driverRegistrar:
    image: raspbernetes/csi-node-driver-registrar
```
If I don't, then I get `ImagePullBackOff` for each of the above with events that look like:

`Failed to pull image "k8s.gcr.io/sig-storage/csi-resizer:v1.0.1": rpc error: code = Unknown desc = no matching manifest for linux/arm/v8 in the manifest list entries`

I only tried to deploy this yesterday so I should have the latest everything.

and here's uname output for one of the Pis. so you can see it's 64bit:
```
$ uname -a
Linux pi02 5.4.79-v8+ #1373 SMP PREEMPT Mon Nov 23 13:32:41 GMT 2020 aarch64 GNU/Linux
```

**Comment by travisghansen** [comment]
What are you using for the k8s distro? None of that should be necessary with the latest chart version.

**Comment by travisghansen** [comment]
Yeah something seems really off with the install. I don’t see any images supporting `linux/arm/v8`. Typically it’s either `linux/arm64/v8` or even `linux/arm64` but never that.

Is that running a 64bit kernel with a 32bit userland?

**Comment by travisghansen** [comment]
Also can you see what the sha digest is for the image it downloaded for this project? Interested to know which image it pulled down and is trying to use.

**Comment by eamonryan** [comment]
> What are you using for the k8s distro? None of that should be necessary with the latest chart version.

I'm using https://k3s.io/ - specifically v1.18.8+k3s1 - https://github.com/k3s-io/k3s/releases/tag/v1.18.8+k3s1

> Yeah something seems really off with the install. I don’t see any images supporting `linux/arm/v8`. Typically it’s either `linux/arm64/v8` or even `linux/arm64` but never that.

I see some others reporting a similarly weird symptom in places like [here](https://github.com/moby/moby/issues/40141) and [here](https://forum.pine64.org/showthread.php?tid=8066&pid=55042#pid55042) but no resolutions posted.

[This one](https://github.com/moby/moby/issues/34875) might also be related, though it's not about armv7 not armv8 but the symptoms look pretty similar, there is more information on this one, it looks like on some of these systems like Rpis and Rock64s and such, the auto-detect behaves like this on multi-arch images and can't find a match. Really strange.

> Is that running a 64bit kernel with a 32bit userland?

I'm not 100% sure how I would verify that, but not as far as I know, no. I've had no issues with any docker image made for arm64 so far (even multiarch ones).

> Also can you see what the sha digest is for the image it downloaded for this project? Interested to know which image it pulled down and is trying to use.

Sure, hope this is what you wanted:
```
csi-driver:                                                                                                        
  Container ID:  docker://027b6ef932c6703a7039902e43db03373fd9781a596bb6bc22736af1c40f8371                  
  Image:         democraticcsi/democratic-csi:latest                                                        
  Image ID:      docker-pullable://democraticcsi/democratic-csi@sha256:c7a86279260fac956a7f21d8316c567c7459f8f597994a7480969fa8bf4cffbc
```

**Comment by travisghansen** [comment]
I’ll read through the links when I get a moment. In the mean time that sha doesn’t seem to match any of the images currently tagged in dockerhub. If you know how to pin a specific sha go ahead and try that out with both the v7 and arm64 v8 shas and see what you get.

Is it even an option to try the 64bit ubuntu and see what you get?

How did you install the 64bit raspbian? Did you download the special iso or just hack the config.txt?

**Comment by eamonryan** [comment]
> I’ll read through the links when I get a moment. In the mean time that sha doesn’t seem to match any of the images currently tagged in dockerhub. If you know how to pin a specific sha go ahead and try that out with both the v7 and arm64 v8 shas and see what you get.

I'll try and let you know - apparently I've hit the new dockerhub pull limit already though so will have to wait a bit.

> Is it even an option to try the 64bit ubuntu and see what you get?

While my trying of this project is new, the cluster is not, it's running a number of workloads already (via nfs-client-provisioner for storage) so ideally I'd like to not take it out of commission. I don't have a spare Pi4 lying around to just try a microk8s or similar on right now sadly.

> How did you install the 64bit raspbian? Did you download the special iso or just hack the config.txt?

You know, I couldn't remember for a bit since the OS parts were installed last year sometime! I checked my notes and some saved articles and found that yes I did the config.txt method - adding `arm_64bit=1` to it.

I believe the special 64-bit beta build didn't exist when I first was working on this cluster, so didn't use it.

My understanding is that the rootfs is still 32-bit in that case, so maybe that is causing the slight difference here?

**Comment by eamonryan** [comment]
I have some new info after testing some things, and some progress :)

So, on the arch stuff, it seems like GCR is bad at handling the use case of Raspbian with 64-bit kernel enabled, it gets detected as `linux/arm/v8` but it doesn't make that last step and serve the relevant arm64 image if the image being requested is multi-arch.

Dockerhub seems to behave differently, in most cases (indeed all cases before this one), if I tried to pull `latest` for a multi-arch image it would pull down the arm64 image just fine.

In this specific case, for your main democratic-csi image, I don't know where it got the SHA of `c7a86279260fac956a7f21d8316c567c7459f8f597994a7480969fa8bf4cffbc` from but all I can think of is it's some much older build from earlier days in this project.

I added overrides to my values.yaml for the driver image now too to specify the arm64 SHA of the latest image:

```
controller:
  driver:
    image: democraticcsi/democratic-csi@sha256:278565d7b9a54cd1ba189d02de6303f95dd8de41a0e8f330449f05e7186057bb
  externalProvisioner:
    image: raspbernetes/csi-external-provisioner
  externalResizer:
    image: raspbernetes/csi-external-resizer
  externalSnapshotter:
    image: raspbernetes/csi-external-snapshotter
node:
  driver:
    image: democraticcsi/democratic-csi@sha256:278565d7b9a54cd1ba189d02de6303f95dd8de41a0e8f330449f05e7186057bb
  driverRegistrar:
    image: raspbernetes/csi-node-driver-registrar
```

And now it works! 
![image](https://user-images.githubusercontent.com/11842311/104644430-9dd99c00-5662-11eb-91ba-8e3f946c27c0.png)

Well it starts at least, I haven't actually tested the functionality yet, but I've certainly gotten past the problem I had when opening this issue.
