### ISSUE TITLE
Unable to mount volume after node reboot

### ISSUE THREAD

**Issue by MarkLFT** [democratic-csi/democratic-csi#85]
I recently had to shutdown the entire k8s cluster.  Prior to shutting it down, all pods/volumes etc were working correctly.  However following the reboot, one of the deployments fails to start as it is unable to mount the pvc volume.

The error message is
`MountVolume.MountDevice failed for volume "pvc-3f761acf-262b-40ba-8b06-f76f205c70a4" : rpc error: code = Internal desc = {"code":1,"stdout":"Couldn't find valid filesystem superblock.\n","stderr":"resize2fs 1.44.5 (15-Dec-2018)\nresize2fs: Superblock checksum does not match superblock while trying to open /dev/sdb\n"}`

As I wrote, all I did was take the cluster down, and then restart it.  All other deployments have come back as expected.  Including others using PVCs on the same NAS unit.

There are no obvious errors on the NAS unit.

Do you have any idea of the cause of this, and more importantly, given that I cannot start the deployment, how can I repair this?

Thanks

**Comment by MarkLFT** [comment]
Latest build, cant see the version currently as not in the office. But it was updated a few days ago.

But no issues with the update until this.

**Comment by MarkLFT** [comment]
Ok, I am back in the office, our TrueNAS version is TrueNAS-12.0-U3.1.

**Comment by travisghansen** [comment]
Yeah ok but based on 12 with the new openzfs code base.

I’ve been fortunate so far in that I’ve been able to run `fsck` on the drives and have them repair just fine.

So what I do:

- find the node where the workload has been scheduled
- ssh directly to the node and run `umount /dev/sdX` however many times is necessary to make sure the device is completely unmounted (usually twice)
- exec into the corresponding `node` pod from the `democratic-csi` deployment (the pod/container that generated the error message) and once there I manually run the `fsck.ext4 /dev/sdX` command and let it run the fs repair
- delete the pod and let it reschedule
  - if it gets scheduled to a different node, I manually logout of the target on the original node and delete the ‘db’ entry for the taget from the node as well

**Comment by MarkLFT** [comment]
That fixed it for me.

Many thanks.

**Comment by MarkLFT** [comment]
Great, that would be helpful.  As you can imagine, losing the database of our pods is not a good thing, and certainly get the heart rate up. ;-)

**Comment by travisghansen** [comment]
Yeah, agreed 100%! I'm going to re-open this so we both have something to follow-up with and keep communication going.

**Comment by MarkLFT** [comment]
This has happened to me again.  Exactly the same symptoms.   But this time when I try your suggestion to repair the drive, I receive a warning that the /dev/sdc is in use.   

I ran the umount several times and it is reporting that it is unmounted.  Any ideas what may be preventing me from running the fsck command?

I have searched the internet, but am unable to find a solution that works.

Thanks.

PS.  Did you get anywhere in following up with this with the iX team?

**Comment by travisghansen** [comment]
I haven’t sat to address this very specifically yet. I also haven’t seen similar issues for some time (I may have updated the nas but it appears you’re already on the latest anyhow).

Regarding the still mounted drive I’m not sure there. You could check the sessions server side (although I’m not sure how much good that will do) and make sure you don’t have multiple from the same node or even other nodes to the same target.

**Comment by solidDoWant** [comment]
I'm starting to get this pretty often with zfs iscsi. What can I do to debug the issue? I'll submit a PR if I can find the root cause

**Comment by travisghansen** [comment]
I don’t know if this is an issue with truenas or not still :( I haven’t seen it in a long time.

I have a massive set of updates queued up for a new release and one of the things reintroduced is a config option to run fsck on attach/mount again. Maybe that will at least help alleviate the associated headaches.

**Comment by solidDoWant** [comment]
Ha - I just got done writing some shell scripts to run fsck and it fixed a lot of my issues. Looking forward to having that built in.

To anybody else googling that comes across this issue: In my case I've had a lot of problems with my PVCs with the exact error and I think I've narrowed it down to two causes with some workarounds:
1. A pod doesn't finish terminating before it's replacement starts creating. As a result, they both fight over who can write to the disk, causing problems. As a workaround, after deleting a pod in a deployment, delete it again after the first instance terminates. The second instance won't be able to start due to not being able to mount the volume properly, but the third start properly as neither the second or (terminated) first pod have the volume mounted. @travisghansen is there any way the CSI could keep new pods in a pending state while another pod has an isci-backed volume mounted? I think that'd solve this issue.
2. The PVC becomes corrupted. In my case I _think_ it's because I have two drives in my zpool starting to fail. To fix, I did the following each time (scripted)
  a. Snapshot the failing volume on the ZFS host
  b. Clone the snapshot into a new volume
  c. Run fsck on the new volume
  d. Create a repair snapshot of the new volume
  e. Send the repair snapshot to the failing volume
  f. Rollback the repair snapshot on the failing voluem
  g. Cleanup the created snapshots/repair volume

**Comment by travisghansen** [comment]
In csi parlance it’s the job of the container orchestrator (CO…usually k8s) to ensure the volume isn’t mounted on 2 nodes simultaneously. In short it’s generally considered outside the scope of csi ‘drivers’ to handle that aspect.

The ability to allow operators to turn on/off fsck is in this commit: https://github.com/democratic-csi/democratic-csi/commit/f6f637ebe7e1eec63bc540f1446baa7919d3b32f

I haven’t committed the relevant documentation but will put it here for others to see.

**Comment by travisghansen** [comment]
Due to some recent power issues I’ve seen this more than I care recently. What I’ve discovered is:

- the fs is not unmounted cleanly
- We later proceed with a mount when the workload is scheduled etc
- The mount is clean and seemingly rw
- However issuing a resize on the fs without a clean unmount fails (I issue a resize command on ever mount on purpose atm…there are several reasons for doing so)

If I simply unmount the fs manually on the target node and wait everything comes back up eventually/shortly on its own. I’m still unclear whether an fs check before the initial mount will resolve the issue on its own but regardless I will probably put code in to handle this case specifically and more gracefully handle the scenario without the need to enable fs checks (upstream fs folks recommend against automatic fs checks for whatever reasons).

I am very close to snapping a new release with many updates and I’ll make sure a solution for this lands before doing so.

**Comment by travisghansen** [comment]
OK, I've confirmed that the `fsck` feature when enabled cleans this particular issue up. As a reference when enabled the default command executed for `ext4` is this: `fsck <device> -- -f -p`

**Comment by travisghansen** [comment]
Resolved in `v1.3.0`.

Enable the fs checks in your config as shown here: https://github.com/democratic-csi/democratic-csi/blob/master/examples/node-common.yaml

**Comment by isugimpy** [comment]
I don't mean to be a pain, but is there documentation on where to set those fs checks via the helm chart?  After doing a bunch of spelunking, I'm not finding the correct spot and would love to use this option.

**Comment by travisghansen** [comment]
Not a pain! Just pretend like the `node-common.yaml` file is part of the driver file you based off of directly.

the scope of the file belongs in this block here: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L14

**Comment by isugimpy** [comment]
Brilliant!  Thank you!

**Comment by chrisbsmith** [comment]
@travisghansen I just ran into this problem (I'm running helm chart 0.8.1). Looking at your link two comment above, seems the line of code has moved.

I tried to update my values file with the new `checkFileSystem` values, but the helm output didn't change. Can you point me to updated location where this should go in a values file? I'm trying to combine it with the freenas-iscsi example

**Comment by chrisbsmith** [comment]
Thanks @travisghansen . Here's my values file. The only addition from my working values file is the `node.mount` section.

```yaml
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.iscsi"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-iscsi-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    fsType: xfs

  mountOptions: []
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

controller:
  driver:
    imagePullPolicy: IfNotPresent

node:
  mount:
    checkFileSystem:
      enabled: true
      xfs:
        enabled: true
  driver:
    imagePullPolicy: IfNotPresent

driver:
  config:
    driver: freenas-iscsi
    instance_id:
    httpConnection:
      protocol: https
      host: storage.example.com
      port: 443
      allowInsecure: false
      apiVersion: 2
      username: k8s
      # password: 
      apiKey: "<truenasapikey>"
    sshConnection:
      host: <ip of truenas server>
      port: 22
      username: root
      # password: 
      privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----

    zfs:
      # the example below is useful for TrueNAS 12
      cli:
        paths:
          zfs: /usr/local/sbin/zfs
          zpool: /usr/local/sbin/zpool
          sudo: /usr/local/bin/sudo
          chroot: /usr/sbin/chroot
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less
      datasetParentName: k8s/iscsi/v
      detachedSnapshotsDatasetParentName: k8s/iscsi/s
      # "" (inherit), lz4, gzip-9, etc
      zvolCompression:
      # "" (inherit), on, off, verify
      zvolDedup:
      zvolEnableReservation: false
      # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
      zvolBlocksize:
    iscsi:
      targetPortal: "<ip>:<port>"
      targetPortals: []
      # leave empty to omit usage of -I with iscsiadm
      interface:
      namePrefix: csi-
      nameSuffix: "-cluster"
      # add as many as needed
      targetGroups:
        # get the correct ID from the "portal" section in the UI
        - targetGroupPortalGroup: 1
          # get the correct ID from the "initiators" section in the UI
          targetGroupInitiatorGroup: 1
          # None, CHAP, or CHAP Mutual
          targetGroupAuthType: None
          # get the correct ID from the "Authorized Access" section of the UI
          # only required if using Chap
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      # 512, 1024, 2048, or 4096,
      extentBlocksize: 4096
      # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
      extentRpm: "SSD"
      # 0-100 (0 == ignore)
      extentAvailThreshold: 0
```
