### ISSUE TITLE
Install custom CA certificate?

### ISSUE THREAD

**Issue by larsks** [democratic-csi/democratic-csi#89]
Our TrueNAS server is using a certificate signed by a local certificate authority. I'd like to be able to use:

```
        httpConnection:
          allowInsecure: true
          apiKey: ...
          host: truenas.local
          port: 443
          protocol: https
          allowInsecure: false
```

But:

- I'm not sure how to tell democratic-csi about the appropriate CA certificate, and 
- I'm not sure if there's a way to map the hostname to an ip address if the hostname isn't in DNS (on my local system I would just edit `/etc/hosts`, but not sure what the appropriate solution is in this case).

Is there a graceful away of accomplishing both of these tasks?
