### ISSUE TITLE
Is it possible to store login credentials in a secret?

### ISSUE THREAD

**Issue by monkeyman512** [democratic-csi/democratic-csi#93]
To start, thank you for all the work you are doing on this project. Second, I am new kubernetes so my don't be afraid to dumb things down.

I am trying to be security minded and keep my configuration data and and login credentials separated. In the current state of the project is it possible to have information like the SSH username/password stored in a secret?

If yes, an example would be greatly appreciated. If no, would it be possible to add it to the backlog?

**Comment by travisghansen** [comment]
Yes it is possible, see here: https://github.com/democratic-csi/charts/blob/master/stable/democratic-csi/values.yaml#L13

There are many ways of managing that data in gitops style, you could use:

- sealed-secrets (bitnami)
- sopssecrets (https://github.com/isindir/sops-secrets-operator)
- helm secrets

The syntax of the secret is:

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <foo>
  namespace: <bar>
data:
  driver-config-file.yaml: <base64 encoded yaml doc>
```

**Comment by ahgraber** [comment]
I think it would be useful to support individual secrets instead of forcing the entirety of the helm values as a secret.  This would allow granular updates of the secret instead of forcing revision of all helm values.

Specifically, values I'd like to see supported as secrets include:
* driver.config.driver.httpConnection.apiKey
* driver.config.driver.sshConnection.password
* driver.config.driver.sshConnection.privateKey

Allowing any secret management is a good first step, so thank you for at least allowing the values-as-secrets!  I just think more granular options would further improve this project!

**Comment by travisghansen** [comment]
@ahgraber thanks for the feedback! Some context may help a little. Given that the project is a collection of many drivers the configuration of the app itself has many driver-specific details (the whole `driver.config` block results in a single yaml file being injected into the container at runtime). The differences between drivers as to the structure of `driver.config` can be extremely varied (I'm currently working on a handful of new drivers for example including support for synology, an api-only truenas driver, and some others to support DIY-style configuration). The differences between these and the need to make the chart relatively generic results in the situation where the config is all one big (essentially generic) secret.

Having said that, the way the chart works and generates the yaml can be dealt with in a structured fashion using something like `helm secrets` where 1 file contains the bulk of the values and a second file encrypted with `helm secrets` could contain only the specific keys you've mentioned above.

Another tricky part with managing the secrets 'outside' the helm chart would be to ensure the pods restart when the secret has been updated. The chart currently generates a 'checksum' of the value to ensure pods roll as necessary.

Having said all that, I'm open to ideas/suggestions for sure!

**Comment by ahgraber** [comment]
Ah, that all makes sense.  I guess I hadn't fully grokked the 'driver-as-plugin' model; now that you've explained it as such, it makes sense that it'd be much easier to support the variety of driver configs as complete secrets as opposed to building out the logic on a per-driver basis.

**Comment by prometheanfire** [comment]
Hi, it looks like the file referenced here is missing.  should I open an issue in the chart repo?

https://github.com/democratic-csi/charts/blob/3ea2ee25b5d0ade9312b15a6accedc82fef9abd5/stable/democratic-csi/values.yaml#L18

**Comment by travisghansen** [comment]
Yeah that's not super clear. It meant to refer to this: https://github.com/democratic-csi/charts/blob/3ea2ee25b5d0ade9312b15a6accedc82fef9abd5/stable/democratic-csi/templates/driver-config-secret.yaml

**Comment by korncola** [comment]
@monkeyman512 just dont use helm: this is one reason it sucks, and this chart as most sucks also. **Its redicolous to save private ssh keys in git**, come on!

i generate manifests form the chart, and then i use proper `secretKeyRef`

**Comment by travisghansen** [comment]
Nobody is forcing you to use the chart or store private keys in git. If you'd like to provide more concrete wishlist for chart improvements I'm happy to hear them (or even better review PRs to make it `suck` less).

Regarding git, there are plenty of solutions for securely storing your ssh key (or other secrets) in git including sealed secrets, sops secrets, helm secrets, etc. I would be happy to provide some guidance on using them if needed.

**Comment by prometheanfire** [comment]
For what it's worth, I used sealed secrets just fine.

```yaml
driver:
  existingConfigSecret: custom-zfs-nfs-democratic-csi-driver-config
  config:
    driver: freenas-nfs
```

**Comment by vuurvoske** [comment]
> For what it's worth, I used sealed secrets just fine.
> 
> ```yaml
> driver:
>   existingConfigSecret: custom-zfs-nfs-democratic-csi-driver-config
>   config:
>     driver: freenas-nfs
> ```

I am struggling to get my secret working. What does the content of custom-zfs-nfs-democratic-csi-driver-config look like?

Is it like this:

```
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: truenas-democratic-csi-driver-config
  namespace: storage
  labels:
    app.kubernetes.io/instance: zfs-iscsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: democratic-csi
    helm.sh/chart: democratic-csi-0.14.7
stringData:
  driver-config-file.yaml: |-
     <somebas64encryptedfile>
```

And what exactly is in the base64? Is it like the example underneath? I've been trying for a long time now and i just can't get i to work:

```
    instance_id:
    httpConnection:
      protocol: https
      apiKey: 3-VDd1nOW96ERw1Zdlbt1luYTuiaYZCc23aTrC0QyeVI3qtvZt4RsQ55YF9w5QqBpG
      host: 192.168.1.10
      port: 443
      allowInsecure: true
    zfs:
      datasetParentName: storage/kubernetes/k8s-nfs/vols
      detachedSnapshotsDatasetParentName: storage/kubernetes/k8s-nfs/snaps
      zvolCompression:
      zvolDedup:
      zvolEnableReservation: false
      zvolBlocksize:
    iscsi:
      targetPortal: "192.168.1.100:3260"
      targetPortals: [] 
      interface:
      namePrefix: csi-
      nameSuffix: "-clustera"
      targetGroups:
        - targetGroupPortalGroup: 2
          targetGroupInitiatorGroup: 1
          targetGroupAuthType: None
          targetGroupAuthGroup:
      extentInsecureTpc: true
      extentXenCompat: false
      extentDisablePhysicalBlocksize: true
      extentBlocksize: 512
      extentRpm: "SSD"
      extentAvailThreshold: 0
```

**Comment by prometheanfire** [comment]
For the sealed secret, it's this.

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: custom-iscsi-democratic-config
  namespace: democratic-csi
spec:
  encryptedData:
    driver-config-file.yaml: base64_encoded_and_encrypted_data
```

For the iscsi driver it's something like this.  I'm using a LE cert so I shouldn't need allowInsecure anymore.

```
driver: freenas-iscsi
node:
  mount:
    checkFilesystem:
      xfs:
        enabled: true
      ext4:
        enabled: true
      btrfs:
        enabled: true
httpConnection:
  allowInsecure: true
  apiKey: API_KEY_GOES_HERE
  apiVersion: 2
  host: IP_GOES_HERE
  port: 443
  protocol: https
instance_id: null
iscsi:
  extentAvailThreshold: 0
  extentBlocksize: 4096
  extentDisablePhysicalBlocksize: true
  extentInsecureTpc: true
  extentRpm: SSD
  extentXenCompat: false
  interface: null
  namePrefix: csi-
  nameSuffix: -cluster
  targetGroups:
  - targetGroupAuthGroup: null
    targetGroupAuthType: None
    targetGroupInitiatorGroup: 2
    targetGroupPortalGroup: 1
  targetPortal: IP_GOES_HERE:3260
  targetPortals: []
sshConnection:
  host: IP_GOES_HERE
  port: 22
  privateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    REDACTED
    -----END OPENSSH PRIVATE KEY-----
  username: democratic-csi
zfs:
  cli:
    sudoEnabled: true
  datasetParentName: POOL_NAME_HERE/kubernetes/iscsi/vols
  detachedSnapshotsDatasetParentName: POOL_NAME_HERE/kubernetes/iscsi/snaps
  zvolBlocksize: null
  zvolCompression: ""
  zvolDedup: ""
  zvolEnableReservation: true
  datasetEnableQuotas: true
```
