### ISSUE TITLE
Resizing PVC error [ExternalExpanding]

### ISSUE THREAD

**Issue by mikeohyan** [democratic-csi/democratic-csi#97]
When updating the capacity of a PVC, we have been coming across an ExternalExpanding error, w/ message "Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC."

Running on a standard democratic-csi setup, running on Rancher and a NAS running TrueNAS-12.0-U2.1

I'm under the impression that the resizing function should be working, am I mistaken?

**Comment by mikeohyan** [comment]
Also, I currently don't have quotas enabled in my democratic-csi deployment.

**Comment by travisghansen** [comment]
Yeah it should work. Where is that error message is coming from? Can you send over the cleansed helm values for me?

**Comment by travisghansen** [comment]
While operationally resizing without quotas doesn’t make much sense the feature should still work in that configuration I think, but let me revisit the code as well to make sure I guess.

**Comment by travisghansen** [comment]
Ok so I looked at the code. If quotas are not enabled it should still ‘work’ but it’s a noop situation. The driver won’t actually set a quota and just returns a successful response.

**Comment by mikeohyan** [comment]
Oh interesting. As per your first request:

We're calling this:
```
helm upgrade \
    --install \
    --create-namespace \
    --values freenas-nfs.yaml \
    --namespace democratic-csi \
    trudy-nfs democratic-csi/democratic-csi
```

With these values:
```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

# add note here about volume expansion requirements
storageClasses:
- name: trudy-nfs-csi
  defaultClass: false
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: nfs
      
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"
    
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-nfs-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    # please see the most up-to-date example of the corresponding config here:
    # https://github.com/democratic-csi/democratic-csi/tree/master/examples
    # YOU MUST COPY THE DATA HERE INLINE!
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: <HOST>
      port: 80
      # This is the API key that we generated previously
      apiKey: <APIKEY>
      allowInsecure: true
      apiVersion: 2
    sshConnection:
      host: <HOST>
      port: <SSHPORT>
      username: root
      # This is the SSH key that we generated for passwordless authentication
      privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        <KEY>
        -----END RSA PRIVATE KEY-----
    zfs:
      # Make sure to use the storage pool that was created previously
      cli:
        sudoEnabled: true
      datasetParentName: <NFSPATH>/vols
      detachedSnapshotsDatasetParentName: <NFSPATH>/snaps
      datasetEnableQuotas: false
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: root
      datasetPermissionsGroup: wheel
    nfs:
      shareHost: <HOST>
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```

When a PVC is changed, it seems to be stuck in a state of "resizing" and from what I can understand, it's waiting for some external provider to complete the resizing task.

This is what the PVC gets stuck at when it's updated:

```
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 84Gi
  storageClassName: *****
  volumeMode: Filesystem
  volumeName: pvc-*****
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-06-07T12:28:42Z"
    status: "True"
    type: Resizing
  phase: Bound
```
